#!/usr/bin/php
<?php

date_default_timezone_set('America/Chicago');

$attempts = 0;

do {
    try {
        $user = "shrl";
        $pass = "UHouston!";
        $pdo = new PDO('mysql:host=10.0.0.1;dbname=shrl', $user, $pass, array(
            PDO::ATTR_PERSISTENT => true,
            PDO::ATTR_ERRMODE => true,
            PDO::ERRMODE_EXCEPTION => true
        ));
    } catch (PDOException $e) {
        echo 'Caught exception: ',  $e->getMessage(), "\n";
        $attempts++;
        sleep(1);
        continue;
    }
    break;
} while ($attempts < 5);


?>