#!/usr/bin/php
<?php

include('/var/lib/UIT-TSS-TOOLBOX/SHRL/PDO-connect');

$stdin = fopen('php://stdin', 'r');
$line = trim(fgets(STDIN));
fclose($stdin);

$arr = array();
$arr = explode('|', $line);

if ($arr[0] == "most-recent") {
    $table = $arr[1];
    $key = $arr[2];


    $sql = "SELECT $key FROM $table WHERE $key IS NOT NULL AND NOT $key = '' AND NOT $key = ' ' AND NOT LENGTH($key) = 0 ORDER BY TIME DESC LIMIT 1";

    foreach ($pdo->query($sql) as $row) {
        sleep(1);
    }
}

if ($arr[0] == "most-recent-where") {
    $table = $arr[1];
    $key = $arr[2];
    $whereKey = $arr[3];
    $whereValue = $arr[4];

    $sql = "SELECT $key FROM $table WHERE $key IS NOT NULL AND NOT $key = '' AND NOT $key = ' ' AND NOT LENGTH($key) = 0 AND $whereKey = '$whereValue' ORDER BY TIME DESC LIMIT 1";

    foreach ($pdo->query($sql) as $row) {
        $handle = popen("echo $row[key] | /var/lib/UIT-TSS-TOOLBOX/client', 'r');
        $read = fread($handle, 2096);
        echo $read;
        pclose($handle);
    }
    echo "END OF DATA";
}


?>
