#!/bin/bash

wan='enx00e04c6805bb'
lan='enp1s0'
pc='172.27.53.0/24'

ufw allow in on ${lan}
ufw allow out on ${lan}
ufw allow in on ${wan} from 172.27.53.0/24 proto tcp to any port 22
ufw deny out on ${wan} proto udp to any port 67
ufw deny out on ${wan} proto tcp to any port 67
ufw deny out on ${wan} proto udp to 172.27.53.0/24 port 123
ufw allow out on ${wan} proto udp to any port 123
ufw deny out on ${wan} proto tcp to any port 123
ufw default deny incoming
ufw enable
ufw reload

#iptables -t filter -F
#iptables -t filter -X

#iptables -t filter -A INPUT -i lo -j ACCEPT

#iptables -t filter -A INPUT -i $lan -j ACCEPT
#iptables -t filter -A INPUT -i $lan -j DROP

#iptables -t filter -A INPUT -i $wan -s $pc -p tcp --dport 22 -j ACCEPT
#iptables -t filter -A INPUT -i $wan -p tcp --dport 22 -j DROP
#iptables -t filter -A INPUT -i $wan -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
#iptables -t filter -A INPUT -j DROP

#iptables -t filter -A OUTPUT -o $wan -p udp --sport 67 -j DROP
#iptables -t filter -A OUTPUT -o $wan -p udp --sport 123 -j DROP
#iptables -t filter -A OUTPUT -o $wan -j ACCEPT
