#!/bin/bash
wanif='enx00e04c6805bb'
wan='172.27.53.0/24'
lanif='enp1s0'
lan='10.0.0.0/24'

# Disable IP forwarding and IPv6
sysctl -w net.ipv4.ip_forward=0
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl -p


# Clear Current Rules
iptables --table raw --flush
iptables --table raw --delete-chain
iptables --table nat --flush
iptables --table nat --delete-chain
iptables --table mangle --flush
iptables --table mangle --delete-chain
iptables --table filter --flush
iptables --table filter --delete-chain

# Loopback Traffic
iptables --table filter --append INPUT --in-interface lo --jump ACCEPT
iptables --table filter --append OUTPUT --out-interface lo --jump ACCEPT

# INPUT Traffic WAN
iptables --table filter --append INPUT --in-interface "${wanif}" --source "${wan}" --protocol tcp --match multiport --destination-ports 22 --jump ACCEPT
iptables --table filter --append INPUT --in-interface "${wanif}" --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT
iptables --table filter --append INPUT --in-interface "${wanif}" --jump LOG --log-prefix "Input Drop: "
iptables --table filter --append INPUT --in-interface "${wanif}" --jump DROP

# INPUT Traffic LAN
iptables --table filter --append INPUT --in-interface "${lanif}" --jump ACCEPT
iptables --table filter --append OUTPUT --out-interface "${lanif}" --jump ACCEPT

# OUTPUT Traffic WAN
iptables --table raw --append OUTPUT ! --out-interface "${lanif}" --protocol udp --match multiport --source-ports 67 --jump DROP
iptables --table filter --append OUTPUT --out-interface "${wanif}" --jump ACCEPT

# OUTPUT Traffic LAN
iptables --table filter --append OUTPUT --out-interface "${lanif}" --jump ACCEPT

# Default Policy
iptables --table filter --new-chain inputdrop
iptables --table filter --append INPUT --jump inputdrop
iptables --table filter --append inputdrop --in-interface "${wanif}" --protocol udp --match multiport --source-ports 137:138 --jump DROP
iptables --table filter --append inputdrop --jump LOG --log-prefix "Input Drop: "
iptables --table filter --append inputdrop --jump DROP

iptables --table filter --policy INPUT DROP
iptables --table filter --append FORWARD --jump LOG --log-prefix "Forward Drop: "
iptables --table filter --policy FORWARD DROP
iptables --table filter --append OUTPUT --jump LOG --log-prefix "Output Drop: "
iptables --table filter --policy OUTPUT DROP
