#!/bin/bash

mkdir -p /tmp/UIT-TSS-TOOLBOX

rm -r /tmp/UIT-TSS-TOOLBOX/

(cd /tmp/

git clone https://github.com/cameronraschke/UIT-TSS-TOOLBOX
)

chmod 755 /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/DEBIAN/postinst
dpkg-deb --build /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/
dpkg --install /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64.deb
