#!/bin/bash
# https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/securing_networks/creating-and-managing-tls-keys-and-certificates_securing-networks
# https://www.gnutls.org/manual/html_node/certtool-Invocation.html

## Only uncomment if creating new CA
# certtool --generate-privkey --sec-param High --key-type=ecdsa --outfile /etc/ssl/private/ca.key
# certtool --generate-self-signed --load-privkey /etc/ssl/pricate/ca.key --template ca.cfg --outfile /etc/ssl/certs/ca.crt
# sudo cp /etc/ssl/certs/ca.crt /usr/local/share/ca-certificates
# update-ca-certificates
chown root:root /etc/ssl/private/ca.key
chmod 600 /etc/ssl/private/ca.key

## Only uncomment if creating new certs for web server
certtool --generate-privkey --outfile /etc/ssl/private/uit-web.key
certtool --generate-request --load-privkey /etc/ssl/private/uit-web.key --template /root/uit-ssl/uit-web.cfg --outfile /root/uit-ssl/uit-web.crq
certtool --generate-certificate --load-request /root/uit-ssl/uit-web.crq --template /root/uit-ssl/uit-web.cfg --load-ca-certificate /etc/ssl/certs/ca.crt --load-ca-privkey /etc/ssl/private/ca.key --outfile /etc/ssl/certs/uit-web.crt

chmod 640 /etc/ssl/private/uit-web.key
chown root:www-data /etc/ssl/private/uit-web.key

certtool --certificate-info --infile /etc/ssl/certs/uit-web.crt

systemctl restart nginx