#!/usr/bin/php
<?php
include('/opt/UIT-TSS-TOOLBOX/include.php');


$stdin = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($stdin);

$db = new db();

$db->select($input);
if (arrFilter($db->get()) == 0)  {
    foreach ($db->get() as $key => $value) {
        if (strFilter($value["result"]) == 0) {
            echo $value["result"] . PHP_EOL;
        } else {
            echo "NULL" . PHP_EOL;
        }
    }
} else {
    echo "NULL" . PHP_EOL;
}

?>