#!/bin/bash

systemctl restart dnsmasq chrony mysql nginx apache2 nfs-kernel-server

/root/firewall

mount -o loop /opt/UIT-TSS-TOOLBOX/UIT-TSS-TOOLBOX-amd64.hybrid.iso /srv/UIT-TSS-TOOLBOX/client/iso/