#!/bin/bash

curl 'http://mickey.uit:8080/client/certs/uit-ca.crt' --output /usr/local/share/ca-certificates/uit-ca.crt &>/dev/null
curl 'http://mickey.uit:8080/client/certs/uit-web.crt' --output /usr/local/share/ca-certificates/uit-web.crt &>/dev/null
update-ca-certificates

/usr/bin/chmod 700 /usr/sbin/uit-*
/usr/bin/chown root:root /usr/sbin/uit-*
/usr/bin/chmod 750 /opt/uit-toolbox/ -R
/usr/bin/chown root:root /opt/uit-toolbox/ -R