#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/SHRL/PDO-connect');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d-His');



#Locations Table
$sql = "SELECT 'Tagnumber','Serial','Model','Dorm','Computer Number','Status','Problem','Datetime'";
foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
    $file = new SplFileObject("/tmp/shrl-report-location-".$time.".csv", 'a');
    $file->fputcsv($row);
    $file = null;
}

$sql = "SELECT DISTINCT tagnumber FROM locations";
foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
    $arr[] = $row['tagnumber'];
}

foreach ($arr as $row) {
    unset($tagNum);
    $tagNum = $row;
    $sql = "SELECT tagnumber,serial,model,dorm,location,status,problem,time FROM locations ";
    $sql .= "WHERE tagnumber = '$tagNum' ORDER BY time DESC LIMIT 1";
    foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
        $file = new SplFileObject("/tmp/shrl-report-location-".$time.".csv", 'a');
        $file->fputcsv($row);
        $file = null;
    }

}

$pdo = null;
?>