#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
DIM=$(tput dim)
RESET=$(tput sgr0)

while true; do

echo ""
echo ""
#Tagnumber Input
read -p "Please enter the ${BOLD}${GREEN}tagnumber${RESET}: " tagNum

#Serial number input
sql=$(echo "most-recent-where|locations|serial|tagnumber|$tagNum" | /var/lib/UIT-TSS-TOOLBOX/SHRL/select 2>/dev/null)
if [[ $sql == "NULL" || $sql == "" || $sql = " " ]]; then
	echo "No serial number data for ${tagNum}"
    read -p "Please enter the ${BOLD}${GREEN}serial number${RESET}: " serial
else
	echo "The last reported serial number for ${tagNum} was: ${BOLD}${sql}${RESET}"
    serial="${sql}"
fi

#Model number input
sql=$(echo "most-recent-where|locations|system_model|tagnumber|$tagNum" | /var/lib/UIT-TSS-TOOLBOX/SHRL/select 2>/dev/null)

if [[ $sql == "NULL" || $sql == "" || $sql = " " ]]; then
	echo "No model number data for ${tagNum}"
    read -p "Please enter the ${BOLD}${GREEN}model number${RESET}: " modelNumber
else
	echo "The last reported model name for ${tagNum} was: ${BOLD}${sql}${RESET}"
    modelNumber="${sql}"
fi

#Dorm location input
sql=$(echo "most-recent-where|locations|dorm|tagnumber|$tagNum" | /var/lib/UIT-TSS-TOOLBOX/SHRL/select 2>/dev/null)
echo "The last reported dorm for ${tagNum} was: ${BOLD}${sql}${RESET}"
read -p "Please enter the ${BOLD}${GREEN}dorm${RESET}: " dorm

#Computer number input
sql=$(echo "most-recent-where|locations|location|tagnumber|$tagNum" | /var/lib/UIT-TSS-TOOLBOX/SHRL/select 2>/dev/null)
echo "The last reported computer number for ${tagNum} was: ${BOLD}${sql}${RESET}"
read -p "Please enter the ${BOLD}${GREEN}computer number${RESET}: " location

#Status input
read -n 1 -p "Please enter the ${BOLD}${GREEN}status${RESET} ${BOLD}${GREEN}[1] ${RESET}${BOLD}Functioning ${BOLD}${GREEN}[2] ${RESET}${BOLD}Broken${RESET}: " status

if [[ $status == "1" ]]; then
    status="functioning"
    problem=""
elif [[ $status == "2" ]]; then
    echo ""
sql=$(echo "most-recent-where|locations|problem|tagnumber|$tagNum" | /var/lib/UIT-TSS-TOOLBOX/SHRL/select 2>/dev/null)
    echo "The last reported issue for ${tagNum} was: ${BOLD}${sql}${RESET}"
    status="broken"
    read -p "Please enter the ${BOLD}${GREEN}problem${GREEN}${RESET}: " problem
else
    status=""
    problem=""
fi

echo "location|${tagNum}|${serial}|${modelNumber}|${dorm}|${location}|${status}|${problem}" | /var/lib/UIT-TSS-TOOLBOX/SHRL/parse
done
