#!/bin/bash

RED=$(echo -ne "\033[31m")
GREEN=$(echo -ne "\033[32m")
BLUE=$(echo -ne "\033[34m")
BOLD=$(echo -ne "\033[1m")
DIM=$(echo -ne "\033[2m")
RESET=$(echo -ne "\033[0m")

REGEX='[[:digit:]]{6}'

while true; do
    echo -e "\n\n\n"
    read -r -p "${BOLD}Please enter the ${GREEN}tag${RESET}${BOLD}: " tagNum

    if [[ tagNum =~ $REGEX ]]; then
        sql=$(echo "SELECT task AS result FROM remote WHERE tagnumber = '${tagNum}'" | /var/lib/UIT-TSS-TOOLBOX/select)
    fi

    echo ""
    echo "The last task for ${tagNum} was ${sql}"
    echo "  ${BOLD}${GREEN}[0]${RESET} ${BOLD}No task"
    echo "  ${BOLD}${GREEN}[1]${RESET} ${BOLD}Data collection"
    read -r -p -N1 "${BOLD}Which task do you want ${BLUE}${tagNum}${RESET}${BOLD} to do? ${BOLD}Select ${GREEN}[0,1]${RESET}" task

    echo "remote|${tagNum}|${task}" | /var/lib/UIT-TSS-TOOLBOX/parse
done