#!/bin/bash

clientStart=$(date +%s.%N)
uit-sql-refresh-client
locationStart=$(date +%s.%N)
uit-sql-refresh-location
serverStart=$(date +%s.%N)
uit-sql-refresh-server
serverEnd=$(date +%s.%N)

clientTime=$(printf %.2f $( echo "$locationStart - $clientStart" | bc -l ))
locationTime=$(printf %.2f $( echo "$serverStart - $locationStart" | bc -l ))
serverTime=$(printf %.2f $( echo "$serverEnd - $serverStart" | bc -l ))

totalTime=$(printf %.2f $( echo "$serverEnd - $clientStart" | bc -l ))

echo ""
echo "Time to update clientstats: ${clientTime}s"
echo "Time to update locations: ${locationTime}s"
echo "Time to update serverstats: ${serverTime}s"
echo "Total time taken: ${totalTime}s"
