#!/usr/bin/php
<?php
/* "uit-sql-refresh-server" uses PHP to refresh the serverstats table in the mysql database. The
serverstats table is a table that contains the highest level of statistics in our database. 
This script iterates through every date starting at 2023-01-09 (our first database entry) until the 
current date and updates all of the entries accordingly. */

# Connect to database and include custom functions
include('/var/lib/UIT-TSS-TOOLBOX/mysql-functions');

# Set current date and time
$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

# Set $startDate to the oldest date entry in the DB.
$startDate = '2023-01-09';

# Clear globals
clearSQLGlobals();
clearTimeGlobals();

# Start the serverstats timer
echo timeSinceLastMarker("start", "Updating Serverstats") . PHP_EOL;

$cloneTime = array();
$nvmeEraseTime = array();
$hddEraseTime = array();
$eraseJobsLC = array();
$cloneJobsLC = array();
$arr1 = array();
$arr2 = array();
$arr3 = array();
$arr4 = array();

# Iterate through all the dates between $startDate and $date.
dbSelect("CALL iterateDate('$startDate', '$date')");
foreach ($arr as $key => $value) {

    # Set the variable $itDate to the iterated date.
    $itDate = $value["date"];

    # Start the timer that counts how much time each date takes to process.
    echo PHP_EOL;
    echo timeSinceLastMarker("markerStart", "Updating $itDate") . PHP_EOL;

    # If the current date does not exist in the serverstats table, then create an entry for the current date.
    dbSelectVal("SELECT date AS result FROM serverstats WHERE date = '$itDate'");
    if (filter($result) == 1) {
        echo "Inserting new serverstats entry for $itDate." . PHP_EOL;
        dbInsertSS("$itDate");
    }

    # Update laptop count. A laptop counts as a distinct tagnumber in jobstats which is in the Tech Commons.
    dbSelectVal("SELECT COUNT(DISTINCT tagnumber) AS result FROM jobstats WHERE department = 'techComm' AND date BETWEEN '$startDate' AND '$itDate'");
    dbUpdateSS("laptop_count", "$result", "$itDate");


    # Update the average time taken to clone a computer.
    // $sql = "SELECT ROUND(AVG(clone_time) / 60, 0) AS result FROM jobstats AS time1 INNER JOIN (SELECT time FROM jobstats WHERE clone_completed = '1' ";
    // $sql .= "AND date = '$itDate' GROUP BY tagnumber) AS time2 ON time1.time = time2.time";
    $sql = "SELECT clone_time / 60 AS result FROM jobstats WHERE clone_completed = '1' AND date = '$itDate'";
    dbSelect($sql);
    if (filterArr($arr) == 0) {
        foreach ($arr as $key => $value) {
            $cloneTime[] = $value["result"];
            $avg = array_filter($cloneTime);
            $avg = round(array_sum($avg) / count($avg), 0);
        }
    } else {
        $avg = array_filter($cloneTime);
        if (count($avg) > 0) {
            $avg = round(array_sum($avg) / count($avg), 0);
        } else {
            $avg = round(array_sum($avg), 0);
        }
    }
    dbUpdateSS("clone_avgtime", "$avg", "$itDate");


    # Update the average erase time of NVMe drives
    $sql = "SELECT erase_time / 60 AS result FROM jobstats WHERE erase_completed = '1' AND (disk LIKE 'nvme%' OR disk_type = 'nvme') AND date = '$itDate'";
    dbSelect($sql);
    if (filterArr($arr) == 0) {
        foreach ($arr as $key => $value) {
            $nvmeEraseTime[] = $value["result"];
            $avg = array_filter($nvmeEraseTime);
            $avg = round(array_sum($avg) / count($avg), 0);
        }
    } else {
        $avg = array_filter($nvmeEraseTime);
        if (count($avg) > 0) {
            $avg = round(array_sum($avg) / count($avg), 0);
        } else {
            $avg = round(array_sum($avg), 0);
        }
    }
    dbUpdateSS("nvme_erase_avgtime", "$avg", "$itDate");


    # Update the average erase time of SATA drives (SSDs and HDDs)
    $sql = "SELECT erase_time / 60 AS result FROM jobstats WHERE erase_completed = '1' AND (disk LIKE 'sd%' OR disk_type = 'hdd') AND date = '$itDate'";
    dbSelect($sql);
    if (filterArr($arr) == 0) {
        foreach ($arr as $key => $value) {
            $hddEraseTime[] = $value["result"];
            $avg = array_filter($hddEraseTime);
            $avg = round(array_sum($avg) / count($avg), 0);
        }
    } else {
        $avg = array_filter($hddEraseTime);
        if (count($avg) > 0) {
            $avg = round(array_sum($avg) / count($avg), 0);
        } else {
            $avg = round(array_sum($avg), 0);
        }
    }
    dbUpdateSS("hdd_erase_avgtime", "$avg", "$itDate");


    # Update the number of erase jobs that have completed
    $sql = "SELECT COUNT(erase_completed) AS result FROM jobstats WHERE erase_completed = '1' AND date = '$itDate'";
    dbSelect($sql);
    if (filterArr($arr) == 0) {
        foreach ($arr as $key => $value) {
            $eraseJobsLC[] = $value["result"];
            $sum = array_sum(array_filter($eraseJobsLC));
        }
    } else {
        $eraseJobsLC[] = $value["result"];
        $sum = array_sum(array_filter($eraseJobsLC));
    }
    dbUpdateSS("erase_jobs", "$sum", "$itDate");


    # Update the number of clone jobs that have completed
    $sql = "SELECT COUNT(clone_completed) AS result FROM jobstats WHERE clone_completed = '1' AND date = '$itDate'";
    dbSelect($sql);
    if (filterArr($arr) == 0) {
        foreach ($arr as $key => $value) {
            $cloneJobsLC[] = $value["result"];
            $sum = array_sum(array_filter($cloneJobsLC));
        }
    } else {
        $cloneJobsLC[] = $value["result"];
        $sum = array_sum(array_filter($cloneJobsLC));
    }
    dbUpdateSS("clone_jobs", "$sum", "$itDate");


    # Update count of all jobs (erase jobs + clone jobs)
    $sum = array_sum(array_filter($eraseJobsLC)) + array_sum(array_filter($cloneJobsLC));
    dbUpdateSS("all_jobs", "$sum", "$itDate");


    # Update date of last image update
    dbSelectVal("SELECT MAX(date) AS result FROM jobstats WHERE clone_master = '1' AND date BETWEEN '$startDate' AND '$itDate'");
    dbUpdateSS("last_image_update", "$result", "$itDate");


    # Get average TBW of non-HDD drives (writes only, SSD and NVMe included). This average takes into account drive model and specifications of the drive.
    dbSelect("SELECT disk_model,disk_type,disk_tbw,disk_tbr,disk_mtbf FROM static_disk_stats");
    foreach ($arr as $key => $value) {
        $diskModel = $value["disk_model"];
        $diskType = $value["disk_type"];
        $diskMaxTBW = $value["disk_tbw"];
        $diskMaxTBR = $value["disk_tbr"];
        $diskMaxMTBF = $value["disk_mtbf"];
        if ($diskType == "hdd") {
            if (filterNum($diskMaxTBW) == 0 && filterNum($diskMaxTBR) == 0) {
                $sql = "SELECT (disk_writes + disk_reads) / '$diskMaxTBW' AS result FROM jobstats AS time1 INNER JOIN (SELECT MAX(time) AS time FROM jobstats WHERE date = '$itDate' AND disk_model = '$diskModel' AND disk_writes IS NOT NULL AND disk_reads IS NOT NULL GROUP BY tagnumber) AS time2 ON time1.time = time2.time";
            } else {
                $sql = NULL;
            }
        } elseif ($diskType == "ssd" || $diskType == "nvme") {
            if (filterNum($diskMaxTBW) == 0 ) {
                $sql = "SELECT disk_writes / '$diskMaxTBW' AS result FROM jobstats AS time1 INNER JOIN (SELECT MAX(time) AS time FROM jobstats WHERE date = '$itDate' AND disk_model = '$diskModel' AND disk_writes IS NOT NULL GROUP BY tagnumber) AS time2 ON time1.time = time2.time";
            } else {
                $sql = NULL;
            }
        } else {
            $sql = NULL;
        }

        dbSelect($sql);
        if (!empty($arr)) {
            foreach ($arr as $key => $value) {
                if (filterNum($value["result"]) == 0) {
                    $arr1[] = $value["result"];
                }
            }
        }

        if (filterNum($diskMaxMTBF) == 0) {
            $sql = "SELECT disk_power_on_hours / '$diskMaxMTBF' AS result FROM jobstats AS time1 INNER JOIN (SELECT MAX(time) AS time FROM jobstats WHERE date = '$itDate' AND disk_model = '$diskModel' AND disk_power_on_hours IS NOT NULL GROUP BY tagnumber) AS time2 ON time1.time = time2.time";
        } else {
            $sql = NULL;
        }

        dbSelect($sql);
        if (!empty($arr)) {
            foreach ($arr as $key => $value) {
                if (filterNum($value["result"]) == 0) {
                    $arr2[] = $value["result"];
                }
            }
        }
    }
    
    $arr1 = array_filter($arr1);
    $arr2 = array_filter($arr2);
    $diskTBW = array_sum($arr1);
    $diskMTBF = array_sum($arr2);
    if (filterArr($arr1) == 0 && filterArr($arr2) == 0) {
        $diskHealth = round(100 - ((($diskTBW / count($arr1)) * 100) + (($diskMTBF / count($arr2)) * 100)) / 2, 2);
    } elseif (filterArr($arr1) == 0 && filterArr($arr2) == 1) {
        $diskHealth = round(100 - (($diskTBW / count($arr1)) * 100), 2);
    } elseif (filterArr($arr1) == 1 && filterArr($arr2) == 0) {
        $diskHealth = round(100 - (($diskMTBF / count($arr2)) * 100), 2);
    } else {
        $diskHealth = "NULL";
    }
    dbUpdateSS("disk_health", "$diskHealth", "$itDate");


    #Update the average battery health by selecting the most recent distinct tagnumber
    $sql = "SELECT battery_health AS result FROM jobstats AS time1 INNER JOIN (SELECT MAX(time) AS time FROM jobstats WHERE date = '$itDate' AND battery_health IS NOT NULL GROUP BY tagnumber) AS time2 ON time1.time = time2.time";
    dbSelect($sql);
    if (filterArr($arr) == 0) {
        foreach ($arr as $key => $value) {
            if (filterNum($value["result"]) == 0) {
                $arr3[] = $value["result"];
            }
        }
    }

    # Get battery charge cycle stats
    dbSelect("SELECT battery_model,battery_charge_cycles FROM static_battery_stats");
    foreach ($arr as $key => $value) {
        $batteryMaxChargeCycles = $value["battery_charge_cycles"];
        $batteryName = $value["battery_model"];
        # Select the most recent distinct tagnumber from jobstats
        $sql = "SELECT battery_charge_cycles AS result FROM jobstats AS time1 INNER JOIN (SELECT MAX(time) AS time FROM jobstats WHERE date = '$itDate' AND battery_model = '$batteryName' GROUP BY tagnumber) AS time2 ON time1.time = time2.time";
        #$sql = "SELECT battery_charge_cycles AS result FROM jobstats WHERE time IN (SELECT MAX(time) FROM jobstats WHERE date = '$itDate' ";
        #$sql .= "AND battery_model = '$batteryName' GROUP BY tagnumber)";
        dbSelect($sql);
        if (filterArr($arr) == 0) {
            foreach ($arr as $key => $value) {
                if (filterNum($value["result"]) == 0) {
                    $arr4[] = ($value["result"] / $batteryMaxChargeCycles) * 100;
                }
            }
        }
    }

    $arr3 = array_filter($arr3);
    $arr4 = array_filter($arr4);
    $batteryCharge = array_sum($arr3);
    $batteryChargeCycles = array_sum($arr4);
    if (filterArr($arr3) == 0 && filterNum($batteryCharge) == 0 && filterArr($arr4) == 0 && filterNum($batteryChargeCycles) == 0) {
        $batteryHealth = round((($batteryCharge / count($arr3)) + (100 - ($batteryChargeCycles / count($arr4)))) / 2, 2);
    } elseif (filterArr($arr3) == 0 && filterNum($batteryCharge) == 0 && (filterArr($arr4) == 1 || filterNum($batteryChargeCycles) == 1)) {
        $batteryHealth = round(($batteryCharge / count($arr3)), 2);
    } elseif ((filterArr($arr3) == 1 || filterNum($batteryCharge) == 1) && filterArr($arr4) == 0 && filterNum($batteryChargeCycles) == 0) {
        $batteryHealth = round(100 - ($batteryChargeCycles / count($arr4)), 2);
    } else {
        $batteryHealth = "NULL";
    }
    dbUpdateSS("battery_health", "$batteryHealth", "$itDate");

    # End the marker timer
    echo timeSinceLastMarker("markerEnd", "Time Taken for $itDate: ") . PHP_EOL;
}

# Stop the timer
echo timeSinceLastMarker("end", "Total Time to Update Serverstats: ") . PHP_EOL;

# Clear globals
clearSQLGlobals();
clearTimeGlobals();

?>