#!/usr/bin/php
<?php
# Connect to database and include custom functions
include('/etc/opt/UIT-TSS-TOOLBOX/server/include.php');

$timer = new scriptTimer();

echo "Updating remote table" . PHP_EOL;
$timer->start();

$db = new db();

$db->select("SELECT remote.tagnumber,
  jobstats.time,
  IF(TIME_TO_SEC(TIMEDIFF(NOW(), remote.present)) < 45, '1', '0') AS 'present_bool',
  t1.last_job_time,
  remote.disk_temp
  FROM remote
  INNER JOIN jobstats ON jobstats.tagnumber = remote.tagnumber
  INNER JOIN system_data ON system_data.tagnumber = remote.tagnumber
  LEFT JOIN
    (SELECT
        tagnumber, 
        ROW_NUMBER() OVER(PARTITION BY tagnumber ORDER BY time DESC) AS 'row_count', IF(SUBSTRING(time, 12, 24) = '00:00:00.000', NULL, time) AS 'last_job_time'
      FROM jobstats
      WHERE (erase_completed = 1 OR clone_completed = 1)) t1
    ON jobstats.tagnumber = t1.tagnumber
  INNER JOIN
    (SELECT time,
        ROW_NUMBER() OVER(PARTITION BY tagnumber ORDER BY time DESC) AS 'row_count'
      FROM jobstats WHERE system_serial IS NOT NULL) t2
    ON t2.time = jobstats.time
  WHERE jobstats.tagnumber IS NOT NULL 
  AND (t1.row_count = 1 OR t1.row_count IS NULL)
  AND t2.row_count = 1
  ORDER BY jobstats.time DESC");


foreach ($db->get() as $key => $value) {

  echo PHP_EOL;
  $timer->startMarker();

  # If tagnumber does not exist in the remote table, insert it.
  $db->select("SELECT tagnumber FROM jobstats GROUP BY tagnumber");
  foreach ($db->get() as $key => $value1) {
    $db->Pselect("SELECT tagnumber FROM remote WHERE tagnumber = :tagnumber", array(':tagnumber' => $value1["tagnumber"]));
    if (is_array($db->get()) === FALSE) {
      $db->insertRemote($value1["tagnumber"]);
    }
  }

  // Update presence
  $db->updateRemote($value["tagnumber"], "present_bool", $value["present_bool"]);

  // Update Last Job Time
  $db->updateRemote($value["tagnumber"], "last_job_time", $value["last_job_time"]);

  // Disk Temp
  if ($value["disk_temp"] >= "82") {
    $db->updateRemote($value["tagnumber"], "status", "fail - high disk temp");
    $db->updateRemote($value["tagnumber"], "job_queued", "shutdown");
  }

  echo "Time taken to update " . $value["tagnumber"] . ": " . $timer->endMarker() . "s" . PHP_EOL;
}

echo "(Updated) remote: " . $timer->end() . " seconds" . PHP_EOL;

?>