#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');
##### serverstats #####
echo "Updating serverstats" . PHP_EOL;

$date = date('Y-m-d',time());
$time = date('Y-m-d H:i:s', time());

$sql = "SELECT date FROM serverstats WHERE date = '$date'";
$results = $conn->query($sql);
while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
	$datecheck = $row['date'];
	if (empty($datecheck)) {
		echo "Inserting new serverstats entry for $date." . PHP_EOL;
		$sql = "INSERT INTO serverstats(date,time,laptop_count,last_image_update,all_jobs,clone_jobs,erase_jobs,";
		$sql .= "all_avgtime,clone_avgtime,nvme_erase_avgtime,ssd_erase_avgtime,tbw_pcnt,battery_health,boot_time) VALUES ('$date','$time',";
		$sql .= "NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)";
		$conn->query($sql);
	}
}


# Update date of report, create new report if none exist for today
$sql = "SELECT date FROM serverstats";
$arr = $conn->query($sql);
if (isset($arr)) {
	foreach ($arr as $row) {
	$sqldate = $row['date'];
	echo "Working on date: " . $row['date'] . PHP_EOL;

	# Update time
	$sql = "UPDATE serverstats SET time = '$time' WHERE date = '$date'";
	$conn->query($sql);

	# Update laptop count
	$sql = "SELECT DISTINCT tagnumber FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	$linecount = mysqli_num_rows($results);
	$sql = "UPDATE serverstats SET laptop_count = '$linecount' WHERE date = '$sqldate'";
	$conn->query($sql);

	# Update clone_avgtime
	$sql = "SELECT clone_time FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND clone_completed = 'Yes' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	$linecount = mysqli_num_rows($results);
	$sql = "SELECT SUM(clone_time) as clone_avgtime FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND clone_completed = 'Yes' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$sum = $row['clone_avgtime'];
		$sql = "UPDATE serverstats SET clone_avgtime = ROUND('$sum' / '$linecount' / 60, 0) WHERE date = '$sqldate'";
		$conn->query($sql);
	}

	# Update nvme_erase_avgtime
	$sql = "SELECT erase_time FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND erase_completed = 'yes' AND disk LIKE 'nvme%' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	$linecount = mysqli_num_rows($results);
	$sql = "SELECT SUM(erase_time) as nvme_erase_avgtime FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND erase_completed = 'yes' AND disk LIKE 'nvme%' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$sum = $row['nvme_erase_avgtime'];
		$sql = "UPDATE serverstats SET nvme_erase_avgtime = ROUND('$sum' / '$linecount' / 60, 0) WHERE date = '$sqldate'";
		$conn->query($sql);
	}

	# Update ssd_erase_avgtime
	$sql = "SELECT erase_time FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND erase_completed = 'yes' AND disk LIKE 'sd%' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	$linecount = mysqli_num_rows($results);
	$sql = "SELECT SUM(erase_time) as ssd_erase_avgtime FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND erase_completed = 'yes' AND disk LIKE 'sd%' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$sum = $row['ssd_erase_avgtime'];
		$sql = "UPDATE serverstats SET ssd_erase_avgtime = ROUND('$sum' / '$linecount' / 60, 0) WHERE date = '$sqldate'";
		$conn->query($sql);
	}

	# Update erase_jobs
	$sql = "SELECT COUNT(erase_completed) AS erase_jobs FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND erase_completed = 'Yes' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$eraseJobsLineCount = $row['erase_jobs'];
		$sql = "UPDATE serverstats SET erase_jobs = '$eraseJobsLineCount' WHERE date = '$sqldate'";
		$conn->query($sql);
	}

	# Update clone_jobs
	$sql = "SELECT COUNT(clone_completed) AS clone_jobs FROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND clone_completed = 'Yes' AND (date BETWEEN '2023-01-09' AND '$sqldate')";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$cloneJobsLineCount = $row['clone_jobs'];
		$sql = "UPDATE serverstats SET clone_jobs = '$cloneJobsLineCount' WHERE date = '$sqldate'";
		$conn->query($sql);
	}

	# Update all_jobs
	$allJobsLineCount = $eraseJobsLineCount + $cloneJobsLineCount;
	$sql = "UPDATE serverstats SET all_jobs = '$allJobsLineCount' WHERE date = '$sqldate'";
	$conn->query($sql);

	# Update last_image_update
	$sql = "SELECT date FROM jobstats WHERE clone_master = 'Yes' AND (date BETWEEN '2023-01-09' AND '$sqldate') ORDER BY time DESC LIMIT 1";
	$results = $conn->query($sql);
	$i = $results->fetch_all(MYSQLI_ASSOC);
	foreach($i as $key => $value) {
		$lastImageUpdate = $value['date'];
	}
	if (!empty($lastImageUpdate)) {
		$sql = "UPDATE serverstats SET last_image_update = '$lastImageUpdate' WHERE date = '$sqldate'";
		$conn->query($sql);
	}

	#TBW
	$sql = "SELECT ROUND((100-(SUM(disk_tbw)/(SUM(max_tbw)/1000))), 0) AS tbw_pcnt FROM clientstats WHERE NOT max_tbw = 'N/A' AND NOT disk_tbw LIKE '______'";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$pcntTBW = $row['tbw_pcnt'];
		$sql = "UPDATE serverstats SET tbw_pcnt = '$pcntTBW' WHERE date = '$date'";
		$conn->query($sql);
	}

	#Update boot_time
	$sql = "SELECT boot_time FROM clientstats WHERE NOT boot_time = '0'";
	$results = $conn->query($sql);
	$lineNums = mysqli_num_rows($results);

	$sql = "SELECT ROUND(SUM(boot_time), 2) as boot_time FROM clientstats WHERE NOT boot_time = '0'";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$sumBootTime = $row['boot_time'];
		$sql = "UPDATE serverstats SET boot_time = ROUND($sumBootTime / $lineNums, 0) WHERE date = '$date'";
		$conn->query($sql);
	}

	#Update battery_health
	$sql = "SELECT battery_health FROM clientstats WHERE NOT battery_health = ''";
	$results = $conn->query($sql);
	$lineNums = mysqli_num_rows($results);

	$sql = "SELECT ROUND(SUM(battery_health), 2) as battery_health FROM clientstats WHERE NOT battery_health = ''";
	$results = $conn->query($sql);
	while ($row = $results->fetch_array(MYSQLI_ASSOC)) {
		$sum = $row['battery_health'];
		$sql = "UPDATE serverstats SET battery_health = ROUND($sum / $lineNums, 0) WHERE date = '$date'";
		$conn->query($sql);
	}
}
}

$conn->close();
?>