#!/usr/bin/php
<?php

# Connect to database and include custom functions
include('/var/lib/UIT-TSS-TOOLBOX/include.php');

$timer = new scriptTimer();

# Start the timer
echo "Updating locations" . PHP_EOL;
$timer->start();

$db = new db();
# Iterate through distinct tagnumbers from jobstats with techComm UUIDs
$db->select("SELECT
jobstats.tagnumber,
t1.time AS 'last_job_time',
t2.max_time, t1.os_installed
FROM jobstats
LEFT JOIN
  (SELECT tagnumber, time, 
    (CASE
      WHEN erase_completed = 1 AND clone_completed = 1 THEN '1'
      WHEN erase_completed = 1 AND clone_completed IS NULL THEN '0'
      WHEN erase_completed IS NULL AND clone_completed = 1 THEN '1'
      ELSE '1'
    END) AS 'os_installed'
    FROM jobstats
    WHERE time IN (SELECT MAX(time) FROM jobstats WHERE (erase_completed = 1 OR clone_completed = 1) AND NOT time LIKE '% 00:00:00.000' GROUP BY tagnumber) AND tagnumber IS NOT NULL) t1
  ON jobstats.tagnumber = t1.tagnumber
LEFT JOIN
  (SELECT tagnumber, IF(SUBSTRING(MAX(time), 12, 24) = '00:00:00.000', NULL, MAX(time)) AS 'max_time'
    FROM locations
    GROUP BY tagnumber) t2
  ON jobstats.tagnumber = t2.tagnumber
INNER JOIN
  (SELECT time, ROW_NUMBER() OVER(PARTITION BY tagnumber ORDER BY time DESC) AS 'row_count' FROM jobstats) t3
  ON jobstats.time = t3.time
  WHERE t3.row_count = 1 
  AND jobstats.tagnumber IS NOT NULL");
  
foreach ($db->get() as $key => $value) {

  # Start the timer that counts how much time each tagnumber takes to process.
  echo PHP_EOL;
  $timer->startMarker();

  $db->updateLocation("os_installed", $value["os_installed"], $value["max_time"]);

  # End the timer and print how long it took to update the location table for a specific tagnumber.
  # End the marker timer
  echo "Time taken to update " . $value["tagnumber"] . ": " . $timer->endMarker() . "s" . PHP_EOL;
}

# Stop the timer
echo "(Updated) locations: " . $timer->end() . " seconds" . PHP_EOL;
?>