#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
DIM=$(tput dim)
RESET=$(tput sgr0)

read -n 1 -p "Please enter the ${BOLD}${BLUE}tagnumber${RESET}: " tagnumber
echo "UPDATE locations SET location = '${location}' WHERE tagnumber = '${tagnumber}'" | uit-tss-db