#!/bin/bash
rm -r /tmp/UIT-TSS-TOOLBOX/ 2>/dev/null

git clone https://github.com/cameronraschke/UIT-TSS-TOOLBOX /tmp/UIT-TSS-TOOLBOX/

chmod 755 /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/DEBIAN/postinst
dpkg-deb --build /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/
dpkg --install /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64.deb
