#!/bin/bash

RED=$(echo -ne "\033[31m")
GREEN=$(echo -ne "\033[32m")
BLUE=$(echo -ne "\033[34m")
BOLD=$(echo -ne "\033[1m")
DIM=$(echo -ne "\033[2m")
RESET=$(echo -ne "\033[0m")

REGEX='[[:digit:]]{6}'

while true; do
    echo -e "\n\n\n"
    echo "Updating presence..."
    uit-sql-refresh-remote
    tput cuu1
    tput el
    read -r -p "${BOLD}Please enter the ${GREEN}tag${RESET}${BOLD}: ${RESET}" tagNum


    if [[ $tagNum =~ $REGEX ]]; then
        sql=$(echo "SELECT present_bool AS result FROM remote WHERE tagnumber = '${tagNum}'" | /var/lib/UIT-TSS-TOOLBOX/select)
        if [[ $sql == "NULL" ]]; then
            echo "${BOLD}${RED}${tagNum}${RESET}${BOLD} is not currently present.${RESET}"
        fi

        sql=$(echo "SELECT task AS result FROM remote WHERE tagnumber = '${tagNum}'" | /var/lib/UIT-TSS-TOOLBOX/select)
        echo "The current task for ${tagNum} is ${sql}"
        echo "  ${BOLD}${GREEN}[1]${RESET} ${BOLD}Data collection${RESET}"
        echo "  ${BOLD}${GREEN}[2]${RESET} ${BOLD}Erase and Clone HP Laptops${RESET}"
        echo "  ${BOLD}${GREEN}[3]${RESET} ${BOLD}NVME Erase${RESET}"
        echo "  ${BOLD}${GREEN}[8]${RESET} ${BOLD}Play sound${RESET}"
        echo "  ${BOLD}${GREEN}[9]${RESET} ${BOLD}Update Client Package${RESET}"
        echo "  ${BOLD}${GREEN}[0]${RESET} ${BOLD}No task${RESET}"
        read -r -N1 -p "${BOLD}Which task do you want ${tagNum} to do? ${BOLD}Select ${GREEN}[0-9]${RESET} " task
        echo "remote|${tagNum}|task|${task}" | /var/lib/UIT-TSS-TOOLBOX/parse
    else
        echo "  ${BOLD}${GREEN}[1]${RESET} ${BOLD}Data collection${RESET}"
        echo "  ${BOLD}${GREEN}[2]${RESET} ${BOLD}Erase and Clone HP Laptops${RESET}"
        echo "  ${BOLD}${GREEN}[3]${RESET} ${BOLD}NVME Erase${RESET}"
        echo "  ${BOLD}${GREEN}[8]${RESET} ${BOLD}Play sound${RESET}"
        echo "  ${BOLD}${GREEN}[9]${RESET} ${BOLD}Update Client Package${RESET}"
        echo "  ${BOLD}${GREEN}[0]${RESET} ${BOLD}No task${RESET}"
        read -r -N1 -p "${BOLD}Which task do you want laptops in '${tagNum}' to do? ${BOLD}Select ${GREEN}[0-9]${RESET} " task
        echo ""
        sql=$(echo "SELECT tagnumber FROM locations WHERE time IN (SELECT MAX(time) FROM locations WHERE NOT location = 'Plugged in and booted on laptop table.' AND NOT location = 'Finished work on laptop table.' AND location = '${tagNum}' GROUP BY tagnumber);" | /var/lib/UIT-TSS-TOOLBOX/select)
        for i in ${sql}; do
            sql=$(echo "SELECT present_bool AS result FROM remote WHERE tagnumber = '${i}'" | /var/lib/UIT-TSS-TOOLBOX/select)
            if [[ $sql == "NULL" ]]; then
                echo "${BOLD}${RED}${i}${RESET}${BOLD} is not currently present.${RESET}"
                tput cuu1
                tput el
            fi
            echo "remote|${i}|task|${task}" | /var/lib/UIT-TSS-TOOLBOX/parse
        done
    fi



done