#!/bin/bash
rm -r /tmp/UIT-TSS-TOOLBOX/

git clone https://github.com/cameronraschke/UIT-TSS-TOOLBOX /tmp/

chmod 755 /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/DEBIAN/postinst
dpkg-deb --build /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/
dpkg-deb --install /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64.deb
