#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
DIM=$(tput dim)
RESET=$(tput sgr0)

while true; do
    echo ""
    echo ""
    echo ""
    read -p "Please enter the ${BOLD}${GREEN}tagnumber${RESET}: " tagNum
    sql=$(echo "SELECT system_serial AS result FROM locations WHERE tagnumber = '${tagNum}' AND tagnumber IS NOT NULL ORDER BY time DESC LIMIT 1" | /var/lib/UIT-TSS-TOOLBOX/select)
    echo "The last reported serial number for ${BOLD}${tagNum}${RESET} was: ${BOLD}${sql}${RESET}"
    if [[ $sql == "NULL" ]]; then
        read -p "Please enter the ${BOLD}${GREEN}laptop serial number${RESET}: " serial
    else
        serial="${sql}"
    fi

    diskModel=$(echo "SELECT disk_model AS result FROM jobstats WHERE tagnumber = '${tagNum}' AND disk_model IS NOT NULL ORDER BY time DESC LIMIT 1" | /var/lib/UIT-TSS-TOOLBOX/select)
    diskSize=$(echo "SELECT disk_size AS result FROM jobstats WHERE tagnumber = '${tagNum}' AND disk_size IS NOT NULL ORDER BY time DESC LIMIT 1" | /var/lib/UIT-TSS-TOOLBOX/select)
    diskSerial=$(echo "SELECT disk_serial AS result FROM jobstats WHERE tagnumber = '${tagNum}' AND disk_serial IS NOT NULL ORDER BY time DESC LIMIT 1" | /var/lib/UIT-TSS-TOOLBOX/select)

    if [[ $diskModel == "NULL" ]]; then
        read -p "Please enter the ${BOLD}${GREEN}disk model${RESET}: " diskModel
    fi

    if [[ $diskSize == "NULL" ]]; then
        read -p "Please enter the ${BOLD}${GREEN}disk size${RESET} in GB: " diskSize
    fi

    if [[ $diskSerial == "NULL" ]]; then
        read -p "Please enter the ${BOLD}${GREEN}disk serial number${RESET} in GB: " diskSerial
    fi

    echo "disk|${tagNum}|${serial}|${diskModel}|${diskSize}|${diskSerial}" | /var/lib/UIT-TSS-TOOLBOX/parse
done