#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/include.php');

$db = new db();

/*
#Job Table
$file = new SplFileObject("/tmp/laptop-report-job-".$time.".csv", 'w');
$db->select("CALL iterateJobCSV()");
foreach ($arr as $key => $value) {
    $file->fputcsv($value);
}
unset($value);
$file = null;


#Client Table
$file = new SplFileObject("/tmp/laptop-report-client-".$time.".csv", 'w');
$db->select("CALL iterateClientCSV()");
foreach ($arr as $key => $value) {
    $file->fputcsv($value);
}
unset($value);
$file = null;


#Locations Table
$file = new SplFileObject("/tmp/laptop-report-location-".$time.".csv", 'w');
$db->select("CALL iterateLocationsCSV()");
foreach ($arr as $key => $value) {
    $file->fputcsv($value);
}
unset($value);
$file = null;

# Property Table
$file = new SplFileObject("/tmp/laptop-report-property-".$time.".csv", 'w');
$db->select("CALL iterateLocationsPropertyCSV()");
foreach ($arr as $key => $value) {
    $file->fputcsv($value);
}
unset($value);
$file = null;
*/

// SHRL Report
$file = new SplFileObject("/tmp/laptop-report-shrl-".$date.".csv", 'w');
$db->AssocSelect("CALL iterateSHRLcsv()");
foreach ($db->get() as $key => $value) {
    $file->fputcsv($value);
}
unset($value);
$file = null;

#Server Table
$file = new SplFileObject("/tmp/laptop-report-server-".$time.".csv", 'w');
$db->AssocSelect("CALL iterateServerCSV()");
foreach ($db->get() as $key => $value) {
    $file->fputcsv($value);
}
unset($value);
$file = null;

?>