#!/bin/bash

DATE=$(date --iso)

mkdir /tmp/uit-tmp-reports/ 2>/dev/null

uit-sql-csv

mkdir /home/cameron/reports/${DATE}/

mv /tmp/uit-tmp-reports/* /home/cameron/reports/${DATE}/
mysqldump laptopDB -pUHouston! > /home/cameron/reports/${DATE}/laptopDB-${DATE}.sql