#!/usr/bin/php
<?php

/* uit-sql-refresh-location uses php to update the location table. This script
specifically focuses on matching a tagnumber from the clientstats table and
putting the tagnumber's corresponding serial number into the location table. */
include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');

$date = date('Y-m-d',time());
$dt = new DateTimeImmutable();
$time = $dt->format('Y-m-d H:i:s.v');

echo "Updating the location table" . PHP_EOL;

/* Select the serial numbers from clientstats which corresponds with the tagnumber 
in the locations table and update the locations table */
$sql = "SELECT tagnumber,chassis_serial FROM clientstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111'";
foreach ($pdo->query($sql) as $row) {
    $start = hrtime(true);
    $tagNum = $row['tagnumber'];
    $serial = $row['chassis_serial'];
    $sql = "UPDATE locations SET chassis_serial = '$serial' WHERE tagnumber = '$tagNum'";
    $pdo->query($sql);
    
    $end = hrtime(true);
	$executionTime = round(($end - $start) / 1e9, 4);
	echo "Updating computer $tagNum -> $serial: " . $executionTime . " seconds" . PHP_EOL;
}

# Close the connection
$pdo = null;
?>
