#!/bin/bash
DATE=$(date --iso)
mysqldump --user="laptops" --password="UHouston!" --host="10.0.0.1" laptopDB > /mnt/sql-backups/laptopDB-${DATE}.sql

rsync -a --delete /home/hp/ /mnt/hp
rsync -a --delete /home/dell/ /mnt/dell
rsync -a --delete /home/desktops/ /mnt/desktops