#!/bin/bash

DATE=$(date --iso)

uit-sql-refresh

uit-sql-csv

mv /tmp/laptop-report* /home/cameron
mysqldump laptopDB -pUHouston! > /home/cameron/laptopDB-${DATE}.sql
mysqldump shrl -pUHouston! > /home/cameron/shrl-${DATE}.sql

chown -R cameron:cameron /home/cameron/
