#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
DIM=$(tput dim)
RESET=$(tput sgr0)

while true; do
date=$(date '+%Y-%m-%d %H:%M:%S')

echo ""
echo ""
read -p "Please enter the ${BOLD}${GREEN}tagnumber${RESET}: " tagnumber
read -p "Please enter the ${BOLD}${GREEN}location${RESET}: " location
read -n 1 -p "Please enter the ${BOLD}${GREEN}status${RESET} ${BOLD}${GREEN}[1] ${RESET}${BOLD}Functioning ${BOLD}${GREEN}[2] ${RESET}${BOLD}Broken${RESET}: " status

if [[ $status == "1" ]]; then
    status="functioning"
    problem="N/A"
elif [[ $status == "2" ]]; then
    echo ""
    status="broken"
    read -p "Please enter the ${BOLD}${GREEN}problem${GREEN}${RESET}: " problem
else
    status="N/A"
    problem="N/A"
fi

echo "custom,${tagnumber},${location},${status},${problem}" | /var/lib/UIT-TSS-TOOLBOX/uit-tss-db-location-update
done