#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
DIM=$(tput dim)
RESET=$(tput sgr0)

while true; do
date=$(date '+%Y-%m-%d %H:%M:%S')

echo ""
echo ""
read -p "Please enter the ${BOLD}${GREEN}tagnumber${RESET}: " tagnumber
read -p "Please enter the ${BOLD}${GREEN}serial number${RESET}: " serial
read -p "Please enter the ${BOLD}${GREEN}location${RESET}: " location
read -n 1 -p "Please enter the ${BOLD}${GREEN}status${RESET} ${BOLD}${GREEN}[1] ${RESET}${BOLD}Functioning ${BOLD}${GREEN}[2] ${RESET}${BOLD}Broken${RESET}: " status

if [[ $status == "1" ]]; then
    status="functioning"
    problem=""
elif [[ $status == "2" ]]; then
    echo ""
    ISSUE=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" -s -N \
	--execute="SELECT problem FROM locations WHERE tagnumber = '${tagnumber}' ORDER BY time DESC LIMIT 1;")
    echo "The last reported issue for ${tagnumber} was: ${ISSUE}"
    status="broken"
    read -p "Please enter the ${BOLD}${GREEN}problem${GREEN}${RESET}: " problem
else
    status=""
    problem=""
fi

echo "custom|${tagnumber}|${serial}|${location}|${status}|${problem}" | /var/lib/UIT-TSS-TOOLBOX/uit-tss-db-location-update
done