#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');

$date = date('Y-m-d',time());
$time = date('Y-m-d H:i:s', time());

### Location Table ###
$sql = "SELECT tagnumber FROM clientstats WHERE NOT tagnumber = '000000'";
    foreach ($pdo->query($sql) as $row) {
        unset($tagNum);
        global $tagNum;
        $tagNum = $row;

        #Update Serial Numbers
        $sql = "SELECT chassis_serial FROM clientstats WHERE tagnumber = '$tagNum'";
        foreach ($pdo->query($sql) as $row) {
            $sql = "UPDATE locations SET chassis_serial = '$row' WHERE tagnumber = '$tagNum'";
            $pdo->query($sql);
        }
    }

$pdo = null;
?>