#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$date = date('Y-m-d',time());
$time = date('Y-m-d-His', time());

    $sql = "SELECT 'Job UUID','Tag Number','MAC Address','Date','Time','BIOS Vendor','BIOS Version','BIOS Last Update',";
    $sql .= "'BIOS Revision','BIOS Firmware','System Manufacturer','System Product Name','System Serial Number','System UUID',";
    $sql .= "'System SKU','System Family','Motherboard Manufacturer','Motherboard Serial Number','Chassis Manufcaturer',";
    $sql .= "'Chassis Type','Chassis Serial','Chassis Tag','Chassis PSU State','CPU Family','CPU Manufacturer','CPU ID',";
    $sql .= "'CPU Version','CPU Voltage','CPU Max Speed','CPU Current Speed','CPU Cores','CPU Threads','Battery Manufacturer',";
    $sql .= "'Battery Name','Battery Capacity','Battery Voltage','Battery Serial Number','Battery Manufacture Date','Boot Errors',";
    $sql .= "'Action','Reboot','Disk','Disk Size (GB)','Total Time','Erase Successful','Erase Mode','Total Erase Time','Percent of Disk Erased',";
    $sql .= "'Clone Successful','Clone Mode','Total Clone Time','Master Image','Clone Server','Clone Image','Last Image Update','Samba User' ";
    $sql .= "UNION ALL ";
    $sql .= "SELECT * ";
    $sql .= "FROM jobstats ORDER BY date DESC ";
    $sql .= "INTO OUTFILE '/tmp/laptop-report-job-".$date.".csv' ";
    $sql .= "FIELDS TERMINATED BY ',' ";
    $sql .= "ENCLOSED BY '\"' ";
    $sql .= "LINES TERMINATED BY '\\n'";

    $conn->query($sql);

    $sql = "SELECT 'Date','Laptop Count','Last Image Update','Total Jobs','Erase Jobs','Clone Jobs','Clone Avg. Time','NVME Avg. Erase Time','SSD Avg. Erase Time'
    UNION ALL
    SELECT date,laptop_count,last_image_update,all_jobs,erase_jobs,clone_jobs,clone_avgtime,nvme_erase_avgtime,ssd_erase_avgtime
    FROM serverstats ORDER BY date DESC 
    INTO OUTFILE '/tmp/laptop-report-server-".$date.".csv'
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'";

    $conn->query($sql);

    $sql = "SELECT 'Tag Number','Chassis Serial Number','Chassis Serial','Device Manufacturer','Device Model','Last Job Date','Average Time for All Operations','Average Time to Erase','Average Time to Clone','Total Jobs','Total Erase Jobs','Total Clone Jobs','BIOS Last Update','BIOS Version','Battery Manufacture Date'
    UNION ALL
    SELECT tagnumber,chassis_serial,device_type,system_productname,last_job_date,all_avgtime,erase_avgtime,clone_avgtime,all_jobs,erase_jobs,clone_jobs,bios_date,bios_version,
    FROM clientstats ORDER BY 'last_job_date' DESC 
    INTO OUTFILE '/tmp/laptop-report-client-".$date.".csv'
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'";

    $conn->query($sql);

$conn->close(); 
?>