#!/bin/bash

if [[ "$EUID" > 0 ]]; then 
  echo "Please run as root. Exiting..."
  exit 1
fi

read -p "Download from GitHub? [Y/n]: " gitBool

if [[ -z $gitBool || $gitBool == "y" || $gitBool == "Y" ]]; then
  rm -r /tmp/uit-toolbox/
  git clone https://github.com/cameronraschke/UIT-TSS-TOOLBOX /tmp/uit-toolbox/
fi

if [[ -d /tmp/uit-toolbox/uit-tss-toolbox_2.0-1_amd64 ]]; then
  apt --purge uit-toolbox
fi

chmod 755 /tmp/uit-toolbox/uit-tss-toolbox_2.0-1_amd64/DEBIAN/postinst
dpkg-deb --build /tmp/uit-toolbox/uit-tss-toolbox_2.0-1_amd64/ /tmp/uit-toolbox/uit-tss-toolbox_2.0-1_amd64.deb
apt --install /tmp/uit-toolbox/uit-tss-toolbox_2.0-1_amd64.deb

