#!/usr/bin/php
<?php

include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');
include('/var/lib/UIT-TSS-TOOLBOX/functions');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

echo "Updating the location table" . PHP_EOL;

/* Select the serial numbers from jobstats which corresponds with the tagnumber 
in the locations table and update the locations table */
$sql = "SELECT DISTINCT tagnumber FROM jobstats WHERE uuid LIKE 'techComm-%'";
foreach ($pdo->query($sql) as $row) {
    $start = hrtime(true);
    $tagNum = $row['tagnumber'];

    $sql = "SELECT system_serial FROM jobstats WHERE tagnumber = '$tagNum' AND system_serial IS NOT NULL ORDER BY time DESC LIMIT 1";
    $results = $pdo->query($sql);
    $serial = $results->fetchColumn();
    if (filter($serial) == 0) {
      $sql = "UPDATE locations SET system_serial = '$serial' WHERE tagnumber = '$tagNum'";
      $pdo->query($sql);
    } else {
      echo "Can't find serial for $tagNum" . PHP_EOL;
    }


    # Select most recent entry for a given client where the clone job has successfully completed.
    $sql = "SELECT time FROM jobstats WHERE time IN (SELECT MAX(time) FROM jobstats WHERE tagnumber = '$tagNum' AND clone_completed = 'Yes') ORDER BY time DESC LIMIT 1";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0) {
        $sql = "UPDATE locations SET os_installed = '$value' WHERE tagnumber = '$tagNum'";
    } else {
        $sql = "UPDATE locations SET os_installed = NULL WHERE tagnumber = '$tagNum'";
    }
    $pdo->query($sql);

    # End the timer and print how long it took to update the location table for a specific tagnumber.
    $end = hrtime(true);
    $executionTime = round(($end - $start) / 1e9, 4);
    echo "Updating location for $tagNum ($serial): " . $executionTime . " seconds" . PHP_EOL;
}

# Close the connection
$pdo = null;
?>