#!/bin/bash

clientStart=$(date +%s.%3N)
echo | /usr/sbin/uit-sql-refresh-client
locationStart=$(date +%s.%3N)
/usr/sbin/uit-sql-refresh-location
serverStart=$(date +%s.%3N)
/usr/sbin/uit-sql-refresh-server
serverEnd=$(date +%s.%3N)

clientTime=$( echo "$locationStart - $clientStart" | bc -l )
locationTime=$( echo "$serverEnd - $clientStart" | bc -l )
serverTime

totalTime=$(printf %.2f $( echo "$serverEnd - $clientStart" | bc -l ))

echo ""
echo "Total time taken: ${totalTime}"
