#!/usr/bin/php
<?php
/* "uit-sql-refresh-server" uses PHP to refresh the serverstats table in the mysql database. The
serverstats table is a historical aggregation of the highest level of statistics in our database. 
This script iterates through every date starting at 2023-01-09 (our first database entry) until the 
current date and updates all of the entries accordingly. */

# Connect to database and include custom functions
include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');
include('/var/lib/UIT-TSS-TOOLBOX/functions');

# Set current date and time
$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

echo "Updating serverstats" . PHP_EOL;

# Set $oldDate to the oldest date entry in the DB.
$oldDate = "2023-01-01";

# Iterate through all the dates between $oldDate and $date.
$sql = "CALL iterateDate('$oldDate', '$date')";
$stmt = $pdo->prepare($sql);
$stmt->execute();
foreach ($stmt->fetchColumn() as $row) {
    $stmt->closeCursor();

    # Start the timer that counts how much time each date takes to process.
    $start = hrtime(true);

    # Set the variable $sqlDate to the iterated date.
    $sqlDate = $row['date'];

    # If the current date does not exist in the serverstats table, then create an entry for the current date.
    $sql = "SELECT COUNT(date) FROM serverstats WHERE date = '$sqlDate'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value == "0") {
        echo "Inserting new serverstats entry for $sqlDate." . PHP_EOL;
        $sql = "INSERT INTO serverstats(date) VALUES ('$sqlDate')";
        $pdo->query($sql);
    }

    # Update laptop count. A laptop counts as a distinct tagnumber in jobstats which is in the Tech Commons.
    $sql = "SELECT COUNT(DISTINCT tagnumber) FROM jobstats WHERE (date BETWEEN '$oldDate' AND '$sqlDate') AND uuid LIKE 'techComm-%'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0) {
        $sql = "UPDATE serverstats SET laptop_count = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET laptop_count = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    # Update the average time taken to clone a computer.
    $sql = "SELECT ROUND(AVG(clone_time) / 60, 0) FROM jobstats WHERE clone_completed = 'Yes' AND date BETWEEN '$oldDate' AND '$sqlDate'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0) {
        $sql = "UPDATE serverstats SET clone_avgtime = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET clone_avgtime = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    # Update the average erase time of NVMe drives
    $sql = "SELECT ROUND(AVG(erase_time) / 60, 0) FROM jobstats WHERE erase_completed = 'yes' AND disk LIKE 'nvme%' AND date BETWEEN '$oldDate' AND '$sqlDate'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0) {
        $sql = "UPDATE serverstats SET nvme_erase_avgtime = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET nvme_erase_avgtime = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);



    # Update the average erase time of SATA drives (SSDs and HDDs)
    $sql = "SELECT ROUND(AVG(erase_time) / 60, 0) FROM jobstats WHERE erase_completed = 'yes' AND disk LIKE 'sd%' AND date BETWEEN '$oldDate' AND '$sqlDate'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0) {
        $sql = "UPDATE serverstats SET sata_erase_avgtime = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET sata_erase_avgtime = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    # Update the number of erase jobs that have completed
    $sql = "SELECT COUNT(erase_completed) FROM jobstats WHERE erase_completed = 'Yes' AND date BETWEEN '$oldDate' AND '$sqlDate'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($eraseJobsLC > 0) {
        $sql = "UPDATE serverstats SET erase_jobs = '$eraseJobsLC' WHERE date = '$sqlDate'";
    } else {
        $eraseJobsLC = 0;
    }
    $pdo->query($sql);


    # Update the number of clone jobs that have completed
    $sql = "SELECT COUNT(clone_completed) FROM jobstats WHERE clone_completed = 'Yes' AND date BETWEEN '$oldDate' AND '$sqlDate'";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($cloneJobsLC > 0) {
        $sql = "UPDATE serverstats SET clone_jobs = '$cloneJobsLC' WHERE date = '$sqlDate'";
    } else {
        $cloneJobsLC = 0;
    }
    $pdo->query($sql);


    # Update count of all jobs (erase jobs + clone jobs)
    $value = $eraseJobsLC + $cloneJobsLC;
    $sql = "UPDATE serverstats SET all_jobs = '$value' WHERE date = '$sqlDate'";
    $pdo->query($sql);


    # Update date of last image update
    $sql = "SELECT date FROM jobstats WHERE clone_master = 'Yes' AND date BETWEEN '$oldDate' AND '$sqlDate' ORDER BY time DESC LIMIT 1";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if (filter($value) == 0) {
        $sql = "UPDATE serverstats SET last_image_update = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET last_image_update = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    # TBW and TBR
    $arr = array();
    # Get average TBW of non-HDD drives (writes only, SSD and NVMe included). This average takes into account drive model and specifications of the drive.
    $sql = "SELECT disk_model,disk_tbw FROM static_disk_stats WHERE NOT disk_type = 'hdd'";
    foreach ($pdo->query($sql) as $row) {
        $diskTBW = $row["disk_tbw"];
        $diskModel = $row["disk_model"];
        # Select the most recent distinct tagnumber from jobstats
        $sql = "SELECT (AVG(disk_writes) / '$diskTBW' * 100) FROM jobstats WHERE time IN (SELECT MAX(time) FROM jobstats WHERE date BETWEEN '$oldDate' AND '$sqlDate' ";
        $sql .= "AND disk_writes IS NOT NULL AND disk_model = '$diskModel' GROUP BY tagnumber)";
        $results = $pdo->query($sql);
        $value = $results->fetchColumn();

        array_push($arr, $value);
    }

    # Get average TBW and TBR of HDDs (reads and writes). This average takes into account drive model and specifications of the drive.
    $sql = "SELECT disk_model,disk_tbw,disk_tbr FROM static_disk_stats WHERE disk_type = 'hdd'";
    foreach ($pdo->query($sql) as $row) {
        $diskTBW = $row["disk_tbw"];
        $diskTBR = $row["disk_tbr"];
        $diskModel = $row["disk_model"];
        # Select the most recent distinct tagnumber from jobstats
        $sql = "SELECT ((AVG(disk_writes) / '$diskTBW' * 100) + (AVG(disk_reads) / '$diskTBR' * 100)) / 2 FROM jobstats WHERE time IN (SELECT MAX(time) FROM jobstats WHERE date BETWEEN '$oldDate' AND '$sqlDate' ";
        $sql .= "AND (disk_writes IS NOT NULL OR disk_reads IS NOT NULL) AND disk_model = '$diskModel' GROUP BY tagnumber)";
        $results = $pdo->query($sql);
        $value = $results->fetchColumn();

        array_push($arr, $value);
    }

    # Update the average wear of disks based on reads and writes
    $avg = array_filter($arr);
    if (filter($avg) == 0) {
        $value = array_sum($avg) / count($avg);
        $sql = "UPDATE serverstats SET tbw_pcnt = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET tbw_pcnt = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    # Get the average disk power on hours (MTBF/MTTF) and average that against the disk's specifications.
    $arr = array();
    $sql = "SELECT disk_model,disk_mtbf FROM static_disk_stats WHERE disk_mtbf IS NOT NULL";
    foreach ($pdo->query($sql) as $row) {
        $diskModel = $row["disk_model"];
        $diskMTBF = $row["disk_mtbf"];
        # Select the most recent distinct tagnumber from jobstats
        $sql = "SELECT ROUND(AVG(disk_power_on_hours) / '$diskMTBF' * 100, 2) FROM jobstats WHERE time IN (SELECT MAX(time) FROM jobstats WHERE date BETWEEN '$oldDate' AND '$sqlDate' AND disk_model = '$diskModel' ";
        $sql .= "AND disk_power_on_hours IS NOT NULL GROUP BY tagnumber)";
        $results = $pdo->query($sql);
        $value = $results->fetchColumn();

        array_push($arr, $value);
    }
    # Update the MTBF for the disks. This average takes into account drive model and specifications of the drive.
    $avg = array_filter($arr);
    if (filter($avg) == 0) {
        $value = array_sum($avg) / count($avg);
        $sql = "UPDATE serverstats SET disk_mtbf = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET disk_mtbf = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    #Update the average boot time
    $sql = "SELECT ROUND(AVG(boot_time), 0) FROM jobstats WHERE boot_time IS NOT NULL";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0 && filter($value) == 0) {
        $sql = "UPDATE serverstats SET boot_time = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET boot_time = NULL WHERE date = '$sqlDate'";
    }
    $pdo->query($sql);


    #Update the average battery health by selecting the most recent distinct tagnumber
    $sql = "SELECT ROUND(AVG(battery_health), 0) FROM jobstats WHERE time IN (SELECT MAX(time) FROM jobstats WHERE date BETWEEN '$oldDate' AND '$sqlDate' ";
    $sql .= "AND battery_health IS NOT NULL GROUP BY tagnumber)";
    $results = $pdo->query($sql);
    $value = $results->fetchColumn();
    if ($value > 0 && filter($value) == 0) {
        $sql = "UPDATE serverstats SET battery_health = '$value' WHERE date = '$sqlDate'";
    } else {
        $sql = "UPDATE serverstats SET battery_health = NULL WHERE date = '$sqlDate'";
    }
    $results = $pdo->query($sql);


    # Output time taken for specific date
    $end = hrtime(true);
    $executionTime = round(($end - $start) / 1e9, 4);
    echo "Updated serverstats for $sqlDate: " . $executionTime . " seconds" . PHP_EOL;
}

# Close the connection to the DB
$pdo = null;
?>