#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$date = date('Y-m-d',time());
$time = date('Y-m-d-His', time());

    $sql = "SELECT 'Job UUID','Tag Number','MAC Address','Date','Time','BIOS Vendor','BIOS Version','BIOS Last Update',";
    $sql .= "'BIOS Revision','BIOS Firmware','System Manufacturer','System Product Name','System Serial Number','System UUID',";
    $sql .= "'System SKU','System Family','Motherboard Manufacturer','Motherboard Serial Number','Chassis Manufcaturer',";
    $sql .= "'Chassis Type','Chassis Serial','Chassis Tag','PSU State','CPU Family','CPU Manufacturer','CPU ID',";
    $sql .= "'CPU Version','CPU Voltage','CPU Max Speed','CPU Current Speed','CPU Cores','CPU Threads','RAM Serial','Battery Manufacturer',";
    $sql .= "'Battery Name','Battery Capacity','Battery Voltage','Battery Serial Number','Battery Manufacture Date','Battery Alarm (Boolean)','Battery Health (Max Charge %)','Battery Charge Cycles','Boot Errors',";
    $sql .= "'Boot Time','Action','Reboot','Disk','Disk Size (GB)','Disk Model','Disk Serial','Disk Firmware','Disk Health Check','Disk Temperature','Disk Reads (TB)','Disk Writes (TB)',";
    $sql .= "'Max TBW (per the manufacturer)','Total Time','Erase Successful','Erase Mode','Total Erase Time','Percent of Disk Erased',";
    $sql .= "'Clone Successful','Clone Mode','Total Clone Time','Master Image','Clone Server','Clone Image','Last Image Update','Linux User' ";
    $sql .= "\nUNION ALL ";
    $sql .= "\nSELECT * ";
    $sql .= "\nFROM jobstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' ORDER BY date DESC ";
    $sql .= "\nINTO OUTFILE '/tmp/laptop-report-job-".$time.".csv' ";
    $sql .= "\nFIELDS TERMINATED BY ',' ";
    $sql .= "\nENCLOSED BY '\"' ";
    $sql .= "\nLINES TERMINATED BY '\\n'";

    $conn->query($sql);

    $sql = "SELECT 'Date','Laptop Count','Last Image Update','Total Erase and/or Clone Jobs','Erase Jobs','Clone Jobs','Clone Avg. Time (minutes)','NVME Avg. Erase Time (minutes)','SSD Avg. Erase Time (minutes)','Average Disk Wear Percent','Average Battery Max Charge Level Percent','Average Boot Time (seconds)'
    UNION ALL
    SELECT date,laptop_count,last_image_update,all_jobs,erase_jobs,clone_jobs,clone_avgtime,nvme_erase_avgtime,ssd_erase_avgtime,tbw_pcnt,battery_health,boot_time
    FROM serverstats ORDER BY date DESC 
    INTO OUTFILE '/tmp/laptop-report-server-".$time.".csv'
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'";

    $conn->query($sql);

    #Client Table
    $sql = "SELECT tagnumber,chassis_serial,device_type,system_productname,last_job_date,all_avgtime,erase_avgtime,clone_avgtime,all_jobs,erase_jobs,clone_jobs,bios_date,bios_version,battery_manufacturedate,battery_health,disk_tbw,max_tbw,boot_time ";
    $sql .= "FROM clientstats WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' ORDER BY 'last_job_date' DESC";
    $results = $conn->query($sql);
    while ($row = mysqli_fetch_array($results, MYSQLI_ASSOC)) {
        $arr[] = $row;
    }

    $sql = "SELECT 'Tag Number','Chassis Serial Number','Device Manufacturer','Device Model','Last Job Date',";
    $sql .= "'Average Time for All Operations (minutes)','Average Time to Erase (minutes)','Average Time to Clone (minutes)','Total Jobs (Erase and Clone Jobs)','Total Erase Jobs',";
    $sql .= "'Total Clone Jobs','BIOS Last Update','BIOS Version','Battery Manufacture Date','Battery Max Charge in Percent','Terabytes Written (TBW)','Max Terabytes Written (TBW)', 'Average Boot Time (seconds)'";
    $results = $conn->query($sql);
    while ($row = mysqli_fetch_array($results, MYSQLI_ASSOC)) {
        $file = new SplFileObject("/home/file/laptop-report-client-".$time.".csv", 'a');
        $file->fputcsv($row);
        $file = null;
    }

    
    foreach ($arr as $row) {
            $file = new SplFileObject("/home/file/laptop-report-client-".$time.".csv", 'a');
            $file->fputcsv($row);
            $file = null;
    }


    #Locations Table
    $sql = "SELECT DISTINCT tagnumber FROM locations WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111'";
    $results = $conn->query($sql);
    while ($row = mysqli_fetch_array($results, MYSQLI_ASSOC)) {
        $arr[] = $row['tagnumber'];
    }

    $sql = "SELECT 'Tagnumber', 'Serial Number', 'Current Location', 'Status', 'Description of Problem (if applicable)', 'Datetime of Most Recent Update'";
    $results = $conn->query($sql);
    while ($row = mysqli_fetch_array($results, MYSQLI_ASSOC)) {
        $file = new SplFileObject("/home/file/laptop-report-location-".$time.".csv", 'a');
        $file->fputcsv($row);
        $file = null;
    }

    
    foreach ($arr as $row) {
        unset($tagNum);
        $tagNum = $row;
        $sql = "SELECT tagnumber,chassis_serial,location,status,problem,time FROM locations WHERE NOT tagnumber = '000000' AND NOT tagnumber = '111111' AND tagnumber = '$tagNum' ORDER BY time DESC LIMIT 1";
        $results = $conn->query($sql);
        while ($row = mysqli_fetch_array($results, MYSQLI_ASSOC)) {
            $file = new SplFileObject("/home/file/laptop-report-location-".$time.".csv", 'a');
            $file->fputcsv($row);
            $file = null;
        }

    }

$conn->close(); 
?>