#!/bin/bash

# Set passwords for various services
echo "Updating Passwords..."

# MySQL Admin Password
echo "  --MySQL Admin Password"
if [[ -f /home/cameron/.my.cnf ]]; then 
    DB_ADMIN_PASSWD=$(cat /home/cameron/.my.cnf | grep '^password=' | sed 's/password=//g' | head -n1)
else
 DB_ADMIN_PASSWD=$(cat /home/cameron/.uit-passwd | grep '^DB_ADMIN_PASSWD=' | sed 's/DB_ADMIN_PASSWD=//g')
fi

# MySQL Client Password
echo "  --Client Password"
CLIENT_PASSWD=$(cat /home/cameron/.uit-passwd | grep '^CLIENT_PASSWD=' | sed 's/CLIENT_PASSWD=//g')

# Website PHP Scripts
echo "  --Web Service Password"
WEB_SVC_PASSWD=$(openssl rand 30 | hexdump | tr -d '\n' | sed 's/[[:space:]]//g' | head -n1 | md5sum | awk '{print $1}')

# All Users for the Website
echo "  --Web User Password"
WEB_USER_PASSWD=$(cat /home/cameron/.uit-passwd | grep '^WEB_USER_PASSWD=' | sed 's/WEB_USER_PASSWD=//g')

# Webmaster Email
echo "  --Webmaster Email"
WEBMASTER_EMAIL=$(cat /home/cameron/.uit-passwd | grep '^WEBMASTER_EMAIL=' | sed 's/WEBMASTER_EMAIL=//g')

# Webmaster Name
echo "  --Webmaster Name"
WEBMASTER_NAME=$(cat /home/cameron/.uit-passwd | grep '^WEBMASTER_NAME=' | sed 's/WEBMASTER_NAME=//g')

# IP Address of the Server
echo "  --Server IP Address"
IP_ADDRESS=$(cat /home/cameron/.uit-passwd | grep '^IP_ADDRESS=' | sed 's/IP_ADDRESS=//g')


# MySQL Users
mysql --database='laptopDB' --execute="ALTER USER 'cameron'@'localhost' IDENTIFIED BY '${DB_ADMIN_PASSWD}';"
mysql --database='laptopDB' --execute="ALTER USER 'uitclient'@'10.0.0.0/255.255.0.0' IDENTIFIED BY '${CLIENT_PASSWD}';"
mysql --database='laptopDB' --execute="ALTER USER 'uitweb'@'localhost' IDENTIFIED BY '${WEB_SVC_PASSWD}';"
mysql --database='laptopDB' --execute="UPDATE logins SET username = MD5(username);"
mysql --database='laptopDB' --execute="UPDATE logins SET password = MD5('${WEB_USER_PASSWD}');"

# Client-side Bash Scripts
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /srv/UIT-TSS-TOOLBOX/client/src/uit-tss-client_2.0-1_amd64/usr/sbin/uit-tss-client
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /srv/UIT-TSS-TOOLBOX/client/src/uit-tss-client_2.0-1_amd64/opt/UIT-TSS-TOOLBOX/include.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /srv/UIT-TSS-TOOLBOX/client/src/uit-tss-client_2.0-1_amd64/opt/UIT-TSS-TOOLBOX/api-client.php

# Web PHP Scripts
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/management/locations.php
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/management/api/endpoint.php
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/management/bash/uit-print-pdf
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/management/php/include.php
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/management/api/print-page.php

# This is the client password because clients don't know web password
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /var/www/html/management/api/refresh-client.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /var/www/html/management/tagnumber.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /var/www/html/management/locations.php

# Webmaster Name and Email
sed --in-place "s/WEBMASTER_EMAIL/${WEBMASTER_EMAIL}/g" /var/www/html/management/index.php
sed --in-place "s/WEBMASTER_NAME/${WEBMASTER_NAME}/g" /var/www/html/management/index.php

# Webmaster IP Address, Name, and Email for SSL Cert
sed --in-place "s/WEBMASTER_EMAIL/\"${WEBMASTER_EMAIL}\"/g" /root/uit-ssl/uit-web.cfg
sed --in-place "s/IP_ADDRESS/${IP_ADDRESS}/g" /root/uit-ssl/uit-web.cfg
sed --in-place "s/WEBMASTER_NAME/${WEBMASTER_NAME}/g" /root/uit-ssl/uit-web.cfg

echo "NOTICE: Rebuild the client .deb file by running uit-git-script in order to update the client passwords."
echo "Done."