#!/bin/bash

DTIME=$(date '+%F-%H%M%S')
mysqldump --user="root" --password="UHouston!" --host="localhost" laptopDB > /home/images/sql-backups/laptopDB-${DTIME}.sql

rsync -a --delete /home/images/sql-backups /mnt/images
