#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/mysql-functions');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d-His');



#Job Table
dbSelect("CALL iterateJobLabels()");
foreach ($arr as $key => $value) {
    $file = new SplFileObject("/tmp/laptop-report-job-".$time.".csv", 'a');
    $file->fputcsv($value);
    $file = null;
}

dbSelect("SELECT * FROM jobstats WHERE department = 'techComm' ORDER BY time DESC");
foreach ($arr as $key => $value) {
    $file = new SplFileObject("/tmp/laptop-report-job-".$time.".csv", 'a');
    $file->fputcsv($value);
    $file = null;
}



#Server Table
unset($arr);
unset($row);
$sql = "SELECT date,laptop_count,CONCAT(tbw_pcnt, '%'),CONCAT(disk_mtbf, '%'),CONCAT(battery_health, '%'),all_jobs,clone_jobs,erase_jobs,";
$sql .= "CONCAT(clone_avgtime, ' minutes'),CONCAT(nvme_erase_avgtime, ' minutes'),CONCAT(sata_erase_avgtime, ' minutes'),last_image_update ";
$sql .= "FROM serverstats ORDER BY date DESC";
foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
    $arr[] = $row;
}

$sql = "SELECT 'Date','Computer Count','Disk TBW/R','Disk MTBF','Battery Max Charge Level','Total Erase and Clone Jobs','Clone Jobs','Erase Jobs',";
$sql .= "'Clone Time','NVME Erase Time','SATA Erase Time','Last Image Update'";
foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
    $file = new SplFileObject("/tmp/laptop-report-server-".$time.".csv", 'a');
    $file->fputcsv($row);
    $file = null;
}

foreach ($arr as $row) {
    $file = new SplFileObject("/tmp/laptop-report-server-".$time.".csv", 'a');
    $file->fputcsv($row);
    $file = null;
}



#Client Table
dbSelect("CALL iterateClientLabels()");
foreach ($arr as $key => $value) {
    $file = new SplFileObject("/tmp/laptop-report-client-".$time.".csv", 'a');
    $file->fputcsv($value);
    $file = null;
}

$sql = "SELECT tagnumber,system_serial,system_manufacturer,system_model,last_job_time,";
$sql .= "CONCAT(battery_health, '%'),CONCAT(tbw_pcnt, '%'),";
$sql .= "CONCAT(erase_avgtime, ' minutes'),CONCAT(clone_avgtime, ' minutes'),all_jobs ";
$sql .= "FROM clientstats ORDER BY last_job_time DESC";
dbSelect($sql);
foreach ($arr as $key => $value) {
        $file = new SplFileObject("/tmp/laptop-report-client-".$time.".csv", 'a');
        $file->fputcsv($row);
        $file = null;
}



#Locations Table
unset($arr);
unset($row);
$sql = "SELECT DISTINCT tagnumber FROM locations";
foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
    $arr[] = $row['tagnumber'];
}

$sql = "SELECT 'Tagnumber', 'Serial Number', 'Location', 'Status', 'Description of Problem', 'Most Recent Update'";
foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
    $file = new SplFileObject("/tmp/laptop-report-location-".$time.".csv", 'a');
    $file->fputcsv($row);
    $file = null;
}


foreach ($arr as $row) {
    unset($tagNum);
    $tagNum = $row;
    $sql = "SELECT tagnumber,system_serial,location,status,problem,time ";
    $sql .= "FROM locations ";
    $sql .= "WHERE tagnumber = '$tagNum' ORDER BY time DESC LIMIT 1";
    foreach ($pdo->query($sql, PDO::FETCH_ASSOC) as $row) {
        $file = new SplFileObject("/tmp/laptop-report-location-".$time.".csv", 'a');
        $file->fputcsv($row);
        $file = null;
    }

}

$pdo = null;
?>