#!/bin/bash

/usr/bin/chmod 700 /usr/sbin/uit-tss-*
/usr/bin/chown root:root /usr/sbin/uit-tss-*

/usr/bin/apt purge live-build -y
/usr/bin/wget http://ftp.us.debian.org/debian/pool/main/l/live-build/live-build_20220505_all.deb --output-document=/opt/debian-live.deb
/usr/bin/apt install /opt/debian-live.deb -y
/usr/bin/rm /opt/debian-live.deb
