#!/bin/bash

/usr/bin/apt purge live-build -y
/usr/bin/apt install wget -y
/usr/bin/wget http://ftp.us.debian.org/debian/pool/main/l/live-build/live-build_20220505_all.deb --output-document=/opt/debian-live.deb
/usr/bin/apt install /opt/debian-live.deb
/usr/bin/rm /opt/debian-live.deb
