#!/usr/bin/php
<?php

function filter ($string) {
    if ($string == "" || $string == " " || $string == "NULL" || empty($string) || is_null($string)) {
        return 1;
    } else {
        return 0;
    }
}

function clearArray() {
    unset($GLOBALS["result"]);
    unset($GLOBALS["arr"]);
}

?>