#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');
include('/var/lib/UIT-TSS-TOOLBOX/functions');

function dbSelect ($sql) {
    clearSQLGlobals();
    if (filter($sql) == 0) {
        global $pdo;
        global $arr;
        $arr = array();
        $sql = $pdo->prepare($sql);
        $sql->execute();
        $arr = $sql->fetchAll(PDO::FETCH_ASSOC);
    } else {
        $result = "NULL";
        $arr = array();
    }
}

function dbSelectVal ($sql) {
    clearSQLGlobals();
    if (filter($sql) == 0) {
        global $pdo;
        global $result;
        $arr = array();
        $sql = $pdo->prepare($sql);
        $sql->execute();
        $arr = $sql->fetchAll(PDO::FETCH_ASSOC);
        if (filterArr($arr) == 0) {
            foreach ($arr as $key => $value) {
                $result = $value["result"];
            }
        } else {
            $result = "NULL";
            $arr = array();
        }
    } else {
        $result = "NULL";
        $arr = array();
    }
}

function dbInsertJob ($uuid) {
    if (filter($uuid) == 0) {
        global $pdo;
        $sql = "INSERT INTO jobstats (uuid) VALUES (:uuid)";
        $stmt = $pdo->prepare($sql);

        $stmt->bindParam(':uuid', $uuid, PDO::PARAM_STR);

        if (filter($stmt) == 0) {
            $stmt->execute();
        }
    }
}

function dbUpdateJob ($key, $value, $uuid) {
    if (filter($key) == 0 && filter($uuid) == 0) {
        global $pdo;
        $sql = "UPDATE jobstats SET $key = :value WHERE uuid = :uuid";
        $stmt = $pdo->prepare($sql);

        if (is_numeric($value) && filterNum($value) == 1) {
            $value = "NULL";
        }

        if (filter($value) == 0) {
            $stmt->bindParam(':value', $value, PDO::PARAM_STR);
            $stmt->bindParam(':uuid', $uuid, PDO::PARAM_STR);
        } else {
            $stmt->bindParam(':value', $value, PDO::PARAM_NULL);
            $stmt->bindParam(':uuid', $uuid, PDO::PARAM_STR);
        }

        if (filter($stmt) == 0) {
            $stmt->execute();
        }
    }
}

function dbInsertLocation ($time) {
    if (filter($time) == 0) {
        global $pdo;
        $sql = "INSERT INTO locations (time) VALUES (:time)";
        $stmt = $pdo->prepare($sql);

        $stmt->bindParam(':time', $time, PDO::PARAM_STR);

        if (filter($stmt) == 0) {
            $stmt->execute();
        }
    }
}

function dbUpdateLocation ($key, $value, $time) {
    if (filter($key) == 0 && filter($time) == 0) {
        global $pdo;
        $sql = "UPDATE locations SET $key = :value WHERE time = :time";
        $stmt = $pdo->prepare($sql);

        if (filter($value) == 0) {
            if ($value == "TRUE") {
                $value = "0";
                $stmt->bindParam(':value', $value, PDO::PARAM_STR);
                $stmt->bindParam(':time', $time, PDO::PARAM_STR);
            } elseif ($value == "FALSE") {
                $value = "1";
                $stmt->bindParam(':value', $value, PDO::PARAM_STR);
                $stmt->bindParam(':time', $time, PDO::PARAM_STR);
            }
            $stmt->bindParam(':value', $value, PDO::PARAM_STR);
            $stmt->bindParam(':time', $time, PDO::PARAM_STR);
        } else {
            $stmt->bindParam(':value', $value, PDO::PARAM_NULL);
            $stmt->bindParam(':time', $time, PDO::PARAM_STR);
        }

        if (filter($stmt) == 0) {
            $stmt->execute();
        }
    }
}

function dbInsertRemote ($tagNum) {
    if (filter($tagNum) == 0) {
        global $pdo;
        $sql = "INSERT INTO remote (tagnumber) VALUES (:tagNum)";
        $stmt = $pdo->prepare($sql);

        $stmt->bindParam(':tagNum', $tagNum, PDO::PARAM_STR);

        if (filter($stmt) == 0) {
            $stmt->execute();
        }
    }
}

function dbUpdateRemote ($tagNum, $key, $value) {
    if (filter($tagNum) == 0 && filter($key) == 0) {
        global $pdo;
        $sql = "UPDATE remote SET $key = :value WHERE tagnumber = :tagNum";
        $stmt = $pdo->prepare($sql);

        if (filter($value) == 0) {
            $stmt->bindParam(':tagNum', $tagNum, PDO::PARAM_STR);
            $stmt->bindParam(':value', $value, PDO::PARAM_STR);
        } else {
            $stmt->bindParam(':tagNum', $tagNum, PDO::PARAM_STR);
            $stmt->bindParam(':value', $value, PDO::PARAM_NULL);
        }

        if (filter($stmt) == 0) {
            $stmt->execute();
        }
    }
}

?>