#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/mysql-functions');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

$fd = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($fd);

$arr = explode('|', $input);

if ($arr[0] == "init") {
    $uuid = $arr[1];
    $tagNum = $arr[2];
    $macAddr = $arr[3];
    $wifiMac = $arr[4];

    dbInsertJob($uuid);

    dbUpdateJob("tagnumber", "$tagNum", "$uuid");
    dbUpdateJob("etheraddress", "$macAddr", "$uuid");
    dbUpdateJob("wifi_mac", "$wifiMac", "$uuid");
    dbUpdateJob("date", "$date", "$uuid");
    dbUpdateJob("time", "$time", "$uuid");

} elseif ($arr[0] == "location") {

    if (empty($arr[7])) {
        $arr[7] = "unknown";
    }

    if ($arr[1] == "begin") {
        $tagNum = $arr[2];
        $serial = $arr[3];
        $location = "Plugged in and booted on laptop table.";
        $status = "functioning";
        $problem = "";
    }

    if ($arr[1] == "end") {
        $tagNum = $arr[2];
        $serial = $arr[3];
        $location = "Finished work on laptop table.";
        $status = "functioning";
        $problem = "";
    }

    if ($arr[1] == "custom") {
        $tagNum = $arr[2];
        $serial = $arr[3];
        $location = $arr[4];
        $status = $arr[5];
        $problem = $arr[6];
    }

    $uuid = uniqid("location-", true);
    
    #Not the same insert statement as above, ether address is DEFAULT here.
    dbInsertJob($uuid);
    dbUpdateJob("tagnumber", "$tagNum", "$uuid");
    dbUpdateJob("system_serial", "$serial", "$uuid");
    dbUpdateJob("date", "$date", "$uuid");
    dbUpdateJob("time", "$time", "$uuid");

    dbInsertLocation("$time");
    dbUpdateLocation("tagnumber", "$tagNum", "$time");
    dbUpdateLocation("system_serial", "$serial", "$time");
    dbUpdateLocation("location", "$location", "$time");
    dbUpdateLocation("status", "$status", "$time");
    dbUpdateLocation("problem", "$problem", "$time");

} elseif ($arr[0] == "general") {
    $key = $arr[1];
    $value = $arr[2];
    $uuid = $arr[3];

    if ($key == "cpu_temp") {
        $value = bcdiv("$value", 1000, 2);
    }

    if (!empty($arr[4]) && $arr[4] == "nvme") {
        $value = bcmul("$value", 512, 4);
        $value = bcdiv("$value", 1000000000, 2);
    } elseif (!empty($arr[4]) && $arr[4] == "sata") {
        $value = bcmul("$value", 512, 4);
        $value = bcdiv("$value", 1000000000000, 2);
    }

    if ($key == "disk_type") {
        if ($value == "1") {
            $value = "hdd";
        } elseif ($value == "0") {
            $value = "ssd";
        } elseif ($value == "nvme") {
            $value = "nvme";
        } else {
            $value = "NULL";
        }
    }

    if ($key == "ram_capacity") {
        $value = round("$value" / 1000000, 2);
    }

    dbUpdateJob("$key", "$value", "$uuid");

} elseif ($arr[0] == "system-stats") {
    $uuid = $arr[2]
    if ($arr[1] == "cpu") {
        $cpuSum = null;
        $cpuLineCount = null;
        $lines = file('/tmp/cpu-usage.txt');
        foreach ($lines as $lineNum => $line) {
            $cpuSum = $cpuSum + $line;
            $cpuLineCount = $cpuLineCount + 1;
        }
        $cpuAvg = $cpuSum / $lineNum;
        dbUpdateJob("cpu_usage", "$cpuAvg", "$uuid");
    } elseif ($arr[1] == "network") {
        echo "bruh";
    }
} else {
    exit();
}

?>