#!/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$date = date('Y-m-d',time());
$time = date('Y-m-d H:i:s', time());

$stdin = fopen('php://stdin', 'r');
$line = trim(fgets(STDIN));

$arr = explode(',', $line);

$uuid = $arr[1];

if ($arr[0] == "disk") {
    $sql = "UPDATE jobstats SET '".$arr[1]."' = '".$arr[3]."' WHERE uuid = '".$arr[2]."'";
}

?>