#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

$stdin = fopen('php://stdin', 'r');
$line = trim(fgets(STDIN));
fclose($stdin);

$arr = explode('|', $line);

if ($arr[0] == "init") {
    $uuid = $arr[1];
    $tagNum = $arr[2];
    $macAddr = $arr[3];
    $sql = "INSERT INTO jobstats(uuid,tagnumber,etheraddress,wifi_mac,date,time,bios_vendor,bios_version,bios_date,";
    $sql .= "bios_revision,bios_firmware,system_manufacturer,system_productname,system_serial,system_uuid,system_sku,";
    $sql .= "system_family,motherboard_manufacturer,motherboard_serial,chassis_manufacturer,chassis_type,chassis_serial,";
    $sql .= "chassis_tag,chassis_psu,cpu_family,cpu_manufacturer,cpu_id,cpu_version,cpu_voltage,cpu_maxspeed,cpu_currentspeed,";
    $sql .= "cpu_cores,cpu_threads,cpu_temp,ram_serial,battery_manufacturer,battery_name,battery_capacity,battery_voltage,battery_serial,";
    $sql .= "battery_manufacturedate,battery_alarm,battery_health,battery_charge_cycles,boot_errors,boot_time,action,reboot,disk,";
    $sql .= "disksizegb,disk_model,disk_serial,disk_firmware,disk_health,disk_temp,disk_reads,disk_writes,max_tbw,all_time,";
    $sql .= "erase_completed,erase_mode,erase_time,erase_diskpercent,clone_completed,clone_mode,clone_time,clone_master,";
    $sql .= "clone_server,clone_image,clone_imageupdate,clone_sambauser) ";
    $sql .= "VALUES ('$uuid','$tagNum','$macAddr',DEFAULT,'$date','$time',DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT)";
    $pdo->query($sql);

} elseif ($arr[0] == "disk") {
    $key = $arr[1];
    $value = $arr[2];
    $uuid = $arr[3];
    if (!empty($value)) {
        if (!empty($arr[4]) && $arr[4] == "nvme"){
            $value = bcmul("$value", 512, 4);
            $value = bcdiv("$value", 1000000000, 2);
        }
        if (!empty($arr[4]) && $arr[4] == "sata"){
            $value = bcmul("$value", 512, 4);
            $value = bcdiv("$value", 1000000000000, 2);
        }
        $sql = "UPDATE jobstats SET $key = '$value' WHERE uuid = '$uuid'";
        $pdo->query($sql);
    } else {
        $sql = "UPDATE jobstats SET $key = NULL WHERE uuid = '$uuid'";
        $pdo->query($sql);
    }
    
} elseif ($arr[0] == "battery") {
    $key = $arr[1];
    $uuid = $arr[2];
    $value = $arr[3];
    if ($arr[1] == "battery_charge_cycles") { 
        if ($value == 0 || empty($value)){
            $sql = "UPDATE jobstats SET $key = NULL WHERE uuid = '$uuid'";
            $pdo->query($sql);
        } else {
            $sql = "UPDATE jobstats SET $key = '$value' WHERE uuid = '$uuid'";
            $pdo->query($sql);
        }
    }
    $sql = "UPDATE jobstats SET $key = '$value' WHERE uuid = '$uuid'";
    $pdo->query($sql);
} elseif ($arr[0] == "update") {
    $value = $arr[1];
    system("ssh cameron@mickey.uit 'echo $value | uit-sql-refresh-client'", $return);
} elseif ($arr[0] == "checktag") {
    $systemSerial = $arr[1];
    $sql = "SELECT tagnumber FROM clientstats WHERE chassis_serial = '$systemSerial'";
    foreach ($pdo->query($sql) as $row) {
        $tagNum = $row['tagnumber'];
        $fd = fopen("/tmp/tagnumber.uit", "w");
        fwrite($fd, $tagNum);
        fclose($fd);
    }
} elseif ($arr[0] == "location") {

    if (empty($arr[7])) {
        $arr[7] = "unknown";
    }

    if ($arr[1] == "begin") {
        $tagNum = $arr[2];
        $serial = $arr[3];
        $location = "Plugged in and booted on laptop table.";
        $status = "functioning";
        $problem = "";
        $department = $arr[7];
    }

    if ($arr[1] == "end") {
        $tagNum = $arr[2];
        $serial = $arr[3];
        $location = "Finished work on laptop table.";
        $status = "functioning";
        $problem = "";
        $department = $arr[7];
    }

    if ($arr[1] == "custom") {
        $tagNum = $arr[2];
        $serial = $arr[3];
        $location = $arr[4];
        $status = $arr[5];
        $problem = $arr[6];
        $department = $arr[7];
    }

    if ($department == "1") {
        $uuid = uniqid("techComm-", true);
    } elseif ($department == "2") {
        $uuid = uniqid("shrl-", true);
    } else {
        $uuid = uniqid("manual", true);
    }
    
    #Not the same insert statement as above, ether address is DEFAULT here.
    $sql = "INSERT INTO jobstats(uuid,tagnumber,etheraddress,wifi_mac,date,time,bios_vendor,bios_version,bios_date,";
    $sql .= "bios_revision,bios_firmware,system_manufacturer,system_productname,system_serial,system_uuid,system_sku,";
    $sql .= "system_family,motherboard_manufacturer,motherboard_serial,chassis_manufacturer,chassis_type,chassis_serial,";
    $sql .= "chassis_tag,chassis_psu,cpu_family,cpu_manufacturer,cpu_id,cpu_version,cpu_voltage,cpu_maxspeed,cpu_currentspeed,";
    $sql .= "cpu_cores,cpu_threads,cpu_temp,ram_serial,battery_manufacturer,battery_name,battery_capacity,battery_voltage,battery_serial,";
    $sql .= "battery_manufacturedate,battery_alarm,battery_health,battery_charge_cycles,boot_errors,boot_time,action,reboot,disk,";
    $sql .= "disksizegb,disk_model,disk_serial,disk_firmware,disk_health,disk_temp,disk_reads,disk_writes,max_tbw,all_time,";
    $sql .= "erase_completed,erase_mode,erase_time,erase_diskpercent,clone_completed,clone_mode,clone_time,clone_master,";
    $sql .= "clone_server,clone_image,clone_imageupdate,clone_sambauser) ";
    $sql .= "VALUES ('$uuid','$tagNum',DEFAULT,DEFAULT,'$date','$time',DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,";
    $sql .= "DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT)";
    $pdo->query($sql);

    $sql = "INSERT INTO locations(tagnumber,chassis_serial,location,status,problem,time) ";
    $sql .= "VALUES (:tagnumber, :chassis_serial, :location, :status, :problem, :time)";
    $stmt = $pdo->prepare($sql);
    $stmt->bindParam(':tagnumber', $tagNum, PDO::PARAM_STR);
    $stmt->bindParam(':chassis_serial', $serial, PDO::PARAM_STR);
    $stmt->bindParam(':location', $location, PDO::PARAM_STR);
    $stmt->bindParam(':status', $status, PDO::PARAM_STR);
    $stmt->bindParam(':problem', $problem, PDO::PARAM_STR);
    $stmt->bindParam(':time', $time, PDO::PARAM_STR);
    $stmt->execute();
    $stmt = null;

    $sql = "UPDATE locations SET location = NULL WHERE location = ''";
    $pdo->query($sql);
    
    $sql = "UPDATE locations SET status = NULL WHERE status = ''";
    $pdo->query($sql);
    
    $sql = "UPDATE locations SET problem = NULL WHERE problem = ''";
    $pdo->query($sql);
    
    $sql = "UPDATE locations SET chassis_serial = NULL WHERE chassis_serial = ''";
    $pdo->query($sql);

} elseif ($arr[0] == "cpu") {
    $key = $arr[1];
    $value = $arr[2];
    $uuid = $arr[3];

    $value = bcdiv("$value", 1000, 2);

    $sql = "UPDATE jobstats SET $key = '$value' WHERE uuid = '$uuid'";
    $pdo->query($sql);

} elseif ($arr[0] == "general") {
    $key = $arr[1];
    $value = $arr[2];
    $uuid = $arr[3];
    $sql = "UPDATE jobstats SET $key = '$value' WHERE uuid = '$uuid'";
    $pdo->query($sql);
} else {
    echo "No query specified.";
}

$pdo = null;

?>
