#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$date = date('Y-m-d',time());
$time = date('Y-m-d H:i:s', time());

$default = "NULL";
$status = "functioning";

$stdin = fopen('php://stdin', 'r');
$line = trim(fgets(STDIN));

$arr = explode(',', $line);

if ($arr[0] == "begin") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = "Plugged in and booted on laptop table.";
}

if ($arr[0] == "end") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = "Finished work on laptop table.";
}

if ($arr[0] == "custom") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = $arr[3];
}

$conn->query("INSERT INTO locations(tagnumber,chassis_serial,location,status,problem,time) VALUES ('$tagNum','$serial','$location','$status',$default,'$time')");

?>