#!/bin/bash

echo "These are the current disks and their sizes:"
lsblk --nodeps --noheadings -o NAME,SIZE --exclude 1,2,7,11
echo ""
echo "Which disk do you want to flash with the ISO?"
        select ISODISK in $(lsblk --nodeps --noheadings -o NAME --exclude 1,2,7,11)
        do
        echo ""
        echo "$(lsblk /dev/${ISODISK} -o NAME,SIZE,TYPE,MOUNTPOINT)"
        echo "You chose ${ISODISK}. Is this correct?"
        PS3="Select a drive: "
        read -p "All data on ${ISODISK} will be deleted. Press Enter to confirm...."
        break
        done
echo "Unmounting ${ISODISK}"
umount /dev/${ISODISK} &>/dev/null
echo "Making FAT filesystem"
mkfs.vfat -I /dev/${ISODISK} &>/dev/null
echo "Creating new label: UITTSSCLONE"
mlabel -i /dev/${ISODISK} ::UITTSSCLONE &>/dev/null
echo "Writing ISO to disk, this may take a while..."
dd if=/opt/UIT-TSS-CLONE/UIT-TSS-CLONE-amd64.hybrid.iso of=/dev/${ISODISK} bs=4M status=progress
