#!/bin/bash
DATE=$(date --iso)

for tagNum in $(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT tagnumber FROM jobstats;"); do

	exists=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" -s -N --execute="\
		SELECT tagnumber FROM clientstats WHERE tagnumber = '${tagNum}';")

		if [[ $exists == $tagNum ]]; then
			mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" -s -N --execute="\
    			UPDATE clientstats \
     			SET tagnumber = '${tagNum}' \
    			WHERE tagnumber = '${tagNum}';"
		else
			mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" -s -N --execute="\
				INSERT INTO clientstats(
				tagnumber, \
				all_lastdate, \
				all_lastuuid, \
				all_time, \
				all_avgtime, \
				all_avgtimetoday, \
				erase_avgtime, \
				erase_avgtimetoday, \
				clone_avgtime, \
				clone_avgtimetoday, \
				all_jobs, \
				all_jobstoday, \
				erase_jobs, \
				erase_jobstoday, \
				clone_jobs, \
				clone_jobstoday)
				VALUES (
				'${tagNum}', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0', \
				'0');"
		fi


	#Update linecount
	linecount=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT tagnumber FROM jobstats WHERE tagnumber = '${tagNum}';" | wc -l )


	# Update total time
	erasetime=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT erase_time FROM jobstats WHERE tagnumber = '${tagNum}';")
	erasetime=$(z=0; for i in ${erasetime}; do z=$(( z + i )); echo $z; done | tail -n 1)
	imagetime=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT clone_time FROM jobstats WHERE tagnumber = '${tagNum}';")
	imagetime=$(z=0; for i in ${imagetime}; do z=$(( z + i )); echo $z; done | tail -n 1)
	
	totaltime=$(( erasetime + imagetime ))
    mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="UPDATE clientstats SET all_time = '${totaltime}' WHERE tagnumber = '${tagNum}';"


	# Update total time today
	erasetime=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT erase_time FROM jobstats WHERE tagnumber = '${tagNum}' AND date = ${DATE};")
	erasetime=$(z=0; for i in ${erasetime}; do z=$(( z + i )); echo $z; done | tail -n 1)
	imagetime=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT clone_time FROM jobstats WHERE tagnumber = '${tagNum}' AND date = ${DATE};")
	imagetime=$(z=0; for i in ${imagetime}; do z=$(( z + i )); echo $z; done | tail -n 1)
	
	totaltime=$(( erasetime + imagetime ))
    mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="UPDATE clientstats SET all_time = '${totaltime}' WHERE tagnumber = '${tagNum}' AND date = ${DATE};"
	

    # Average image and erase time overall
	sqlstatement=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT all_time FROM clientstats WHERE tagnumber = ${tagNum};")

	totaltime=$(echo "${sqlstatement}" | tail -n 1)

	TimesSeconds=$((totaltime / linecount))

	TimesMinutes=$(echo "$((TimesSeconds / 60)) minutes")

	mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" --execute="\
		UPDATE clientstats SET all_avgtime = '${TimesMinutes}' WHERE tagnumber = ${tagNum};"


    # Average image and erase time today
	sqlstatement=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT all_time FROM clientstats WHERE tagnumber = ${tagNum} AND date = ${DATE};")

	totaltime=$(echo "${sqlstatement}" | tail -n 1)

	TimesSeconds=$((totaltime / linecount))

	TimesMinutes=$(echo "$((TimesSeconds / 60)) minutes")

	mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" --execute="\
		UPDATE clientstats SET all_avgtimetoday = '${TimesMinutes}' WHERE tagnumber = ${tagNum} AND date = ${DATE};"


	# Update total jobs
	erasejobs=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT erase_completed FROM jobstats WHERE tagnumber = '${tagNum}';")
	erasejobs=$(z=0; for i in ${erasejobs}; do z=$(( z + i )); echo $z; done | tail -n 1)
	mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" --execute="\
		UPDATE clientstats SET erase_jobs = '${erasejobs}' WHERE tagnumber = ${tagNum};"
	imagejobs=$(mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="SELECT clone_completed FROM jobstats WHERE tagnumber = '${tagNum}';")
	imagejobs=$(z=0; for i in ${imagejobs}; do z=$(( z + i )); echo $z; done | tail -n 1)
	mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" --execute="\
		UPDATE clientstats SET image_jobs = '${imagejobs}' WHERE tagnumber = ${tagNum};"
	
	totaljobs=$(( erasejobs + imagejobs ))
    mysql --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" \
		-s -N --execute="UPDATE clientstats SET all_jobs = '${totaljobs}' WHERE tagnumber = '${tagNum}';"

done