#!/bin/bash

echo "These are the current disks and their sizes:"
lsblk --nodeps --noheadings -o NAME,SIZE --exclude 1,2,7,11
echo ""
echo "Which USB disk do you want to flash with the ISO?"
        select ISODISK in $(for ISODISK in /sys/block/*;
        do if udevadm info --query=property --path=${ISODISK} | grep -q ^ID_BUS=usb;
        then ISODISK=$(echo ${ISODISK} | grep -o 'sd.*');
        echo ${ISODISK}; fi; done)
        do
        echo ""
        echo "$(lsblk /dev/${ISODISK} -o NAME,SIZE,TYPE,MOUNTPOINT)"
        echo "You chose ${ISODISK}. Is this correct?"
        PS3="Select a drive: "
        read -p "All data on ${ISODISK} will be deleted. Press Enter to confirm...."
        break
        done

if [ -n ${ISODISK} ]; then
echo "Unmounting /dev/${ISODISK}"
umount /dev/${ISODISK} &>/dev/null
echo "Making FAT filesystem on /dev/${ISODISK}"
mkfs.vfat -I /dev/${ISODISK} &>/dev/null
echo "Creating new label on disk /dev/${ISODISK}: UITTSSSHRED"
mlabel -i /dev/${ISODISK} ::UITTSSSHRED &>/dev/null
echo "Writing ISO to /dev/${ISODISK}, this may take a while..."
dd if=/opt/UIT-TSS-SHRED/UIT-TSS-SHRED-amd64.hybrid.iso of=/dev/${ISODISK} bs=4M status=progress
fi
