#!/bin/bash
chmod 600 /root/.ssh_passwd
mysqldump --user="laptops" --password="UHouston!" --database="laptopDB" --host="10.0.0.1" > /mnt/laptopDB.sql
sshpass -f /root/.ssh_passwd ssh-copy-id \
	-o "StrictHostKeyChecking=no" 
scp /mnt/laptopDB.sql laptopsql@p2.plutomail.io:/home/laptopsql

ssh laptopsql@p2.plutomail.io 'mysql -u doadmin --password="AVNS_ncJzgkTeIG6wBd4OSQs" -h private-db-mysql-nyc1-21857-do-user-11961075-0.b.db.ondigitalocean.com -P 25060 -D laptopDB < /mnt/laptopDB.sql'