#!/bin/bash

SSD_REGEX='sd.*'
NVME_REGEX='nvme.*'
SCSI_REGEX='hd.*'
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)
DIM=$(tput dim)
RESET=$(tput sgr0)
cloneElapsed="0"
shredElapsed="0"
ACTION="burn an ISO to"

if [[ ! -f /opt/UIT-TSS-TOOLBOX/UIT-TSS-TOOLBOX-amd64.hybrid.iso ]]; then
        echo ""
        echo "${BOLD}${RED}ISO file does not exist. Please run uit-tss-configure-toolbox.${RESET}"
fi

function diskSelect {
        DISKNAMES=$(for ISODISK in /sys/block/*;
                do if udevadm info --query=property --path=${ISODISK} | grep -q ^ID_BUS=usb;
                then ISODISK=$(echo ${ISODISK} | grep -o 'sd.*');
                echo ${ISODISK}; fi; done)
        CLIENTDISK=""
	diskNums="0"
	local DISKCONF=""
	local a="0"
	local n="0"
	local DISKARR=()

	for i in ${DISKNAMES}; do
		diskNums=$(( diskNums + 1 ))
		DISKARR+=( "$i" )
	done

	if [[ $diskNums == "1" ]]; then
		for i in ${!DISKARR[@]}; do
			CLIENTDISK=${DISKARR[$i]}
		done
		echo "The disk ${BOLD}${CLIENTDISK}${RESET} has been automatically selected because it is the only detected disk."
		read -n 1 -p "Press ${BOLD}${BLUE}[1]${RESET} to confirm" DISKCONF
		if [[ $DISKCONF != "1" ]]; then
			echo "${BOLD}${RED}Reselecting disk.${RESET}"
			diskSelect
		fi
	else
		echo "Which disk do you want to ${ACTION}?"
		while read -r line; do
			a=$(( $a + 1 ))
			echo "${BOLD}${BLUE}[${a}]${RESET} $line"
		done < <(echo "${BOLD}${DISKSIZES}${RESET}")
		echo ""
		read -n 1 -p "Select a disk ${BOLD}${BLUE}[1-$a]${RESET}: " CLIENTDISK
		for i in ${!DISKARR[@]}; do
			n=$(( $n + 1 ))
			if [[ $n == $CLIENTDISK ]]; then
				CLIENTDISK=${DISKARR[$i]}
			fi
		done
		echo ""
		echo ""
	fi

	if [[ $CLIENTDISK =~ ${SSD_REGEX} ]]; then
		:
	else
	    echo ""
	    echo "${BOLD}${RED}Invalid selection.${RESET}"
		sleep 0.5
	    diskSelect
	fi


}

function execute {
        if [[ ! -z ${ISODISK} && $DISKCHECK =~ sd.* ]]; then
                echo "Unmounting ${ISODISK}"
                umount /dev/${ISODISK} &>/dev/null
                echo "Making FAT filesystem on ${ISODISK}"
                mkfs.vfat -I -F 32 /dev/${ISODISK} &>/dev/null
                echo "Writing ISO to ${ISODISK}, this may take a while..."
                /usr/bin/pv < /opt/UIT-TSS-TOOLBOX/UIT-TSS-TOOLBOX-amd64.hybrid.iso > /dev/${ISODISK}
                echo "Creating new label on disk ${ISODISK}: UITTOOLBX"
                fatlabel /dev/${ISODISK} "UITTOOLBX" &>/dev/null
                fatlabel /dev/${ISODISK}1 "UITTOOLBX" &>/dev/null
        else
                echo ""
                echo "Invalid block device or no USB drive found. Exiting...."
                exit 1
        fi
}

diskSelect
execute