#!/bin/bash

mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'UHouston\!';"

mysql --user="root" --password="UHouston!" --execute="CREATE USER 'laptops'@'%' IDENTIFIED BY 'UHouston\!';"
mysql --user="root" --password="UHouston!" --execute="ALTER USER 'laptops'@'%' IDENTIFIED BY 'UHouston\!';"
mysql --user="root" --password="UHouston!" --execute="GRANT ALL ON *.* TO 'laptops'@'%' WITH GRANT OPTION;"

mysql --user="laptops" --password="UHouston!" --execute="CREATE DATABASE laptops;"
mysql --user="laptops" --password="UHouston!" --database="laptops" --execute="CREATE TABLE laptopstats(\
	id int NOT NULL AUTO_INCREMENT, \
	tagnumber VARCHAR(150) NOT NULL, \
	uuid VARCHAR(150) NOT NULL, \
	etheraddress VARCHAR(150) NOT NULL, \
	date VARCHAR(150) NOT NULL, \
	rebooted VARCHAR(150) NOT NULL, \
	action VARCHAR(150) NOT NULL, \
	mode VARCHAR(150) NOT NULL, \
	disk VARCHAR(150) NOT NULL, \
	disksizegb VARCHAR(150) NOT NULL, \
	diskpcnt VARCHAR(150) NOT NULL, \
	server VARCHAR(150) NOT NULL, \
	sambauser VARCHAR(150) NOT NULL, \
	cloneimg VARCHAR(150) NOT NULL, \
	imgupdate VARCHAR(150) NOT NULL, \
	erasepattern VARCHAR(150) NOT NULL, \
	totaltime VARCHAR(150) NOT NULL, \
	erasetime VARCHAR(150) NOT NULL, \
	imagetime VARCHAR(150) NOT NULL, \
	avgtimeall VARCHAR(150) NOT NULL, \
	avgtimetoday VARCHAR(150) NOT NULL, \
	avgtimeweek VARCHAR(150) NOT NULL, \
	avgtimemonth VARCHAR(150) NOT NULL, \
	avgtimeeraseall VARCHAR(150) NOT NULL, \
	avgtimeerasetoday VARCHAR(150) NOT NULL, \
	avgtimeeraseweek VARCHAR(150) NOT NULL, \
	avgtimeerasemonth VARCHAR(150) NOT NULL, \
	avgtimecloneall VARCHAR(150) NOT NULL, \
	avgtimecloneday VARCHAR(150) NOT NULL, \
	avgtimecloneweek VARCHAR(150) NOT NULL, \
	avgtimeclonemonth VARCHAR(150) NOT NULL, \
	timestotal VARCHAR(150) NOT NULL, \
	timestoday VARCHAR(150) NOT NULL, \
	timestweek VARCHAR(150) NOT NULL, \
	timesmonth VARCHAR(150) NOT NULL, \
	timeserasedtotal VARCHAR(150) NOT NULL, \
	timeserasedday VARCHAR(150) NOT NULL, \
	timeserasedweek VARCHAR(150) NOT NULL, \
	timeserasedmonth VARCHAR(150) NOT NULL, \
	timesclonedtotal VARCHAR(150) NOT NULL, \
	timesclonedday VARCHAR(150) NOT NULL, \
	timesclonedweek VARCHAR(150) NOT NULL, \
	timesclonedmonth VARCHAR(150) NOT NULL, \
	PRIMARY KEY (id) );"

mysql --user="laptops" --password="UHouston!" --database="laptops" --execute="CREATE TABLE serverstats(\
	title VARCHAR(150) NOT NULL, \
	avgtimeall VARCHAR(150) NOT NULL, \
	avgtimetoday VARCHAR(150) NOT NULL, \
	avgtimeweek VARCHAR(150) NOT NULL, \
	avgtimemonth VARCHAR(150) NOT NULL, \
	avgtimeeraseall VARCHAR(150) NOT NULL, \
	avgtimeerasetoday VARCHAR(150) NOT NULL, \
	avgtimeeraseweek VARCHAR(150) NOT NULL, \
	avgtimeerasemonth VARCHAR(150) NOT NULL, \
	avgtimecloneall VARCHAR(150) NOT NULL, \
	avgtimecloneday VARCHAR(150) NOT NULL, \
	avgtimecloneweek VARCHAR(150) NOT NULL, \
	avgtimeclonemonth VARCHAR(150) NOT NULL, \
	timestotal VARCHAR(150) NOT NULL, \
	timestoday VARCHAR(150) NOT NULL, \
	timestweek VARCHAR(150) NOT NULL, \
	timesmonth VARCHAR(150) NOT NULL, \
	timeserasedtotal VARCHAR(150) NOT NULL, \
	timeserasedday VARCHAR(150) NOT NULL, \
	timeserasedweek VARCHAR(150) NOT NULL, \
	timeserasedmonth VARCHAR(150) NOT NULL, \
	timesclonedtotal VARCHAR(150) NOT NULL, \
	timesclonedday VARCHAR(150) NOT NULL, \
	timesclonedweek VARCHAR(150) NOT NULL, \
	timesclonedmonth VARCHAR(150) NOT NULL, \
	PRIMARY KEY (title) );"
