#!/bin/bash

INTERFACES=$(cat /proc/net/dev | grep -oP '.*:\ ' | sed 's/://g' | sed 's/[[:space:]]//g')
LANIP='10.0.0.1'
LANSUBNET='24'

function initialize {
    clear
    echo ""
    echo "Initializing UIT-TSS-CONFIGURE-SERVER by Cameron Raschke"
    echo ""

    read -p "Press Enter to continue...."

    echo ""
    echo "Setting all interfaces down"
    for i in $INTERFACES; do
    ip link set down $i
    done

    echo ""
    echo "Flushing all IP addresses"
    for i in $INTERFACES; do
    ip addr flush dev $i
    done

    echo ""
    echo "Removing all interfaces from bonds and bridges"
    for i in $INTERFACES; do
    ip link set dev $i nomaster
    done

    echo ""
    echo "Flushing all routes"
    ip route flush table main
}

function intro {
	clear
	echo ""
	echo "Welcome to UIT-TSS-CONFIGURE-SERVER by Cameron Raschke."
	echo ""
	echo "Press CTRL + C at any time to exit"
	echo ""
	echo ""
	echo ""
	echo "| |    | |  | |     | |"
	echo "| |    | |  | |_____| |"
	echo "| |    | |  | |_____| |"
	echo "| |____| |  | |     | |"
	echo "\________/  | |     | |"
	echo ""
	echo "------------------------------"
	echo ""
    echo "Checklist:
	-Physical connections
	   * Make sure the server has power and ethernet attached.
       * Make sure the server has two interfaces connected - one for WAN, one for LAN.
	-Storage
	   * Make sure the server has over 100GB of free storage on the root drive.
    -Data
       * Backup the images to the server once it has been configured."
	read -p "Press Enter to continue...."
	clear
}

function ifselect {
    echo "Which interface is your WAN port?"
    echo $INTERFACES

    echo "Which interface is your LAN port?"
    echo $INTERFACES
}

function ifconf {
    echo "Configuring networking"
}

funciton firewall {
cat <<'EOF' > /root/firewall.sh
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A FORWARD -i lo -j ACCEPT
iptables -t filter -A FORWARD -o lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT

iptables -t filter -A INPUT -i $LANIF -j ACCEPT
iptables -t filter -A OUTPUT -o $LANIF -j ACCEPT

iptables -t filter -A INPUT -i $WANIF -p udp --sport 53 -j ACCEPT
iptables -t filter -A INPUT -i $WANIF -p tcp --sport 80 -j ACCEPT
iptables -t filter -A INPUT -i $WANIF -p tcp --sport 443 -j ACCEPT
iptables -t filter -A INPUT -i $WANIF -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -t filter -A INPUT -i $WANIF -j DROP

iptables -t filter -A OUTPUT -o $WANIF -p udp --dport 53 -j ACCEPT
iptables -t filter -A OUTPUT -o $WANIF -p tcp --dport 80 -j ACCEPT
iptables -t filter -A OUTPUT -o $WANIF -p tcp --dport 443 -j ACCEPT
iptables -t filter -A OUTPUT -o $WANIF -j DROP

EOF

    chown root:root /root/firewall.sh
    chmod 700 /root/firewall.sh
    /root/firewall.sh
}

function unixaccounts {
    echo -e 'UHouston!\nUHouston!\n' | passwd root
    echo -e 'UHouston!\nUHouston!\n' | passwd cameron

}

function hostname {
    hostnamectl set-hostname UIT-TSS-LAPTOP-SERVER
}

function crontab {
    echo -n "@reboot /root/firewall.sh" > /etc/cron.d/00-firewall
}

function pkginstall {
    echo "Updating and upgrading all packages...."
    apt update -y
    apt upgrade -y
    echo "Installing necessary packages...."
    apt install dnsmasq samba iftop iotop iptables chpasswd -y
    echo "Enabling new packages...."
    systemctl enable nmbd smbd dnsmasq
    systemctl stop dnsmasq
}

function pkgconf {
    echo "Configuring Samba...."
cat <<'EOF' > /etc/samba/smb.conf
[global]
workgroup = WORKGROUP
server string = Samba Server
interfaces = ${LANIP}/${LANSUBNET} ${LANIF}
socket address = ${LANIP}
bind interfaces only = yes
log file = /var/log/samba/log.%m
max log size = 50
logging = file
panic action = /usr/share/samba/panic-action %d
server role = standalone server
obey pam restrictions = yes
unix password sync = yes
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
map to guest = bad user
usershare allow guests = no

[dell]
path = /home/dell
read only = no
browsable = yes

[hp]
path = /home/hp
read only = no
browsable = yes

[desktops]
path = /home/desktops
read only = no
browsable = yes
EOF

    echo -e 'UHouston!\nUHouston!\n' | smbpasswd -a cameron

    mkdir /home/dell
    mkdir /home/desktops
    mkdir /home/hp

    chown cameron:cameron /home/dell -R
    chown cameron:cameron /home/desktops -R
    chown cameron:cameron /home/hp -R

    echo "Configuring SSH...."
    sed -i 's/#ListenAddress 0.0.0.0/ListenAddress 10.0.0.1/g' /etc/ssh/sshd_config
    sed -i 's/#AddressFamily any/AddressFamily inet/g' /etc/ssh/sshd_config

    echo "Configuring dnsmasq...."
cat <<'EOF' > /etc/dnsmasq.conf
port=53
no-resolv
listen-address=${LANIP}
bogus-priv
strict-order
interface=${LANIF}
bind-interfaces

dhcp-option=1,255.255.255.0
dhcp-option=6,10.0.0.1
dhcp-option=15,.uit
dhcp-range=10.0.0.5,10.0.0.254,255.255.255.0,2m
dhcp-sequential-ip
EOF   

apt autoremove -y
}

function pkgrestart {
    echo "Applying all package changes...."
    systemctl restart nmbd smbd ssh dnsmasq
}

function writescripts {
echo "Creating SMB Status script"
echo "watch -n 0.5 'smbstatus --verbose'" > /root/smbstatus.sh
chown root:root /root/smbstatus.sh
chmod 700 /root/smbstatus.sh
}

function kubernetes {
    apt install containerd -y
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] \
        https://apt.kubernetes.io/ kubernetes-xenial main" \
        | sudo tee /etc/apt/sources.list.d/kubernetes.list
    apt update -y
    apt install -y kubelet kubeadm kubectl
    apt-mark hold kubelet kubeadm kubectl

    kubectl drain ${K8SNODE} --delete-emptydir-data --force --ignore-daemonsets

    kubeadm reset

    iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

    ipvsadm -C

    kubectl delete node ${K8SNODE}

    kubeadm init \
        --control-plane-endpoint ${LANIP} \
        --pod-network-cidr 192.168.1.1/24 \
        --apiserver-advertise-address=${LANIP}

    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

    export KUBECONFIG=/etc/kubernetes/admin.conf

    kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

    kubectl taint nodes --all node-role.kubernetes.io/control-plane-


}

function terminate {
    read -p "Press Enter to reboot...."
    reboot
}

