#!/bin/bash

if [ ! -f /opt/live-build.deb ]; then
/usr/bin/apt purge live-build -y
/usr/bin/wget http://ftp.us.debian.org/debian/pool/main/l/live-build/live-build_20220505_all.deb \
	--output-document=/opt/debian-live.deb
/usr/bin/apt install /opt/debian-live.deb -y
fi

/usr/bin/apt install dosfstools -y

rm -r /opt/UIT-TSS-SHRED/
mkdir /opt/UIT-TSS-SHRED/

( cd /opt/UIT-TSS-SHRED/ && \

	lb clean && \

	/usr/bin/lb config \
		--apt apt \
		--apt-recommends true \
		--apt-secure true \
		--apt-source-archives true \
		--architecture amd64 \
		--archive-areas 'main' \
		--binary-filesystem fat32 \
		--binary-images iso-hybrid \
		--bootappend-live "boot=live live-media=removable toram username=root hostname=UIT-TSS-SHRED \
			timezone=America/Chicago" \
		--bootloaders "grub-efi syslinux" \
		--chroot-filesystem squashfs \
		--compression gzip \
		--clean \
		--debian-installer live \
		--debian-installer-distribution bullseye \
		--distribution bullseye \
		--debootstrap-options "--variant=minbase --arch=amd64" \
		--hdd-label UIT-TSS-SHRED \
		--image-name UIT-TSS-SHRED \
		--initramfs live-boot \
		--initsystem systemd \
		--iso-application UIT-TSS-SHRED \
		--iso-preparer "Cameron Raschke caraschke@uh.edu" \
		--iso-publisher "Cameron Raschke caraschke@uh.edu" \
		--iso-volume UIT-TSS-SHRED \
		--mode debian \
		--system live \
		--uefi-secure-boot enable \
		--updates true)

mkdir -p /opt/UIT-TSS-SHRED/config/bootloaders
cp -r /usr/share/live/build/bootloaders/isolinux /opt/UIT-TSS-SHRED/config/bootloaders
cp -r /usr/share/live/build/bootloaders/grub-pc /opt/UIT-TSS-SHRED/config/bootloaders

cat <<'EOF' > /opt/UIT-TSS-SHRED/config/bootloaders/isolinux/isolinux.cfg
UI vesamenu.c32

MENU TITLE Boot Menu
DEFAULT linux
        TIMEOUT 10
        MENU RESOLUTION 640 480
        SAY Now booting into UIT-TSS-SHRED by Cameron Raschke
label linux
        menu label UIT-TSS-SHRED by Cameron Raschke
        menu default
        linux /live/vmlinuz
        initrd /live/initrd.img
        append @APPEND_LIVE@
EOF

rm -r /opt/UIT-TSS-SHRED/config/bootloaders/grub-pc/*
cat <<'EOF' > /opt/UIT-TSS-SHRED/config/bootloaders/grub-pc/grub.cfg
insmod part_gpt
insmod part_msdos
insmod fat
insmod iso9660
insmod gfxterm

set gfxmode=800x600
terminal_output gfxterm

set default="0"
set timeout=0
set timeout_style=hidden

menuentry "UIT-TSS-SHRED by Cameron Raschke" {
        linux @KERNEL_LIVE@ @APPEND_LIVE@
        initrd @INITRD_LIVE@
}
EOF

cat <<'EOF' > /opt/UIT-TSS-SHRED/config/package-lists/live.list.chroot
live-boot
live-config
live-config-systemd
systemd-sysv
openssl
less
nano
vim
cifs-utils
passwd
locales
firmware-linux-free
parted
gdisk
libasound2
libasound2-plugins
alsa-utils
sox
libsox-fmt-all
kbd
iptables
hdparm
util-linux
nvme-cli
procps
coreutils
pv
hexdump
EOF

mkdir -p /opt/UIT-TSS-SHRED/config/includes.chroot/root/
cat <<'EOF' > /opt/UIT-TSS-SHRED/config/hooks/live/0100-uit-tss-toolbox-setup.hook.chroot

/usr/sbin/sysctl -w "net.ipv6.conf.all.disable_ipv6=1" &>/dev/null
/usr/sbin/sysctl -w "net.ipv6.conf.default.disable_ipv6=1" &>/dev/null
/usr/sbin/sysctl -w "net.ipv4.conf.default.rp_filter=2" &>/dev/null
/usr/sbin/sysctl -w "net.ipv4.conf.all.rp_filter=2" &>/dev/null
/usr/sbin/sysctl -w "net.ipv4.ip_forward=0" &>/dev/null
/usr/sbin/sysctl -w "net.ipv6.conf.all.forwarding=1" &>/dev/null
/usr/sbin/sysctl -w  "net.ipv6.conf.default.forwarding=1" &>/dev/null
/usr/sbin/sysctl -p &>/dev/null

/usr/sbin/sysctl -w "kernel.printk=2 4 1 2" &>/dev/null
/usr/sbin/sysctl -w "kernel.kptr_restrict=1" &>/dev/null
/usr/sbin/sysctl -w "vm.mmap_min_addr=65536" &>/dev/null
/usr/sbin/sysctl -p &>/dev/null

echo "UIT-TSS-SHRED" > /etc/hostname
echo -e "\nWelcome to UIT-TSS-SHRED by Cameron Raschke.\n" > /etc/motd
echo -e "\nWelcome to UIT-TSS-SHRED by Cameron Raschke.\n" > /etc/issue.net
echo -e "Banner /etc/issue.net" >> /etc/ssh/sshd_config

/usr/bin/apt purge iproute2 -y &>/dev/null
EOF

chmod 777 /opt/UIT-TSS-SHRED/config/hooks/live/0100-uit-tss-toolbox-setup.hook.chroot

mkdir -p /opt/UIT-TSS-SHRED/config/includes.chroot/root/
/usr/bin/wget https://soundboardguy.com/wp-content/uploads/2022/01/Oven-Timer-Ding.mp3 \
	--output-document=/opt/UIT-TSS-SHRED/config/includes.chroot/root/oven.mp3

mkdir -p /opt/UIT-TSS-SHRED/config/includes.chroot/root
touch /opt/UIT-TSS-SHRED/config/includes.chroot/root/.bash_profile
cat <<'EOF' > /opt/UIT-TSS-SHRED/config/includes.chroot/root/.bash_profile
#!/bin/bash

clear

echo ""
echo "Configuring Kernel..."
/usr/sbin/iptables -P INPUT DROP &>/dev/null
/usr/sbin/iptables -P FORWARD DROP &>/dev/null
/usr/sbin/iptables -P OUTPUT DROP &>/dev/null
/usr/sbin/sysctl -w "net.ipv6.conf.all.disable_ipv6=1" &>/dev/null
/usr/sbin/sysctl -w "net.ipv6.conf.default.disable_ipv6=1" &>/dev/null
/usr/sbin/sysctl -w "net.ipv4.conf.default.rp_filter=2" &>/dev/null
/usr/sbin/sysctl -w "net.ipv4.conf.all.rp_filter=2" &>/dev/null
/usr/sbin/sysctl -w "net.ipv4.ip_forward=0" &>/dev/null
/usr/sbin/sysctl -w "net.ipv6.conf.all.forwarding=1" &>/dev/null
/usr/sbin/sysctl -w  "net.ipv6.conf.default.forwarding=1" &>/dev/null
/usr/sbin/sysctl -w "kernel.printk=2 4 1 2" &>/dev/null
/usr/sbin/sysctl -w "kernel.kptr_restrict=1" &>/dev/null
/usr/sbin/sysctl -w "vm.mmap_min_addr=65536" &>/dev/null
/usr/sbin/sysctl -p &>/dev/null
echo "Done."
echo ""
 
echo "Configuring audio..."
/usr/bin/amixer sset Master 100% &>/dev/null
/usr/bin/amixer set Master unmute &>/dev/null
/usr/bin/amixer sset Speakers 100% &>/dev/null
/usr/sbin/amixer set Speakers unmute &>/dev/null
echo "Done."
echo ""

echo "Configuring font..."
/usr/bin/setfont /usr/share/consolefonts/Lat7-TerminusBold16.psf.gz
echo "Done."
echo ""

sleep 1

clear

CLIENTDISK=''
SSD_REGEX='sd.*'
NVME_REGEX='nvme.*'
SCSI_REGEX='hd.*'



function intro {
	clear
	echo ""
	echo -e "\nWelcome to UIT-TSS-SHRED by Cameron Raschke.\n"
	echo "Press CTRL + C at any time to exit"
	echo "If you have exited and want to restart UIT-TSS-SHRED, press CTRL + D"
	echo ""
	echo ""
echo '
| |    | |  | |     | |
| |    | |  | |_____| |
| |    | |  | |_____| |
| |____| |  | |     | |
\________/  | |     | |
'
	sleep 1
	echo ""
	echo "------------------------------"
	echo ""
echo 'Checklist:
	-Physical connections
	   * Make sure that power is plugged in to the client.
	   * Do not use UIT-TSS-SHRED on USB drives or drives connected over USB.
	-General best practices
	   * Sanitize laptops with cleaner before imaging them.
	   * Reset BIOS to default/factory settings before imaging.
	-Dells
	   * Make sure SATA mode is in AHCI mode and not RAID mode.
	      * This is usually under "System Configuration" or "Storage" in BIOS.
	      * Every Dell is in RAID mode by default. 
	      * If you reset BIOS, make sure you change SATA mode after the reset.
	      
	*** WARNING *** After pressing Enter, the system will enter hibernate mode.
	This is normal. Please wake up the system after it hibernates. *** WARNING ***
'
	read -p "Please remove the thumb drive and press Enter...."
	echo -n mem > /sys/power/state
	clear
}



function modeselect {
	echo ""
	echo "Choose a mode:"

	echo ""
	echo "1 Default 
	-Mixture of modes
	-Most secure"

	echo ""
	echo "2 Zero mode 
	-One pass of zeroes
	-Fastest for SATA"

	echo ""
	echo "3 Secure Erase
	-Firmware zeroing
	-SATA/NVME Only
	-Fastest for NVME
	-One pass, real-time verification"

	echo ""
	echo "4 DOD 5220.22-M/NCSC-TG-025/AFSSI-5020/HMG IS5
	-Writes a pass of zeroes, then ones, then a random bit
	-3 passes, 3 verifications"

	echo ""
	echo "5 RCMP TSSIT OPS-II/VSITR
	-Alternates passes between 0's and 1's 6 times
	-Writes random bit, verifies random bit"

	echo ""
	echo "6 Gutmann (Very long)
	-Four random character passes (excluding zero)
	-27 predefined pattern passes
	-Four random character passes (exluding zero)"

	echo ""
	echo "7 Schneier
	-A pass of 1's then a pass of 0's
	-Five passes of a random stream of characters"

	read -n1 -p "Choose [1-7] " MODE
	echo ""
	case $MODE in
	1)
	MODE='default'
	;;
	2)
	MODE='fast'
	;;
	3)
	MODE='secureerase'
	;;
	4)
	MODE='dod'
	;;
	5)
	MODE='rcmp'
	;;
	6)
	MODE='gutmann'
	;;
	7)
	MODE='schneier'
	;;
	*)
	modeselect
	;;
	esac
}



function diskselect {
	DISKNAMES=$(lsblk --nodeps --noheadings -o NAME --exclude 1,2,7,11)
	echo ""
    echo "These are the current disks and their sizes:"
    echo "$(lsblk --nodeps --noheadings -o NAME,SIZE --exclude 1,2,7,11)"
    echo ""
    echo "Which disk do you want to ${ACTION}?"
    PS3="Select a drive: "
    select CLIENTDISK in ${DISKNAMES}
    do
        if [[ $CLIENTDISK =~ sd.* || $CLIENTDISK =~ nvme.* ]]; then
        echo "$(lsblk /dev/${CLIENTDISK} -o NAME,SIZE,TYPE,MOUNTPOINT)"
		echo "*** WARNING *** There is no going back once you confirm. \
Press CTRL + C to exit. *** WARNING ***"
        echo "You chose ${CLIENTDISK}. Is this correct?"
        read -p "Press Enter to confirm...."
        echo ""
        break
        else
		echo "Invalid block device selected."
		echo ""
		diskselect
        exit 1
        fi
    done
}



function default {
	clear
	echo ""
	echo "UIT-TSS-SHRED running in default mode."

	echo ""
	echo "[1/8] Destroying all GPT and MBR data...."
	sleep 1
	/usr/sbin/sgdisk --zap-all /dev/${CLIENTDISK} &>/dev/null

	echo ""
	echo "[2/8] First pass - using pattern 01010101 on ${CLIENTDISK}...."
	sleep 1
	/usr/bin/yes "01" | (pv > /dev/${CLIENTDISK})

	echo ""
	echo "[3/8] Second pass - using pattern 10101010 on ${CLIENTDISK}...."
	sleep 1
	/usr/bin/yes "10" | (pv > /dev/${CLIENTDISK})
	
	if [[ $CLIENTDISK =~ $SSD_REGEX ]]; then 
	echo ""
	echo "[4/8] Using Secure Erase on ${CLIENTDISK}. Please keep the device powered on."
	sleep 1
	/usr/sbin/hdparm --user-master u --security-set-pass UHouston /dev/${CLIENTDISK} &>/dev/null
	/usr/sbin/hdparm --user-master u --security-erase UHouston /dev/${CLIENTDISK} &>/dev/null
	fi
	
	if [[ $CLIENTDISK =~ $NVME_REGEX ]]; then
	echo ""
	echo "[4/8] Using Secure Erase on ${CLIENTDISK}. Please keep the device powered on."
	sleep 1
	/usr/sbin/nvme format /dev/${CLIENTDISK} --ses=1 --namespace-id=1 &>/dev/null
	/usr/sbin/nvme format /dev/${CLIENTDISK} --ses=2 --namespace-id=1 &>/dev/null
	fi

	if [[ $CLIENTDISK =~ $SCSI_REGEX ]]; then
	echo "[4/8] No SATA or NVME drive was selected, cannot use Secure Erase. Continuing...."
	else
	echo "[4/8] No SATA or NVME drive was selected, cannot use Secure Erase. Continuing...."
	fi

	echo ""
	echo "[5/8] Writing a stream of random characters to ${CLIENTDISK}...."
	sleep 1
	/usr/bin/pv < /dev/urandom > /dev/${CLIENTDISK}

	echo ""
	echo "[6/8] Using the Write Zero method on ${CLIENTDISK}...."
	sleep 1
	/usr/bin/pv < /dev/zero > /dev/${CLIENTDISK}

	echo ""
	echo "[7/8] Discarding and deleting all sectors on ${CLIENTDISK}...."
	sleep 1
	/usr/sbin/blkdiscard /dev/${CLIENTDISK} &>/dev/null

	echo ""
	echo "[8/8] Verifying - searching all sectors on ${CLIENTDISK} for non-zero bits...."
	HEXVERIFY=$(/usr/bin/pv /dev/${CLIENTDISK} | grep -oP -m 1 '[^0]' &> /dev/null | head -1)

	if [[ ! -z $HEXVERIFY ]]; then
        echo ""
        echo "Non-zero bits found on device ${CLIENTDISK}. Test has failed."
		exit 1
	else
        echo ""
		echo "The drive ${CLIENTDISK} is completely and securely wiped."
		echo "Test passed successfully!"
	fi
}



function fast {
	clear
	echo ""
	echo "UIT-TSS-SHRED running in fast mode."

	echo ""
	echo "[1/1] Using the Write Zero method on ${CLIENTDISK}...."
	sleep 1
	/usr/bin/pv < /dev/zero > /dev/${CLIENTDISK}

	echo ""
	echo ""
	echo "Done."
}



function secureerase {
	clear
	echo ""
	echo "UIT-TSS-SHRED running in Secure Erase mode."
	echo "Notice: This mode will only work on newer SATA/NVME drives."

	if [[ $CLIENTDISK =~ $SSD_REGEX ]]; then 
	echo ""
	echo "[1/1] Using Secure Erase on ${CLIENTDISK}. Please keep the device powered on."
	sleep 1
	/usr/sbin/hdparm --user-master u --security-set-pass UHouston /dev/${CLIENTDISK} &>/dev/null
	/usr/sbin/hdparm --user-master u --security-erase UHouston /dev/${CLIENTDISK} &>/dev/null
	fi
	
	if [[ $CLIENTDISK =~ $NVME_REGEX ]]; then
	echo ""
	echo "[1/1] Using Secure Erase on ${CLIENTDISK}. Please keep the device powered on."
	sleep 1
	/usr/sbin/nvme format /dev/${CLIENTDISK} --ses=1 --namespace-id=1 &>/dev/null
	/usr/sbin/nvme format /dev/${CLIENTDISK} --ses=2 --namespace-id=1 &>/dev/null
	fi

	if [[ $CLIENTDISK =~ $SCSI_REGEX ]]; then
	echo "[1/1] Error: No SATA or NVME drive was selected, cannot use Secure Erase. Please use another mode. Exiting...."
	else
	echo "[1/1] Error: No SATA or NVME drive was selected, cannot use Secure Erase. Please use another mode. Exiting...."
	fi

	echo ""
	echo ""
	echo "Done."
}



function dod {
	clear
	echo ""
	echo "UIT-TSS-SHRED running in DOD 5220.22-M mode."

	RANDOMBIT=$(cat /dev/urandom | xxd -plain | head -1 | cut -c 1)

	echo ""
	echo "Writing a pass of all 0's"
	pv < /dev/zero > /dev/${CLIENTDISK}
	echo ""
	echo "Verifying disk - checking for 0's...."
	ZEROVERIFY=$(/usr/bin/pv /dev/${CLIENTDISK} | grep -oP -m 1 '[^0]' &> /dev/null | head -1)
	if [[ ! -z $ZEROVERIFY ]]; then
        echo ""
        echo "Bits found on device ${CLIENTDISK} that weren't 0's. Test has failed."
		exit 1
	fi

	echo ""
	echo "Writing a pass of all 1's"
	/usr/bin/yes "1" | (pv > /dev/${CLIENTDISK})
	echo ""
	echo "Verifying disk - checking for 1's...."
	ONEVERIFY=$(/usr/bin/pv /dev/${CLIENTDISK} | grep -oP -m 1 '[^1]' &> /dev/null | head -1)
	if [[ ! -z $ONEVERIFY ]]; then
        echo ""
        echo "Bits found on device ${CLIENTDISK} that weren't 1's. Test has failed."
		exit 1
	fi

	echo ""
	echo "Writing a pass of a random bit (${RANDOMBIT})"
	/usr/bin/yes "${RANDOMBIT}" | (pv > /dev/${CLIENTDISK})
	echo ""
	echo "Verifying disk - checking for the random bit (${RANDOMBIT})'s...."
	RBITVERIFY=$(/usr/bin/pv /dev/${CLIENTDISK} | grep -oP -m 1 "[^${RANDOMBIT}]" &> /dev/null | head -1)
	if [[ ! -z $RBITVERIFY ]]; then
        echo ""
        echo "Bits found on device ${CLIENTDISK} that weren't ${RANDOMBIT}'s. Test has failed."
		exit 1
	fi

	if [[ ! -z $ZEROVERIFY && ! -z $ONEVERIFY && ! -z $RBITVERIFY ]]; then
        echo ""
        echo "Bad bits found on device ${CLIENTDISK}. Test has failed."
		exit 1
	else
        echo ""
		echo "The drive ${CLIENTDISK} is erased and verified."
	fi
}



function rcmp {

}



function gutmann {
	clear
	echo ""
	echo "UIT-TSS-SHRED running in Gutmann mode."

	#01010101.....
	#cat /dev/zero | tr '\000' '\001' | xxd -p | (pv /dev/${CLIENTDISK})
	#10101010.....
	#cat /dev/zero | tr '\000' '\020' | xxd -p | (pv /dev/${CLIENTDISK})
}



function execute {
	start_time=$SECONDS
	
	if [[ $MODE == 'default' ]]; then
	default
	fi

	if [[ $MODE == 'fast' ]]; then
	fast
	fi

	if [[ $MODE == 'secureerase' ]]; then
	secureerase
	fi

	if [[ $MODE == 'dod' ]]; then
	dod
	fi

	if [[ $MODE == 'rcmp' ]]; then
	rcmp
	fi
	
	if [[ $MODE == 'gutmann' ]]; then
	gutmann
	fi
	
	if [[ $MODE == 'schneier' ]]; then
	schneier
	fi

}



function terminate {
	elapsed=$(( SECONDS - start_time ))
	TIME=$(date -d@$elapsed -u +'%H hours and %M minutes')
	echo ""
	echo ""
	echo "--------------------"
	echo ""
	/usr/bin/play /root/oven.mp3 &> /dev/null
	echo "Process has finished in ${TIME}."
	read -p "Press Enter to shutdown..."
	poweroff
}



intro
diskselect
modeselect
execute
terminate
EOF

(cd /opt/UIT-TSS-SHRED && \
	lb build)
