#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

    $sql = "SELECT 'Date','Laptop Count','Last Image Update','Total Jobs','Erase Jobs','Clone Jobs','Clone Avg. Time','NVME Avg. Erase Time','SSD Avg. Erase Time'
    UNION ALL
    SELECT 'date','laptop_count','last_image_update','all_jobs','erase_jobs','clone_jobs','clone_avgtime','nvme_erase_avgtime','ssd_erase_avgtime'
    FROM serverstats ORDER BY date DESC INTO OUTFILE '/tmp/report.csv'
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'";

    $conn->query($sql);

$conn->close(); 
?>