#!/bin/bash

function selectdisk {
        DISKNAMES=$(lsblk --nodeps --noheadings -o NAME --exclude 1,2,7,11)
        echo "These are the current disks and their sizes:"
        echo "${DISKNAMES}"
        echo ""
        echo "Which USB disk do you want to flash with the ISO?"
        PS3="Select a drive: "
        select ISODISK in $(for ISODISK in /sys/block/*;
                do if udevadm info --query=property --path=${ISODISK} | grep -q ^ID_BUS=usb;
                then ISODISK=$(echo ${ISODISK} | grep -o 'sd.*');
                echo ${ISODISK}; fi; done)
                do
                if [[ $ISODISK =~ sd.* || $ISODISK =~ nvme.* ]]; then
                echo ""
                echo "$(lsblk /dev/${ISODISK} -o NAME,SIZE,TYPE,MOUNTPOINT)"
                echo "You chose ${ISODISK}. Is this correct?"
                read -p "All data on ${ISODISK} will be deleted. Press Enter to confirm...."
                break
                else
                echo ""
                echo "Invalid block device selected."
                selectdisk
                fi
                if [[ ! -f /opt/UIT-TSS-SHRED/UIT-TSS-SHRED-amd64.hybrid.iso ]]; then
                echo ""
                echo "ISO file does not exist."
                fi
        done
}

function execute {
        if [ ! -z ${ISODISK} ]; then
        echo "Unmounting ${ISODISK}"
        umount /dev/${ISODISK} &>/dev/null
        echo "Making FAT filesystem on ${ISODISK}"
        mkfs.vfat -I /dev/${ISODISK} &>/dev/null
        echo "Creating new label on disk ${ISODISK}: UITTSSSHRED"
        fatlabel /dev/${ISODISK} UITTSSSHRED &>/dev/null
        echo "Writing ISO to ${ISODISK}, this may take a while..."
        dd if=/opt/UIT-TSS-SHRED/UIT-TSS-SHRED-amd64.hybrid.iso of=/dev/${ISODISK} bs=4M status=progress
        fi
}

selectdisk
execute
