#!/bin/bash

function selectdisk {
        DISKNAMES=$(lsblk --nodeps --noheadings -o NAME,SIZE --exclude 1,2,7,11)
        DISKCHECK=$(for ISODISK in /sys/block/*;
                do if udevadm info --query=property --path=${ISODISK} | grep -q ^ID_BUS=usb;
                then ISODISK=$(echo ${ISODISK} | grep -o 'sd.*');
                echo ${ISODISK}; fi; done)

        echo ""
        echo "These are the current disks and their sizes:"
        echo "${DISKNAMES}"

        if [[ ! -f /opt/UIT-TSS-SHRED/UIT-TSS-SHRED-amd64.hybrid.iso ]]; then
        echo ""
        echo "ISO file does not exist. Please run uit-tss-configure-shred."
        fi

        if [[ $DISKCHECK =~ sd.* ]]; then
        echo ""
        echo "Which USB drive do you want to flash with the shred ISO?"
                PS3="Select a drive: "
                select ISODISK in $DISKCHECK
                do        
                echo ""
                echo "$(lsblk /dev/${ISODISK} -o NAME,SIZE,MOUNTPOINT)"
                echo ""
                read -p "All data on ${ISODISK} will be deleted. Press Enter to confirm...."
                break
                done
        else
        echo ""
        echo "Invalid block device or no USB drive found. Exiting...."
        exit 1
        fi
}

function execute {
        if [[ ! -z ${ISODISK} && $DISKCHECK =~ sd.* ]]; then
        echo "Unmounting ${ISODISK}"
        umount /dev/${ISODISK} &>/dev/null
        echo "Making FAT filesystem on ${ISODISK}"
        mkfs.vfat -I -F 32 /dev/${ISODISK} &>/dev/null
        echo "Writing ISO to ${ISODISK}, this may take a while..."
        /usr/bin/pv < /opt/UIT-TSS-SHRED/UIT-TSS-SHRED-amd64.hybrid.iso > /dev/${ISODISK}
        echo "Creating new label on disk ${ISODISK}: UITTSSSHRED"
        fatlabel /dev/${ISODISK} "UITTSSSHRED" &>/dev/null
        fatlabel /dev/${ISODISK}1 "UITTSSSHRED" &>/dev/null
        else
        echo ""
        echo "Invalid block device or no USB drive found. Exiting...."
        exit 1
        fi
}

selectdisk
execute