#!/usr/bin/php
<?php
include('/etc/opt/UIT-TSS-TOOLBOX/server/include.php');

$fd = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($fd);

$arr = explode('|', $input);

$db = new db();

if ($arr[0] == "location") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = $arr[3];
    $department = $arr[4];
    $status = $arr[5];
    $diskRemoved = $arr[6];
    $note = $arr[7];

    $uuid = uniqid("location-", true);

    #Not the same insert statment as client parse code, ether address is DEFAULT here.
    $db->insertJob($uuid);
    $db->updateJob("tagnumber", $tagNum, $uuid);
    $db->updateJob("system_serial", $serial, $uuid);
    $db->updateJob ("date", $date, $uuid);
    $db->updateJob ("time", $time, $uuid);
    $db->updateJob ("department", $department, $uuid);

    # INSERT statement
    $db->insertLocation($time);
    $db->updateLocation("tagnumber", $tagNum, $time);
    $db->updateLocation("system_serial", $serial, $time);
    $db->updateLocation("location", $location, $time);
    $db->updateLocation("status", $status, $time);
    $db->updateLocation("disk_removed", $diskRemoved, $time);
    $db->updateLocation("note", $note, $time);
}


if ($arr[0] == "disk") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $diskModel = $arr[3];
    $diskSize = $arr[4];
    $diskSerial = $arr[5];
    $department = $arr[6];

    $uuid = uniqid("disk-", true);

    $db->insertJob($uuid);
    $db->updateJob ("date", $date, $uuid);
    $db->updateJob ("time", $time, $uuid);
    $db->updateJob("tagnumber", $tagNum, $uuid);
    $db->updateJob("system_serial", $serial, $uuid);
    $db->updateJob("disk_model", $diskModel, $uuid);
    $db->updateJob("disk_size", $diskSize, $uuid);
    $db->updateJob("disk_serial", $diskSerial, $uuid);
    $db->updateJob ("department", $department, $uuid);
}

if ($arr[0] == "remote") {
    $tagNum = $arr[1];
    $key = $arr[2];
    $value = $arr[3];

    if ($key == "job_queued") {
        if ($value == "0") {
            $value = "NULL";
        } elseif ($value == "1") {
            $value = "data collection";
        } elseif ($value == "2") {
            $value = "hpEraseAndClone";
        } elseif ($value == "3") {
            $value = "nvmeErase";
        } elseif ($value == "4") {
            $value = "nvmeVerify";
        } elseif ($value == "9") {
            $value = "update";
        } elseif ($value == "8") {
            $value = "findmy";
        } elseif ($value == "s") {
            $value = "shutdown";
        } elseif ($value == "f") {
            $value = "fail-test";
        }
    }

    if ($key == "cpu_temp") {
        $value = round(bcdiv($value, 1000, 2), 0);
    }

    $db->updateRemote($tagNum, $key, $value);
}

?>