#!/usr/bin/php
<?php

function filter ($string) {
    if ($string == "" || $string == " " || $string == "NULL" || empty($string) || is_null($string)) {
        return 1;
    } else {
        return 0;
    }
}

function clearArray() {
    unset($GLOBALS["result"]);
    unset($GLOBALS["arr"]);
    unset($GLOBALS["timeArr"]);
    unset($GLOBALS["execTime"]);
    unset($GLOBALS["arrayobject"]);
}

function timeSinceLastMarker($key) {
    global $timeArr;
    $curVal = null;
    $previousVal = null;
    $start = null;
    $end = null;
    $execTime = null;
    $curTime = null;

    if (filter($timeArr) == 1) {
        $timeArr = array();
    }

    $curTime = array("0" => hrtime(true));
    array_push($timeArr, $curTime);

    if (filter($arrayObject) == 1) {
        $arrayObject = new ArrayObject($timeArr);
        $iterator = $arrayObject->getIterator();
    }

    #$arrayObject->append(hrtime(true));

    $count = $iterator->count();

    if ($key == "start") {
        $iterator->rewind();
        $start = $iterator->current();
        $iterator->next();
    } elseif ($key == "end") {
        $iterator->seek($count - 1);
        $end = $iterator->current();
        $iterator->rewind();
        $start = $iterator->current();
        $execTime = round(($end - $start) / 1e9, 4);
    } elseif (is_numeric($key)) {
        while ($iterator->valid() && $count > 1) {
            $previousVal = $iterator->seek($count - 2);
            $iterator->seek($count - 1);
            $curVal = $iterator->current();
        }
        $execTime = round(($curVal - $previousVal) / 1e9, 4);
    }

    if (filter($execTime) == 0) {
        echo $execTime;
    }
}

?>