#!/usr/bin/php
<?php

function filter ($string) {
    if ($string == "" || $string == " " || $string == "NULL" || empty($string) || is_null($string)) {
        return 1;
    } else {
        return 0;
    }
}

function clearGlobals() {
    unset($GLOBALS["result"]);
    unset($GLOBALS["arr"]);
    unset($GLOBALS["timeArr"]);
    unset($GLOBALS["execTime"]);
    unset($GLOBALS["arrayobject"]);
    unset($GLOBALS["iterator"]);
    unset($GLOBALS["tmpArray"]);
}

function timeSinceLastMarker($key, $string) {
    global $timeArr;
    global $arrayObject;
    global $iterator;
    global $tmpArray;
    $curVal = null;
    $previousVal = null;
    $start = null;
    $end = null;
    $execTime = null;
    $curTime = null;
    $count = null;
    $markerStart = null;
    $markerEnd = null;

    $curTime = hrtime(true);

    if (filter($tmpArray) == 1) {
        $tmpArray = array();
        array_push($tmpArray, $curTime);
    }

    if (filter($tmpArrayObject) == 1) {
        $tmpArrayObject = new ArrayObject($tmpArray);
    }

    $tmpIterator = $tmpArrayObject->getIterator();
    $tmpArrayObject->append(hrtime(true));

    if (filter($timeArr) == 1) {
        $timeArr = array();
        array_push($timeArr, $curTime);
    }

    if (filter($arrayObject) == 1) {
        $arrayObject = new ArrayObject($timeArr);
    }

    $iterator = $arrayObject->getIterator();
    $arrayObject->append(hrtime(true));
    $count = $iterator->count() - 1;

    if ($key == "start") {
        $execTime = "...";
    } elseif ($key == "markerStart") {
        array_push($tmpArray, $curTime);
        $execTime = "...";
    } elseif ($key == "markerEnd") {
        $iterator->seek($count);
        $markerEnd = $iterator->current();
        $markerStart = $tmpIterator->rewind();
        $markerStart = $tmpIterator->current();
        $execTime = round(($markerEnd - $markerStart) / 1e9, 4);
    } elseif ($key == "end") {
        $iterator->seek($count);
        $end = $iterator->current();
        $iterator->rewind();
        $start = $iterator->current();
        $execTime = round(($end - $start) / 1e9, 4);
    } elseif (is_numeric($key)) {
        $iterator->seek($count - 1);
        $previousVal = $iterator->current();
        $iterator->seek($count);
        $curVal = $iterator->current();
        $execTime = round(($curVal - $previousVal) / 1e9, 4);
    }

    if (filter($execTime) == 0) {
        return $string . $execTime;
    }
}

?>