#!/usr/bin/php
<?php

function filter ($string) {
    if ($string == "" || $string == " " || $string == "NULL" || empty($string) || is_null($string)) {
        return 1;
    } else {
        return 0;
    }
}

function clearArray() {
    unset($GLOBALS["result"]);
    unset($GLOBALS["arr"]);
    unset($GLOBALS["timeArr"]);
    unset($GLOBALS["execTime"]);
    unset($GLOBALS["arrayobject"]);
}

function timeSinceLastMarker($key) {
    global $timeArr;

    if (filter($timeArr) == 1 || filter($arrayObject) == 1) {
        $timeArr = array();
        $arrayObject = new ArrayObject($timeArr);
        $iterator = $arrayObject->getIterator();
    }

    $arrayObject->append(hrtime(true));

    $count = $iterator->count();

    while ($iterator->valid() && $count > 1) {
        $previousVal = $iterator->seek($count - 2);
        $iterator->seek($count - 1);
        $curVal = $iterator->current();
    }

    $iterator->rewind();
    $start = $iterator->current();
    $iterator->seek($count - 1);
    $end = $iterator->current();
    
    if ($key == "start") {
        $execTime = $curVal;
    } elseif ($key == "end") {
        $execTime = round(($end - $start) / 1e9, 4);
    } elseif (is_numeric($key)) {
        $execTime = round(($curVal - $previousVal) / 1e9, 4);
    }

    echo $execTime;
}

?>