#!/usr/bin/php
<?php

require('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');
require('/var/lib/UIT-TSS-TOOLBOX/functions');


function dbSelect ($sql) {
    clearArray();
    global $pdo;
    global $arr;
    $arr = array();
    if (filter($sql) == 0) {
        $sql = $pdo->prepare($sql);
        $sql->execute();
        $arr = $sql->fetchAll(PDO::FETCH_ASSOC);
    } else {
        exit();
    }
}

function dbSelectVal ($sql) {
    clearArray();
    global $pdo;
    global $arr;
    global $result;
    $arr = array();
    if (filter($sql) == 0) {
        $sql = $pdo->prepare($sql);
        $sql->execute();
        $arr = $sql->fetchAll(PDO::FETCH_ASSOC);
        foreach ($arr as $key => $value) {
            $result = $value["result"];
        }
    } else {
        exit();
    }
}

function dbUpdateSS ($key, $value, $date) {
    global $pdo;
    $sql = "UPDATE serverstats SET $key = :value WHERE date = :date";
    $stmt = $pdo->prepare($sql);

    if (is_numeric($value) && $value <= 0) {
        $value = "NULL";
    }

    if (filter($key) == 0 && filter($value) == 1 && filter($date) == 0) {
        $stmt->bindParam(':value', $value, PDO::PARAM_NULL);
        $stmt->bindParam(':date', $date, PDO::PARAM_STR);
    } elseif (filter($key) == 0 && filter($value) == 0 && filter($date) == 0) {
        $stmt->bindParam(':value', $value, PDO::PARAM_STR);
        $stmt->bindParam(':date', $date, PDO::PARAM_STR);
    } else {
        $stmt = null;
    }

    if (filter($stmt) == 0) {
        $stmt->execute();
    }
    $stmt = null;
}

function dbUpdateCS ($key, $value, $tagnumber) {
    global $pdo;
    $sql = "UPDATE clientstats SET $key = :value WHERE tagnumber = :tagnumber";
    $stmt = $pdo->prepare($sql);

    if (is_numeric($value) && $value <= 0) {
        $value = "NULL";
    }

    if (filter($key) == 0 && filter($value) == 1 && filter($tagnumber) == 0) {
        $stmt->bindParam(':value', $value, PDO::PARAM_NULL);
        $stmt->bindParam(':tagnumber', $tagnumber, PDO::PARAM_STR);
    } elseif (filter($key) == 0 && filter($value) == 0 && filter($tagnumber) == 0) {
        $stmt->bindParam(':value', $value, PDO::PARAM_STR);
        $stmt->bindParam(':tagnumber', $tagnumber, PDO::PARAM_STR);
    } else {
        $stmt = null;
    }

    if (filter($stmt) == 0) {
        $stmt->execute();
    }
    $stmt = null;
}

function dbUpdateLoc ($key, $value, $tagnumber) {
    global $pdo;
    $sql = "UPDATE locations SET $key = :value WHERE tagnumber = :tagnumber";
    $stmt = $pdo->prepare($sql);

    if (filter($key) == 0 && filter($value) == 1 && filter($tagnumber) == 0) {
        $stmt->bindParam(':value', $value, PDO::PARAM_NULL);
        $stmt->bindParam(':tagnumber', $tagnumber, PDO::PARAM_STR);
    } elseif (filter($key) == 0 && filter($value) == 0 && filter($tagnumber) == 0) {
        $stmt->bindParam(':value', $value, PDO::PARAM_STR);
        $stmt->bindParam(':tagnumber', $tagnumber, PDO::PARAM_STR);
    } else {
        $stmt = null;
    }

    if (filter($stmt) == 0) {
        $stmt->execute();
    }
    $stmt = null;
}

?>