#!/usr/bin/php
<?php

require('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');
require('/var/lib/UIT-TSS-TOOLBOX/functions');

function dbSelect ($sql) {
    clearArray();
    global $pdo;
    global $arr;
    $arr = array();
    if (filter($sql) == 0) {
        $sql = $pdo->prepare($sql);
        $sql->execute();
        $arr = $sql->fetchAll(PDO::FETCH_ASSOC);
    } else {
        exit();
    }
}

function dbUpdateSS ($key, $value, $date) {
    if (filter($value) == 0) {
        $sql = "UPDATE serverstats SET $key = '$value' WHERE date = '$date'";
    } else {
        $sql = "UPDATE serverstats SET $key = NULL WHERE date = '$date'";
    }
}

?>