#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/mysql-functions');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

$fd = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($fd);

$arr = explode('|', $input);

if ($arr[0] == "location") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = $arr[3];
    $department = $arr[4];
    $status = $arr[5];
    $diskRemoved = $arr[6];
    $note = $arr[7];

    $uuid = uniqid("location-", true);

    #Not the same insert statment as client parse code, ether address is DEFAULT here.
    dbInsertJob($uuid);
    dbUpdateJob("tagnumber", "$tagNum", "$uuid");
    dbUpdateJob("system_serial", "$serial", "$uuid");
    dbUpdateJob ("date", "$date", "$uuid");
    dbUpdateJob ("time", "$time", "$uuid");
    dbUpdateJob ("department", "$department", "$uuid");

    # INSERT statement
    dbInsertLocation($time);
    dbUpdateLocation("tagnumber", "$tagNum", "$time");
    dbUpdateLocation("system_serial", "$serial", "$time");
    dbUpdateLocation("location", "$location", "$time");
    dbUpdateLocation("status", "$status", "$time");
    dbUpdateLocation("disk_removed", "$diskRemoved", "$time");
    dbUpdateLocation("note", "$note", "$time");
}


if ($arr[0] == "disk") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $diskModel = $arr[3];
    $diskSize = $arr[4];
    $diskSerial = $arr[5];
    $department = $arr[6];

    $uuid = uniqid("disk-", true);

    dbInsertJob($uuid);
    dbUpdateJob ("date", "$date", "$uuid");
    dbUpdateJob ("time", "$time", "$uuid");
    dbUpdateJob("tagnumber", "$tagNum", "$uuid");
    dbUpdateJob("system_serial", "$serial", "$uuid");
    dbUpdateJob("disk_model", "$diskModel", "$uuid");
    dbUpdateJob("disk_size", "$diskSize", "$uuid");
    dbUpdateJob("disk_serial", "$diskSerial", "$uuid");
    dbUpdateJob ("department", "$department", "$uuid");
}

if ($arr[0] == "remote") {
    $tagNum = $arr[1];
    $key = $arr[2];
    $value = $arr[3];

    if ($key == "task") {
        if ($value == "0") {
            $value = "NULL";
        } elseif ($value == "1") {
            $value = "data collection";
        } elseif ($value == "2") {
            $value = "hpEraseAndClone";
        } elseif ($value == "3") {
            $value = "nvmeErase";
        } elseif ($value == "9") {
            $value = "update";
        } elseif ($value == "8") {
            $value = "findmy";
        }
    }

    dbUpdateRemote("$tagNum", "$key", "$value");

}

?>