#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/mysql-functions');

$dt = new DateTimeImmutable();
$date = $dt->format('Y-m-d');
$time = $dt->format('Y-m-d H:i:s.v');

$stdin = fopen('php://stdin', 'r');
$line = trim(fgets(STDIN));

$arr = explode('|', $line);

if ($arr[0] == "location") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = $arr[3];
    $status = $arr[4];
    $problem = $arr[5];

    $uuid = uniqid("location-", true);

    #Not the same insert statment as client parse code, ether address is DEFAULT here.
    dbInsertJob($uuid);
    dbUpdateJob("tagnumber", "$tagNum", "$uuid");
    dbUpdateJob("system_serial", "$serial", "$time");
    dbUpdateJob ("date", "$date", "$uuid");
    dbUpdateJob ("time", "$time", "$uuid");

    # INSERT statement
    dbInsertLocation($time);
    dbUpdateLocation("tagnumber", "$tagNum", "$time");
    dbUpdateLocation("system_serial", "$serial", "$time");
    dbUpdateLocation("location", "$location", "$time");
    dbUpdateLocation("status", "$status", "$time");
    dbUpdateLocation("problem", "$problem", "$time");
}

?>