#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/include.php');

$stdin = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($stdin);

$db = new db();

$db->select($input);
$arr = $db->get();
if (arrFilter($arr) == 0)  {
    foreach ($arr as $key => $value) {
        if (strFilter($value["result"]) == 0) {
            echo $value["result"] . PHP_EOL;
        } else {
            echo "NULL" . PHP_EOL;
        }
    }
} else {
    echo "NULL" . PHP_EOL;
}

?>