#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/mysql-functions');

$stdin = fopen('php://stdin', 'r');
$input = trim(fgets(STDIN));
fclose($stdin);

dbSelect("$input");

foreach ($arr as $key => $value) {
    if (filter($value) == "1") {
        $value = "NULL";
    }
    echo $value . PHP_EOL;
}

?>