#!/bin/php
<?php
### jobstats
ALTER TABLE jobstats MODIFY COLUMN uuid VARCHAR(36)
ALTER TABLE jobstats MODIFY COLUMN tagnumber INT
ALTER TABLE jobstats MODIFY COLUMN etheraddress VARCHAR(17)
ALTER TABLE jobstats MODIFY COLUMN date DATE
ALTER TABLE jobstats MODIFY COLUMN time DATETIME
ALTER TABLE jobstats MODIFY COLUMN bios_vendor VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN bios_version VARCHAR(128)
ALTER TABLE jobstats MODIFY COLUMN bios_date VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN bios_revision VARCHAR(128)
ALTER TABLE jobstats MODIFY COLUMN bios_firmware VARCHAR(128)
ALTER TABLE jobstats MODIFY COLUMN system_manufacturer VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN system_productname VARCHAR(128)
ALTER TABLE jobstats MODIFY COLUMN system_serial VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN system_uuid VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN system_sku VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN system_family VARCHAR(128)
ALTER TABLE jobstats MODIFY COLUMN motherboard_manufacturer VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN motherboard_serial VARCHAR(128)
ALTER TABLE jobstats MODIFY COLUMN chassis_manufacturer VARCHAR(64)
ALTER TABLE jobstats MODIFY COLUMN chassis_type VARCHAR(32)

UPDATE jobstats SET time = NULL WHERE time = '0000-00-00 00:00:00'


?>