#!/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$sql = "UPDATE jobstats SET uuid = NULL WHERE uuid = 'N/A'";
$conn->query($sql);
$sql = "UPDATE jobstats SET uuid = NULL WHERE uuid = ''";
$conn->query($sql);

$sql = "ALTER TABLE jobstats MODIFY COLUMN uuid VARCHAR(36) NOT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN tagnumber VARCHAR(6) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN etheraddress VARCHAR(17) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN date DATE DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN time DATETIME DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_vendor VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_version VARCHAR(32) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_date VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_revision VARCHAR(8) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_firmware VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN system_manufacturer VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN system_productname VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN system_serial VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN system_uuid VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN system_sku VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN system_family VARCHAR(64) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN motherboard_manufacturer VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN motherboard_serial VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN chassis_manufacturer VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN chassis_type VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN chassis_serial VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN chassis_tag VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN chassis_psu VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN cpu_family VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN cpu_manufacturer VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN cpu_version VARCHAR(64) DEFAULT NULL";
$conn->query($sql);


$sql = "ALTER TABLE serverstats MODIFY COLUMN date DATE";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN time DATETIME DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN laptop_count SMALLINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN last_image_update DATE DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN all_jobs MEDIUMINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN clone_jobs MEDIUMINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN erase_jobs MEDIUMINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN all_avgtime MEDIUMINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN clone_avgtime SMALLINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN nvme_erase_avgtime SMALLINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN ssd_erase_avgtime SMALLINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN tbw_pcnt TINYINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN battery_health TINYINT DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE serverstats MODIFY COLUMN boot_time SMALLINT DEFAULT NULL";
$conn->query($sql);


$conn->close();
?>