#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/PDO-connect');

$date = date('Y-m-d',time());
$time = date('Y-m-d H:i:s', time());

$default = "NULL";
$location = "NULL";

$stdin = fopen('php://stdin', 'r');
$line = trim(fgets(STDIN));

$arr = explode('|', $line);

if ($arr[0] == "begin") {
    $tagNum = $arr[1];
    $location = "Plugged in and booted on laptop table.";
}

if ($arr[0] == "end") {
    $tagNum = $arr[1];
    $location = "Finished work on laptop table.";
}

if ($arr[0] == "custom") {
    $tagNum = $arr[1];
    $serial = $arr[2];
    $location = $arr[3];
    $status = $arr[4];
    $problem = $arr[5];

    if (empty($serial) || $serial == "" || $serial == " ") {
        $serial = $default;
    }

    $uuid = uniqid("manual", true);

    $sql = "INSERT INTO jobstats(uuid,tagnumber,etheraddress,date,time,bios_vendor,bios_version,bios_date,";
    $sql .= "bios_revision,bios_firmware,system_manufacturer,system_productname,system_serial,system_uuid,system_sku,";
    $sql .= "system_family,motherboard_manufacturer,motherboard_serial,chassis_manufacturer,chassis_type,chassis_serial,";
    $sql .= "chassis_tag,chassis_psu,cpu_family,cpu_manufacturer,cpu_id,cpu_version,cpu_voltage,cpu_maxspeed,cpu_currentspeed,";
    $sql .= "cpu_cores,cpu_threads,ram_serial,battery_manufacturer,battery_name,battery_capacity,battery_voltage,battery_serial,";
    $sql .= "battery_manufacturedate,battery_alarm,battery_health,battery_charge_cycles,boot_errors,boot_time,action,reboot,disk,";
    $sql .= "disksizegb,disk_model,disk_serial,disk_firmware,disk_health,disk_temp,disk_reads,disk_writes,max_tbw,all_time,";
    $sql .= "erase_completed,erase_mode,erase_time,erase_diskpercent,clone_completed,clone_mode,clone_time,clone_master,";
    $sql .= "clone_server,clone_image,clone_imageupdate,clone_sambauser) ";
    $sql .= "VALUES ('$uuid','$tagNum',$default,'$date','$time',$default,$default,$default,$default,$default,$default,$default,";
    $sql .= "'$serial',$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,";
    $sql .= "$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,";
    $sql .= "$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,";
    $sql .= "$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,$default,";
    $sql .= "$default,$default,$default,$default,$default,$default,$default,$default,$default)";
    $pdo->query($sql);
}



# INSERT statement
$sql = "INSERT INTO locations(tagnumber,chassis_serial,location,status,problem,time) ";
$sql .= "VALUES (:tagnumber, :chassis_serial, :location, :status, :problem, :time)";
$pdo->prepare($sql);
$pdo->bindParam(':tagnumber', $tagNum, PDO::PARAM_STR);
$pdo->bindParam(':chassis_serial', $serial, PDO::PARAM_STR);
$pdo->bindParam(':location', $location, PDO::PARAM_STR);
$pdo->bindParam(':status', $status, PDO::PARAM_STR);
$pdo->bindParam(':problem', $problem, PDO::PARAM_STR);
$pdo->bindParam(':time', $time, PDO::PARAM_STR);
$pdo->execute();



#Update Serial Numbers
$sql = "SELECT chassis_serial FROM clientstats WHERE tagnumber = '$tagNum'";
foreach ($pdo->query($sql) as $row) {
    $serial = $row['chassis_serial'];
    $sql = "UPDATE locations SET chassis_serial = '$serial' WHERE tagnumber = '$tagNum'";
    $pdo->query($sql);
}

$sql = "UPDATE locations SET location = NULL WHERE location = ''";
$pdo->query($sql);

$sql = "UPDATE locations SET status = NULL WHERE status = ''";
$pdo->query($sql);

$sql = "UPDATE locations SET problem = NULL WHERE problem = ''";
$pdo->query($sql);

$sql = "UPDATE locations SET chassis_serial = NULL WHERE chassis_serial = ''";
$pdo->query($sql);

$pdo = null;
?>