#!/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$sql = "ALTER TABLE jobstats MODIFY COLUMN uuid VARCHAR(36) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN tagnumber VARCHAR(6) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN etheraddress VARCHAR(17) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN date DATE DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN time DATETIME DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_vendor VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_version VARCHAR(32) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_date VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_revision VARCHAR(8) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_firmware VARCHAR(16) DEFAULT NULL";
$conn->query($sql);
$sql = "ALTER TABLE jobstats MODIFY COLUMN bios_firmware VARCHAR(8) DEFAULT NULL";
$conn->query($sql);

?>