<?php
require('/var/www/html/uit-web/header.php');
require('/var/www/html/uit-web/php/include.php');

if ($_SESSION['authorized'] != "yes") {
  die();
}
?>

<html>
    <head>
        <meta charset='UTF-8'>
        <link rel='stylesheet' type='text/css' href='/css/main.css' />
        <title>UIT Laptop Managment - Documentation</title>
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    </head>
    <body>
        <div class='menubar'>
            <p><span style='float: left;'><a href='/index.php'>Return Home</a></span></p>
            <p><span style='float: right;'>Logged in as <b><?php echo htmlspecialchars($login_user); ?></b>.</span></p>
            <br>
            <p><span style='float: right;'>Not <b><?php echo htmlspecialchars($login_user); ?></b>? <a href='logout.php'>Click Here to Logout</a></span></p>
        </div>

        <div class='pagetitle'><h1>UIT-TSS-TOOLBOX Documentation</h1></div>

        <div class='documentation'>
            <h3>Error - Kernel out of Date</h3>
            <p>The <i>Kernel Out of Date</i> error means that the running kernel on the client is not at the same version as the one in the client's filesystem. This can usually happen after updating the ISO file on the server.</p>
            <p>The clients get their running kernel from the USB sticks at boot time. Unfortunately, there is no easy way to update the kernel without rebooting the entire system.</p>
            <p>The ISO file on the server can be regenerated by running the command <code>sudo uit-iso-configure</code>. This command will regenerate the ISO file that is given to the clients when they start up. The kernel is stored on the USB sticks and the filesystem for the clients is hosted on the server. When a client is booted, the client retrieves both the kernel from the USB stick and the filesystem from the network.</p>
            <p>If the ISO file on the server (which includes the kernel and the filesystem) is updated using <code>sudo uit-iso-configure</code>, then there is a decent chance that the kernel version has changed to a newer version. NFS and many other services require modules from the kernel to function correctly. When the kernel is updated, various services will try to activate kernel modules in the old version of the kernel, which is no longer in the filesystem.</p>
            <p>To fix this error, please shutdown the client and reboot it with a USB stick with an updated kernel. To make sure the USB stick has the updated kernel, please first update the ISO file using <code>sudo uit-iso-configure</code>, then plug in the USB drive and run the <code>sudo uit-iso-flash</code> command to flash the ISO file to the thumb drive.</p>
        </div>

        <div class="uit-footer">
            <img src="/images/uh-footer.svg">
        </div>
    </body>
</html>