#!/bin/bash

/usr/bin/chmod 750 /usr/sbin/uit-*
/usr/bin/chown root:uit /usr/sbin/uit-*

/usr/bin/chown root:uit /etc/opt/UIT-TSS-TOOLBOX -R
find /etc/opt/UIT-TSS-TOOLBOX -type d -exec chmod 750 {} \;
find /etc/opt/UIT-TSS-TOOLBOX -type f -exec chmod 660 {} \;

/usr/bin/chown root:uit /var/www/html/management -R
find /var/www/html/management -type d -exec chmod 750 {} \;
find /var/www/html/management -type f -exec chmod 660 {} \;
chmod 755 /var/www/html/management/bash/ -R

echo -e "\n" >> /etc/cron.d/uit-cron

cp -r /etc/opt/UIT-TSS-TOOLBOX/client/uit-tss-client_2.0-1_amd64/ /home/cameron

chown cameron:cameron /home/cameron/uit-tss-client_2.0-1_amd64/ -R
chmod 755 /home/cameron/uit-tss-client_2.0-1_amd64/DEBIAN/ -R

/usr/bin/chmod 750 /home/cameron/firewall
/usr/bin/chown root:root /home/cameron/firewall
/usr/bin/chmod 750 /home/cameron/startup-script
/usr/bin/chown root:root /home/cameron/startup-script

/usr/bin/chown nobody:nogroup /home/images -R

mysql laptopDB < /etc/opt/UIT-TSS-TOOLBOX/server/mysql/mysql-procedures.sql
mysql laptopDB < /etc/opt/UIT-TSS-TOOLBOX/server/mysql/mysql-tables.sql


if [[ ! -f /var/www/html/management/favicon.ico ]]; then
    wget 'https://uh.edu/favicon.ico' --output-document /var/www/html/management/favicon.ico
fi

if [[ ! -f  /var/www/html/management/images/uh-logo.png ]]; then
    wget 'http://www.sa.uh.edu/brand/_img/uh-wide-full-color-rgb.png' --output-document=/var/www/html/management/images/uh-logo.png
fi

rsync -Pav --delete /home/cameron/laptop-pictures/ /var/www/html/management/images/

rsync -Pav --delete /home/cameron/jquery /var/www/html/management/

rsync -Pav --delete /home/cameron/google-charts /var/www/html/management/
