#!/bin/bash

/usr/bin/chmod 750 /usr/sbin/uit-tss-*
/usr/bin/chown root:uit /usr/sbin/uit-tss-*
/usr/bin/chmod 750 /var/lib/UIT-TSS-TOOLBOX/ -R
/usr/bin/chown root:uit /var/lib/UIT-TSS-TOOLBOX/ -R
echo -e "\n" >> /etc/cron.d/01-uit-tss-cronjobs
echo -e "\n" >> /etc/cron.d/02-uit-tss-cronjobs
cp -r /var/lib/UIT-TSS-TOOLBOX/uit-tss-client_2.0-1_amd64/ /home/cameron
chown cameron:cameron /home/cameron/uit-tss-client_2.0-1_amd64/ -R
chmod 775 /home/cameron/uit-tss-client_2.0-1_amd64/DEBIAN/ -R
chmod 755 /root/UIT-TSS-TOOLBOX/uit-tss-toolbox_2.0-1_amd64/var/lib/UIT-TSS-TOOLBOX/uit-tss-client_2.0-1_amd64/DEBIAN/ -R