#!/bin/bash

/usr/bin/chmod 750 /usr/sbin/uit-*
/usr/bin/chown root:uit /usr/sbin/uit-*

/usr/bin/chmod 700 /root/uit-ssl
/usr/bin/chmod 700 /root/uit-ssl/update-certs
/usr/bin/chown root:root /root/uit-ssl -R

/usr/bin/chown cameron:cameron /home/cameron/powershell -R

sed --in-place "s/WAN_IF/$(cat /home/cameron/.uit-passwd | grep '^WAN_IF=' | sed 's/WAN_IF=//g')/g" /usr/sbin/uit-firewall
sed --in-place "s/WAN_IP/$(cat /home/cameron/.uit-passwd | grep '^WAN_IP=' | sed 's/WAN_IP=//g' | sed 's/\//\\\//g')/g" /usr/sbin/uit-firewall
sed --in-place "s/LAN_IF/$(cat /home/cameron/.uit-passwd | grep '^LAN_IF=' | sed 's/LAN_IF=//g')/g" /usr/sbin/uit-firewall
sed --in-place "s/LAN_IP/$(cat /home/cameron/.uit-passwd | grep '^LAN_IP=' | sed 's/LAN_IP=//g' | sed 's/\//\\\//g')/g" /usr/sbin/uit-firewall
sed --in-place "s/PRINTER_IP/$(cat /home/cameron/.uit-passwd | grep '^PRINTER_IP=' | sed 's/PRINTER_IP=//g' | sed 's/\//\\\//g')/g" /usr/sbin/uit-firewall
sed --in-place "s/LAN_IF/$(cat /home/cameron/.uit-passwd | grep '^LAN_IF=' | sed 's/LAN_IF=//g')/g" /etc/dnsmasq.d/uit-dhcp.conf

if [[ ! -d /srv/nfs/uit-toolbox/images ]]; then
    mkdir -p /srv/nfs/uit-toolbox/images
fi
find /srv/nfs/ -type d -exec chmod 755 {} \;
#find /srv/nfs/uit-toolbox/images -type d -exec chmod 755 {} \;
#find /srv/nfs/uit-toolbox/images -type f -exec chmod 664 {} \;
/usr/bin/chown nobody:nogroup /srv/nfs/uit-toolbox/images -R

/usr/bin/chown root:uit /etc/opt/uit-toolbox -R
find /etc/opt/uit-toolbox -type d -exec chmod 750 {} \;
find /etc/opt/uit-toolbox -type f -exec chmod 660 {} \;

/usr/bin/chown root:uit /var/www/html/uit-web -R
find /var/www/html/uit-web -type d -exec chmod 755 {} \;
find /var/www/html/uit-web -type f -exec chmod 664 {} \;
chown www-data:uit /var/www/html/uit-web/bash/uit-print-pdf
chmod 750 /var/www/html/uit-web/bash/uit-print-pdf

if [[ ! -d /srv/uit-toolbox/client/src/ ]]; then
    mkdir /srv/uit-toolbox/client/src/
fi
if [[ ! -d /srv/uit-toolbox/client/pkg/ ]]; then
    mkdir /srv/uit-toolbox/client/pkg/
fi
if [[ ! -d /srv/uit-toolbox/client/iso/ ]]; then
    mkdir /srv/uit-toolbox/client/iso/
fi

/usr/bin/chown root:uit /srv/uit-toolbox/client/src -R
/usr/bin/chown root:uit /srv/uit-toolbox/client/pkg -R
# Find command w/ directory is different regex
find /srv/uit-toolbox/ -type d -not -path "*/iso*" -exec chmod 755 {} \;
find /srv/uit-toolbox/ -type f -not -path "*/iso/*" -exec chmod 664 {} \;
echo -e "\n" >> /etc/cron.d/uit-cron

# Update mysql tables & procedures
mysql laptopDB < /etc/opt/uit-toolbox/server/mysql/mysql-procedures.sql
mysql laptopDB < /etc/opt/uit-toolbox/server/mysql/mysql-tables.sql

# Insert include.php with modifications for the clients.
cat /var/www/html/uit-web/php/include.php | sed 's/localhost/10.0.0.1/g' | sed 's/uitweb/uitclient/g' > /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/opt/uit-toolbox/include.php
sed --in-place 's/WEB_SVC_PASSWD/CLIENT_PASSWD/g' /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/opt/uit-toolbox/include.php


# Set passwords for various services
echo "Updating Passwords..."

# MySQL Admin Password
echo "  --MySQL Admin Password"
if [[ -f /home/cameron/.my.cnf ]]; then 
    DB_ADMIN_PASSWD=$(cat /home/cameron/.my.cnf | grep '^password=' | sed 's/password=//g' | head -n1)
else
 DB_ADMIN_PASSWD=$(cat /home/cameron/.uit-passwd | grep '^DB_ADMIN_PASSWD=' | sed 's/DB_ADMIN_PASSWD=//g')
fi

# MySQL Client Password
echo "  --Client Password"
CLIENT_PASSWD=$(cat /home/cameron/.uit-passwd | grep '^CLIENT_PASSWD=' | sed 's/CLIENT_PASSWD=//g')

# Website PHP Scripts
echo "  --Web Service Password"
WEB_SVC_PASSWD=$(openssl rand 30 | hexdump | tr -d '\n' | sed 's/[[:space:]]//g' | head -n1 | md5sum | awk '{print $1}')

# All Users for the Website
echo "  --Web User Username and Password"
mysql --database='laptopDB' --execute="DELETE FROM logins;"
WEB_USER_PASSWD=$(cat /home/cameron/.uit-passwd | grep '^WEB_USER_PASSWD=' | sed 's/WEB_USER_PASSWD=//g')
for i in $(cat /home/cameron/.uit-passwd | grep '^WEB_USERS=' | sed 's/WEB_USERS=//g'); do
        mysql --database='laptopDB' --execute="INSERT INTO logins (username, name, password) VALUES (${i},MD5('${WEB_USER_PASSWD}'));"
done
mysql --database='laptopDB' --execute="UPDATE logins SET username = MD5(username);"

# Webmaster Email
echo "  --Webmaster Email"
WEBMASTER_EMAIL=$(cat /home/cameron/.uit-passwd | grep '^WEBMASTER_EMAIL=' | sed 's/WEBMASTER_EMAIL=//g')

# Webmaster Name
echo "  --Webmaster Name"
WEBMASTER_NAME=$(cat /home/cameron/.uit-passwd | grep '^WEBMASTER_NAME=' | sed 's/WEBMASTER_NAME=//g')

# IP Address of the Server
echo "  --Server IP Address"
IP_ADDRESS=$(cat /home/cameron/.uit-passwd | grep '^IP_ADDRESS=' | sed 's/IP_ADDRESS=//g')

# MySQL Users
mysql --database='laptopDB' --execute="ALTER USER 'cameron'@'localhost' IDENTIFIED BY '${DB_ADMIN_PASSWD}';"
mysql --database='laptopDB' --execute="ALTER USER 'uitclient'@'10.0.0.0/255.255.0.0' IDENTIFIED BY '${CLIENT_PASSWD}';"
mysql --database='laptopDB' --execute="ALTER USER 'uitweb'@'localhost' IDENTIFIED BY '${WEB_SVC_PASSWD}';"


# Client-side Bash Scripts
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/usr/sbin/uit-tss-client
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/opt/uit-toolbox/include.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/opt/uit-toolbox/api-client.php

# Web PHP Scripts
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/uit-web/locations.php
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/uit-web/api/endpoint.php
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/uit-web/bash/uit-print-pdf
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/uit-web/php/include.php
sed --in-place "s/WEB_SVC_PASSWD/${WEB_SVC_PASSWD}/g" /var/www/html/uit-web/api/print-page.php

# This is the client password because clients don't know web password
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /var/www/html/uit-web/api/refresh-client.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /var/www/html/uit-web/tagnumber.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /var/www/html/uit-web/locations.php
sed --in-place "s/CLIENT_PASSWD/${CLIENT_PASSWD}/g" /usr/sbin/uit-sql-refresh

# Webmaster Name and Email
sed --in-place "s/WEBMASTER_EMAIL/${WEBMASTER_EMAIL}/g" /var/www/html/uit-web/index.php
sed --in-place "s/WEBMASTER_NAME/${WEBMASTER_NAME}/g" /var/www/html/uit-web/index.php

# Webmaster IP Address, Name, and Email for SSL Cert
sed --in-place "s/WEBMASTER_EMAIL/${WEBMASTER_EMAIL}/g" /root/uit-ssl/uit-web.cfg
sed --in-place "s/IP_ADDRESS/${IP_ADDRESS}/g" /root/uit-ssl/uit-web.cfg
sed --in-place "s/WEBMASTER_NAME/${WEBMASTER_NAME}/g" /root/uit-ssl/uit-web.cfg


# Build client .deb package
(cd /srv/uit-toolbox/client/src/
chmod 755 /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/DEBIAN/
chmod 755 /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/DEBIAN/control
chmod 755 /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64/DEBIAN/postinst
dpkg-deb --build --root-owner-group /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64 
mv -v /srv/uit-toolbox/client/src/uit-tss-client_2.0-1_amd64.deb /srv/uit-toolbox/client/pkg/uit-toolbox-client.deb 
)

if [[ ! -f /var/www/html/uit-web/favicon.ico ]]; then
    wget 'https://uh.edu/favicon.ico' --output-document /var/www/html/uit-web/favicon.ico
fi

if [[ ! -f  /var/www/html/uit-web/images/uh-logo.png ]]; then
    wget 'http://www.sa.uh.edu/brand/_img/uh-wide-full-color-rgb.png' --output-document=/var/www/html/uit-web/images/uh-logo.png
fi

rsync -Pav --delete /home/cameron/laptop-pictures/ /var/www/html/uit-web/images/

rsync -Pav --delete /home/cameron/google-charts /var/www/html/uit-web/

if [[ -f /srv/uit-toolbox/client/certs ]]; then
    rm /srv/uit-toolbox/client/certs
fi

mkdir -p /srv/uit-toolbox/client/certs/
cp /etc/ssl/certs/ca.crt /srv/uit-toolbox/client/certs/ca.crt
cp /etc/ssl/certs/uit-web.crt /srv/uit-toolbox/client/certs/uit-web.crt
