#!/bin/bash

if [[ $1 != "WEB_SVC_PASSWD" ]]; then
    exit 1;
fi

if [[ $2 -n ]]; then
    exit 1;
fi

filename=$2

if [[ $filename -n ]]; then
    ffmpeg -loglevel quiet -hide_banner -nostats -i "/tmp/${filename}" -c:a aac -f mp4 - | base64
    fi

rm "/tmp/${filename}"