#!/bin/bash

if [[ $1 != "WEB_SVC_PASSWD" ]]; then
    exit 1;
fi

uuid=$2
fileInput=$3

if [[ $fileInput -n ]]; then
    echo $fileInput | ffmpeg -loglevel quiet -hide_banner -nostats -i pipe: -c:a aac -f mp4 - | base64
    fi