#!/bin/bash

if [[ $1 != "WEB_SVC_PASSWD" ]]; then
    exit 1;
fi

filename=$2

ffmpeg -loglevel quiet -hide_banner -nostats -i "/var/www/html/uit-web/transcode/${filename}" -c:a aac -movflags frag_keyframe+empty_moov -f mp4 pipe:1 | base64