#!/bin/bash

if [[ $1 != "WEB_SVC_PASSWD" ]]; then
    exit 1;
fi

password="$1"
tagnumber="$2"
customer_name="$3"
checkout_date="$4"
customer_psid="$5"
return_date="$6"

wkhtmltopdf --quiet \
    --page-size Letter \
    "https://localhost:1411/api/print-page.php?password=${password}&tagnumber=${tagnumber}&customer_name=${customer_name}&checkout_date=${checkout_date}&return_date=${return_date}" - | lp -o page-ranges=1