#!/bin/bash

if [[ $1 != "UIT_WEB_SVC_PASSWD" ]]; then
    exit 1;
fi

password=$1
tagnumber=$2
customer_name=$3
checkout_date=$4
return_date=$5

curl --silent -X POST \
    --data-urlencode "password=${password}" \
    --data-urlencode "tagnumber=${tagnumber}" \
    --data-urlencode "customer_name=${customer_name}" \
    --data-urlencode "checkout_date=${checkout_date}" \
    --data-urlencode "return_date=${return_date}" \
    'https://localhost:1411/api/print-page.php' | wkhtmltopdf --quiet --page-size Letter - - | lp -o page-ranges=1