#!/usr/bin/php
<?php
include('/var/lib/UIT-TSS-TOOLBOX/DB-connect-local.php');

$date = date('Y-m-d',time());
$time = date('Y-m-d H:i:s', time());

##### clientstats #####
$tag_txt = preg_replace('/[^0-9]/', '', file_get_contents('/root/tagnumber'));
echo "Updating laptop: '" . $tagNum . "' in SQL database" . PHP_EOL;
$sql = "SELECT tagnumber FROM jobstats WHERE tagnumber = '".$tag_txt."'";
if (isset($sql)) {
$results = $conn->query($sql);
$i = $results->fetch_all(MYSQLI_ASSOC);
foreach ($i as $key => $value) {
    unset($tagNum);
    global $tagNum;
    $tagNum = $value['tagnumber'];

    $sql = "SELECT tagnumber FROM clientstats WHERE tagnumber = '$tagNum'";
    $results = $conn->query($sql);
    $exists = mysqli_num_rows($results);
    if ($exists == "0") {
        $sql = "INSERT INTO clientstats(tagnumber,device_type,last_job_date,all_lastuuid,all_time,all_avgtime,";
        $sql .= "erase_time,erase_avgtime,clone_time,clone_avgtime,all_jobs,erase_jobs,clone_jobs,disk)";
        $sql .= "VALUES ($tagNum,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT,DEFAULT)";
        $conn->query($sql);
    }

    #Update disks
    $sql = "SELECT disk FROM jobstats WHERE tagnumber = '$tagNum'";
    $disks = $conn->query($sql);
    while ($row = $disks->fetch_array(MYSQLI_ASSOC)) {
        $sql = "UPDATE clientstats SET disk = '" . $row['disk'] . "' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
    }

    # Erase times
    $sql = "SELECT erase_time FROM jobstats WHERE tagnumber = '$tagNum' AND erase_completed = 'Yes'";
    $results = $conn->query($sql);
    $eraseLineCount = mysqli_num_rows($results);
    $sql = "SELECT ROUND(SUM(erase_time), 2) AS erase_time FROM jobstats WHERE tagnumber = '$tagNum' AND erase_completed = 'Yes'";
    $results = $conn->query($sql);
    $i = $results->fetch_all(MYSQLI_ASSOC);
    $eraseTime = 0;
    foreach($i as $key => $value) {
        $eraseTime = $eraseTime + $value['erase_time'];
    }
    # Update total erase jobs
    $sql = "UPDATE clientstats SET erase_jobs = '$eraseLineCount' WHERE tagnumber = '$tagNum'";
    $conn->query($sql);
    # Avg. Times
    if ($eraseLineCount >= 1) {
        $sql = "UPDATE clientstats SET erase_time = '$eraseTime' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
        $avgTimeSec = round($eraseTime / $eraseLineCount);
        $avgTimeMin = round($avgTimeSec / 60) . " minutes";
        $sql = "UPDATE clientstats SET erase_avgtime = '$avgTimeMin' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
    }

    # Clone times
    $sql = "SELECT clone_time FROM jobstats WHERE tagnumber = '$tagNum' AND clone_completed = 'Yes'";
    $results = $conn->query($sql);
    $cloneLineCount = mysqli_num_rows($results);
    $sql = "SELECT ROUND(SUM(clone_time), 2) AS clone_time FROM jobstats WHERE tagnumber = '$tagNum' AND clone_completed = 'Yes'";
    $results = $conn->query($sql);
    $i = $results->fetch_all(MYSQLI_ASSOC);
    $cloneTime = 0;
    foreach($i as $key => $value) {
        $cloneTime = $cloneTime + $value['clone_time'];
    }
    # Update total clone jobs
    $sql = "UPDATE clientstats SET clone_jobs = '$cloneLineCount' WHERE tagnumber = '$tagNum'";
    $conn->query($sql);
    # Avg. Times
    if ($cloneLineCount >= 1) {
        $sql = "UPDATE clientstats SET clone_time = '$cloneTime' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
        $avgTimeSec = round($cloneTime / $cloneLineCount);
        $avgTimeMin = round($avgTimeSec / 60) . " minutes";
        $sql = "UPDATE clientstats SET clone_avgtime = '$avgTimeMin' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
    }


    # All (clone + erase) times
    $allLineCount = $cloneLineCount + $eraseLineCount;
    $sql = "SELECT ROUND(SUM(erase_time) + SUM(clone_time), 2) AS all_time FROM jobstats WHERE tagnumber = '$tagNum' AND (erase_completed = 'Yes' OR clone_completed = 'Yes')";
    $results = $conn->query($sql);
    $i = $results->fetch_all(MYSQLI_ASSOC);
    $allTime = 0;
    foreach($i as $key => $value) {
        $allTime = $allTime + $value['all_time'];
    }
    $sql = "SELECT ROUND((SUM(erase_time) * $eraseLineCount) + (SUM(clone_time) * $cloneLineCount) / ($eraseLineCount + $cloneLineCount), 2) AS all_avgtime FROM jobstats WHERE tagnumber = '$tagNum' AND (erase_completed = 'Yes' OR clone_completed = 'Yes')";
    $results = $conn->query($sql);
    $i = $results->fetch_all(MYSQLI_ASSOC);
    $allAvgTime = 0;
    foreach($i as $key => $value) {
        $allAvgTime = $allAvgTime + $value['all_avgtime'];
    }
    # Update total jobs
    $sql = "UPDATE clientstats SET all_jobs = '$allLineCount' WHERE tagnumber = '$tagNum'";
    $conn->query($sql);
    #Avg Times
    if ($allLineCount >= 1) {
        $sql = "UPDATE clientstats SET all_time = '$allTime' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
        $avgTimeSec = round($allTime / $allLineCount);
        $avgTimeMin = round($avgTimeSec / 60) . " minutes";
        $sql = "UPDATE clientstats SET all_avgtime = '$avgTimeMin' WHERE tagnumber = '$tagNum'";
        $conn->query($sql);
    }
    # Update last_job_date and all_lastuuid
    $sql = "SELECT uuid,date FROM jobstats WHERE tagnumber = '$tagNum' ORDER BY date DESC LIMIT 1";
    $results = $conn->query($sql);
    $i = $results->fetch_all(MYSQLI_ASSOC);
    foreach($i as $key => $value) {
        $lastDate = $value['date'];
        $lastUUID = $value['uuid'];
    }
    # Update last_job_date
    $sql = "UPDATE clientstats SET last_job_date = '$lastDate' WHERE tagnumber = '$tagNum'";
    $conn->query($sql);
    # Update all_lastuuid
    $sql = "UPDATE clientstats SET all_lastuuid = '$lastUUID' WHERE tagnumber = '$tagNum'";
    $conn->query($sql);
    # Device Type
    $sql = "SELECT clone_image FROM jobstats WHERE tagnumber = '$tagNum'";
    $results = $conn->query($sql);
    $i = $results->fetch_all(MYSQLI_ASSOC);
    foreach($i as $key => $value) {
        $deviceType = $value['clone_image'];
        if (preg_match('/HP/',$deviceType,$matches)) {
            $sql = "UPDATE clientstats SET device_type = 'HP' WHERE tagnumber = '$tagNum'";
            $conn->query($sql);
        } else {
            $sql = "UPDATE clientstats SET device_type = 'Dell' WHERE tagnumber = '$tagNum'";
            $conn->query($sql);
        }
    }
}
} else {
    echo "Cannot update this computer in the SQL database." . PHP_EOL;
}

$conn->close();
?>