#!/bin/bash
while true; do
serial=$(dmidecode --string system-serial-number)
tagNum=$(echo "SELECT tagnumber AS result FROM jobstats WHERE system_serial = '$serial' ORDER BY time DESC LIMIT 1" | /var/lib/UIT-TSS-TOOLBOX/select)
echo "remote|${tagNum}|present|$(date '+%Y-%m-%d %H:%M:%S')" | /var/lib/UIT-TSS-TOOLBOX/parse

if [[ -d /sys/class/power_supply/BAT0 ]]; then
    batCharge=0
    batStatus=""
    batCharge=$(cat /sys/class/power_supply/BAT0/capacity)
    batStatus=$(cat /sys/class/power_supply/BAT0/status)
elif [[ -d /sys/class/power_supply/BAT1 ]]; then
    batCharge=$(cat /sys/class/power_supply/BAT0/capacity)
    batStatus=$(cat /sys/class/power_supply/BAT0/status)
else
    batCharge="0"
fi
echo "remote|${tagNum}|battery_charge|${batCharge}" | /var/lib/UIT-TSS-TOOLBOX/parse
echo "remote|${tagNum}|battery_status|${batStatus}" | /var/lib/UIT-TSS-TOOLBOX/parse

cpuTemp=$(cat /sys/class/thermal/thermal_zone2/temp 2>/dev/null)
echo "remote|${tagNum}|cpu_temp|${cpuTemp}" | /var/lib/UIT-TSS-TOOLBOX/parse

if [[ -d /sys/class/nvme/nvme0/hwmon2 ]]; then
    diskTemp=0
    diskMax=0
    if [[ -f /sys/class/nvme/nvme0/hwmon2/temp1_input ]]; then
        diskTemp=$(cat /sys/class/nvme/nvme0/hwmon2/temp1_input)
    fi
    if [[ -f /sys/class/nvme/nvme0/hwmon2/temp1_max ]]; then
        diskMax=$(cat /sys/class/nvme/nvme0/hwmon2/temp1_max)
    fi
    echo "remote|${tagNum}|disk_temp|${diskTemp}|${diskMax}" | /var/lib/UIT-TSS-TOOLBOX/parse
fi

if [[ -d /sys/class/powercap ]]; then
    uj1=$(cat /sys/class/powercap/*/energy_uj 2>/dev/null)
    sleep 1
    uj2=$(cat /sys/class/powercap/*/energy_uj 2>/dev/null)
    a=0
    n=0
    for i in $uj1; do
        first=$(( a + i ))
    done

    for i in $uj2; do
        second=$(( n + i ))
    done

    echo "remote|${tagNum}|watts_now|${first}|${second}" | /var/lib/UIT-TSS-TOOLBOX/parse
fi

for i in $(ls /lib/modules); do
    echo "${i}" | grep -i --quiet "$(uname -r)"
    if [[ ${PIPESTATUS[1]} == "0" ]]; then
        echo "remote|${tagNum}|kernel_updated|1" | /var/lib/UIT-TSS-TOOLBOX/parse
        break
    else
        echo "remote|${tagNum}|kernel_updated|" | /var/lib/UIT-TSS-TOOLBOX/parse
    fi
done

if [[ $(echo "SELECT task AS result FROM remote WHERE tagnumber = '${tagNum}'" | /var/lib/UIT-TSS-TOOLBOX/select) == "cancel" ]]; then
    echo "remote|${tagNum}|task|" | /var/lib/UIT-TSS-TOOLBOX/parse
    echo "remote|${tagNum}|status|fail - Job cancelled :(" | /var/lib/UIT-TSS-TOOLBOX/parse
    UUID=$(echo "SELECT uuid AS 'result' FROM jobstats WHERE tagnumber = '${tagNum}' AND host_connected = 1 ORDER BY time DESC LIMIT 1" | /var/lib/UIT-TSS-TOOLBOX/select)
    echo "general|erase_completed||${UUID}" | /var/lib/UIT-TSS-TOOLBOX/parse
    echo "general|clone_completed||${UUID}" | /var/lib/UIT-TSS-TOOLBOX/parse
    pkill --terminal tty1
fi

#Network link speed
for i in $(ip addr | awk '/state UP/ {print $2}' | sed 's/://g'); do
    if [[ $(cat /sys/class/net/${i}/speed 2>/dev/null) != $(cat /tmp/net-link-speed-${i}.uit 2>/dev/null) ]]; then
        cat /sys/class/net/${i}/speed > /tmp/net-link-speed-${i}.uit
        $netSpeed=$(cat /tmp/net-link-speed-${i}.uit)
        echo "remote|${tagNum}|network_speed|$netSpeed" | /var/lib/UIT-TSS-TOOLBOX/parse
    fi
done

sleep 10

elapsed=0
elapsed=$(cat /root/uptime)
if [[ -z $elapsed ]]; then
    elapsed=0
fi

elapsed=$(( elapsed + 10 ))
echo "$elapsed" > /root/uptime
echo "remote|${tagNum}|uptime|$elapsed" | /var/lib/UIT-TSS-TOOLBOX/parse

done