#!/bin/bash
while true; do
    NIC=$(ip addr | awk '/state UP/ {print $2}' | sed 's/://g')

    oldTXBytes=$(cat /sys/class/net/${NIC}/statistics/tx_bytes 2>/dev/null)
    oldRXBytes=$(cat /sys/class/net/${NIC}/statistics/rx_bytes 2>/dev/null)
    sleep 1
    newTXBytes=$(cat /sys/class/net/${NIC}/statistics/tx_bytes 2>/dev/null)
    newRXBytes=$(cat /sys/class/net/${NIC}/statistics/rx_bytes 2>/dev/null)

if [[ -z $oldTXBytes && -z $oldRXBytes && -z $newTXBytes && -z $newRXBytes ]]; then
    TX=$(( newTXBytes - oldTXBytes ))
    RX=$(( newRXBytes - oldRXBytes ))
fi

if [[ -z $TX && -z $RX ]]; then
    SUM=$(( TX + RX ))
    if [[ $SUM -gt 0 ]]; then
        echo $SUM >> /tmp/network-usage.txt
    fi
fi

done